src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Customer ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <description>Customer Id of the Account</description>
        <formula>Account.Customer_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Login__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Login</label>
        <referenceTo>Customer_Login__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <description>Order Manager number. Cloud Trigger coded this field to open a new window and look up the order in order manager.</description>
        <externalId>true</externalId>
        <label>Order Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processing_Number__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>Order Manager Product Categories</description>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attorney Services</fullName>
                </value>
                <value>
                    <fullName>Business Formations</fullName>
                </value>
                <value>
                    <fullName>Intellectual Property</fullName>
                </value>
                <value>
                    <fullName>Legal Forms</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Personal Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Customer_Login__c.object
<CustomObject>
    <description>The equivalent of LZData User table</description>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <description>fkUser in User table in LZData</description>
        <externalId>true</externalId>
        <label>Customer Number</label>
        <length>13</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Customer Login</label>
    <nameField>
        <label>Customer Login/Email</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Login</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Login__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Login</label>
        <referenceTo>Customer_Login__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <formula>Base_Product__r.Product_Line__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Line</label>
        <referenceTo>Product_Line__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product_Line__c.object
<CustomObject>
    <description>matching ProductLine lookup table in LZData</description>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Relationship_Type__c.object
<CustomObject>
    <description>matching RelationshipType table in LZData</description>
    <label>Relationship Type</label>
    <nameField>
        <label>Relationship Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/OrderExceptionStatusPageControllerTest.cls
@isTest
public class OrderExceptionStatusPageControllerTest {
    static Product2 testProduct;
    final static String PRODUCT_LINE = 'Intellectual Property';
    static Product_Line__c testProductLine;
    static Id relationshipTypeId;
    static Id exceptionId;
    static Id caseId;
    static Order_Exception__c newExc;
    public static void dataSetup() {
        List<Account> testAcc = TestUtils.createAccounts(1, 'Smith', true);
        List<Contact> testCnt = TestUtils.createContacts(1, 'Smith', testAcc[0].Id, true);
        
        Customer_Login__c custLogin = new Customer_Login__c(name = 'AccountEmail@lz.com', Customer_ID__c = '12345678');
        insert custLogin;
        
        testProductLine = TestUtils.createProductLines(1 , PRODUCT_LINE , false)[0];
        testProductLine.Name = PRODUCT_LINE;
        insert testProductLine;
        
        relationshipTypeId = TestUtils.createRelationshipTypesTypes(1 , 'Process', true)[0].Id;
        
        testProduct = TestUtils.createProducts(1 , 'Test Product', false)[0];
        testProduct.Product_Line__c = testProductLine.Id;
        testProduct.Relationship_Type__c = relationshipTypeId;
        insert testProduct; 
        
        Order__c testOrder = TestUtils.createOrders(1 , testProduct.Id , true)[0];

        newExc = new Order_Exception__c();
        newExc.Order_Number__c = testOrder.Id;
        newExc.Status__c = 'Problem';
        newExc.Processing_Number__c='1234567';
        insert newExc;
        exceptionId = newExc.Id;
        
        Case testCase = TestUtils.createCases(1, false)[0];
        insert testCase;
        caseId = testCase.Id;
        /*
        Resources:
        JSON to string online converter -
        http://www.tools.knowledgewalls.com/jsontostring
        
        Online Multi Line to Single Line Converter -
        http://www.tools.knowledgewalls.com/onlinemultilinetosinglelineconverter
        */
        
        //testJSONstr = '"{ \"ordersComplete\": { \"success\": false } }"';
        
    }
    @isTest
    static void testLoadHoldStatusField() {
        dataSetup();
        IADTestMockGenerator mock = new IADTestMockGenerator();
        Map<String,Map<String,Object>> mapMap = new Map<String,Map<String,Object>>();
        Map<String, Object> orderItemIdToPdtCnfgId = new Map<String, Object>();
        orderItemIdToPdtCnfgId.put('overallRuleStatus',(Object)'passed');
        mapMap.put('overallOrderRuleStatus',orderItemIdToPdtCnfgId);
        String JSONresponse = JSON.serialize(mapMap);
        
        mock.testBody = JSONresponse;
        mock.statusCode = 200;
        
        
        
        
     Test.setMock(HttpCalloutMock.class, mock);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(newExc);
        OrderExceptionStatusPageController testCnt = new OrderExceptionStatusPageController(sc);
        testCnt.getThereAreOpenCases();
        testCnt.getOnHold();
        testCnt.putOnHold();
        Test.startTest();
        testCnt.removeFromHold();
        Test.stopTest();
    }
    
}