src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Customer ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <label>User Order ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Customer_Login__c.object
<CustomObject>
    <description>The equivalent of LZData User table</description>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <description>fkUser in User table in LZData</description>
        <externalId>true</externalId>
        <label>Customer Number</label>
        <length>13</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Customer Login</label>
    <nameField>
        <label>Customer Login/Email</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Login</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Login__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Login</label>
        <referenceTo>Customer_Login__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <formula>Base_Product__r.Product_Line__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Show process name of the base product on the order</description>
        <formula>Base_Product__r.Process__r.Name</formula>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <description>matching the fkUserOrder field of OrderItem table in lzdata</description>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Line</label>
        <referenceTo>Product_Line__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product_Line__c.object
<CustomObject>
    <description>matching ProductLine lookup table in LZData</description>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Relationship_Type__c.object
<CustomObject>
    <description>matching RelationshipType table in LZData</description>
    <label>Relationship Type</label>
    <nameField>
        <label>Relationship Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/POR_PNInjectionTest.cls
@isTest
public without sharing class POR_PNInjectionTest {
	public static String testJSONstr;
    public static String testJSONstr2;
    public static String testJSONstr3;
	static List<Order__c> testOrders;
    static List<Order_Item__c> orderItems;
	static Product2 testProduct;
	final static String PRODUCT_LINE = 'Intellectual Property';
	static Product_Line__c testProductLine;
	static Id relationshipTypeId;
    public static void dataSetup() {
		List<Account> testAcc = TestUtils.createAccounts(1, 'Smith', true);
	 	List<Contact> testCnt = TestUtils.createContacts(1, 'Smith', testAcc[0].Id, true);
		
		Customer_Login__c custLogin = new Customer_Login__c(name = 'AccountEmail@lz.com', Customer_ID__c = '12345678');
		insert custLogin;
		
		testProductLine = TestUtils.createProductLines(1 , PRODUCT_LINE , false)[0];
        testProductLine.Name = PRODUCT_LINE;
        insert testProductLine;
        
        relationshipTypeId = TestUtils.createRelationshipTypesTypes(1 , 'Process', true)[0].Id;
        
        testProduct = TestUtils.createProducts(1 , 'LWT', false)[0];
		testProduct.Product_Line__c = testProductLine.Id;
        testProduct.Relationship_Type__c = relationshipTypeId;
        insert testProduct; 
		
		testOrders = TestUtils.createOrders(1 , testProduct.Id , false);
		for (Order__c thisOrder : testOrders) {
			thisOrder.Name = '12345';
			thisOrder.User_Order_ID__c = '54321';
			thisOrder.Contact__c = testCnt[0].Id;
		}
		insert testOrders;

		orderItems = TestUtils.createOrderItems(1 , testOrders[0].Id, false);
        
        for (Order_Item__c orderItem : orderItems) {
            orderItem.User_Order_ID__c = '123456';
            orderItem.Product__c = testProduct.Id;
            orderItem.Name = '1234';
        }
        try {
            insert orderItems;
        }
        catch(Exception e) {
            System.debug(e);
        }


        

        
		/*
		Resources:
		JSON to string online converter -
		http://www.tools.knowledgewalls.com/jsontostring
		
		Online Multi Line to Single Line Converter -
		http://www.tools.knowledgewalls.com/onlinemultilinetosinglelineconverter
		*/
		
		//testJSONstr = '"{ \"ordersComplete\": { \"success\": true } }"';
		testJSONstr = '{ \"ordersComplete\": { \"success\": true } }';
	}
	@isTest
	static void testGetOrderData() {
		dataSetup();
		POR_PNInjectionButtonController_Ltng.getOrderData(orderItems[0].Id);
        POR_DDSWorkflowOrderInjectionService.orderNumber = 'test';
        POR_DDSWorkflowOrderInjectionService.processingNumber = 'test';
        //POR_DDSWorkflowOrderInjectionService.InjectionResponseWrapper test = new POR_DDSWorkflowOrderInjectionService.InjectionResponseWrapper();
        //test.ordersComplete.sucess = false;
	}
    @isTest
	static void testCheckIfRelaunchEligible() {
		dataSetup();
		POR_PNInjectionButtonController_Ltng.checkIfRelaunchEligible(orderItems[0].Id);
	}
	@isTest
	static void testInjectProcessingNumber() {
		dataSetup();
		IADTestMockGenerator mock = new IADTestMockGenerator();
    	mock.testBody = testJSONstr;
    	mock.statusCode = 200;
		
		Test.setMock(HttpCalloutMock.class, mock);
		Test.startTest();
        POR_PNInjectionButtonController_Ltng.orderName = 'Order';
        POR_PNInjectionButtonController_Ltng.TriggerDDS('12345', '54321');
		POR_PNInjectionButtonController_Ltng.injectProcessingNumber('12345', '54321', '54321');
        Test.stopTest();
	}
	@isTest
	static void testInjectProcessingNumberFail1() {
		dataSetup();
		POR_PNInjectionButtonController_Ltng.injectProcessingNumber(null, null, null);
	}
    
    @isTest
	static void testInjectProcessingNumberFail2() {
		dataSetup();
		IADTestMockGenerator mock = new IADTestMockGenerator();
    	mock.testBody = '"{ \"ordersComplete\": { \"success\": true } }"';
    	mock.statusCode = 200;
		
		Test.setMock(HttpCalloutMock.class, mock);
		Test.startTest();
        POR_PNInjectionButtonController_Ltng.orderName = 'Order';
        POR_PNInjectionButtonController_Ltng.TriggerDDS('12345', '54321');
		POR_PNInjectionButtonController_Ltng.injectProcessingNumber('12345', '54321', '54321');
        Test.stopTest();
	}
    @isTest
	static void testInjectProcessingNumberFail3() {
		dataSetup();
		IADTestMockGenerator mock = new IADTestMockGenerator();
    	mock.testBody = '{ \"ordersComplete\": { \"success\": false } }';
    	mock.statusCode = 200;
		
		Test.setMock(HttpCalloutMock.class, mock);
		Test.startTest();
        POR_PNInjectionButtonController_Ltng.orderName = 'Order';
        POR_PNInjectionButtonController_Ltng.TriggerDDS('12345', '54321');
		POR_PNInjectionButtonController_Ltng.injectProcessingNumber('12345', '54321', '54321');
        Test.stopTest();
	}
	@isTest
	static void testInjectProcessingNumberFail4() {
		dataSetup();
		IADTestMockGenerator mock = new IADTestMockGenerator();
    	mock.testBody = '"{ \"ordersComplete\": { \"success\": true } }"';
    	mock.statusCode = 500;
		
		Test.setMock(HttpCalloutMock.class, mock);
		Test.startTest();
        POR_PNInjectionButtonController_Ltng.orderName = 'Order';
        POR_PNInjectionButtonController_Ltng.TriggerDDS('12345', '54321');
		POR_PNInjectionButtonController_Ltng.injectProcessingNumber('12345', '54321', '54321');
        Test.stopTest();
	}
	
}