src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Customer ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Customer_Login__c.object
<CustomObject>
    <description>The equivalent of LZData User table</description>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <description>fkUser in User table in LZData</description>
        <externalId>true</externalId>
        <label>Customer Number</label>
        <length>13</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Customer Login</label>
    <nameField>
        <label>Customer Login/Email</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Login</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Login__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Login</label>
        <referenceTo>Customer_Login__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <formula>Base_Product__r.Product_Line__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Line</label>
        <referenceTo>Product_Line__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product_Line__c.object
<CustomObject>
    <description>matching ProductLine lookup table in LZData</description>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Relationship_Type__c.object
<CustomObject>
    <description>matching RelationshipType table in LZData</description>
    <label>Relationship Type</label>
    <nameField>
        <label>Relationship Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DDSWebServiceTest.cls
/*
Test coverage for DDSWebService class.
Created by: Artyom M.
Per story: B-24116
*/

@isTest
public with sharing class DDSWebServiceTest {
	public static String testJSONstr;
	static List<Order__c> testOrders;
	static Product2 testProduct;
	final static String PRODUCT_LINE = 'Intellectual Property';
	static Product_Line__c testProductLine;
	static Id relationshipTypeId;
	public static void dataSetup() {
		List<Account> testAcc = TestUtils.createAccounts(1, 'Smith', true);
	 	List<Contact> testCnt = TestUtils.createContacts(1, 'Smith', testAcc[0].Id, true);
		
		Customer_Login__c custLogin = new Customer_Login__c(name = 'AccountEmail@lz.com', Customer_ID__c = '12345678');
		insert custLogin;
		
		testProductLine = TestUtils.createProductLines(1 , PRODUCT_LINE , false)[0];
        testProductLine.Name = PRODUCT_LINE;
        insert testProductLine;
        
        relationshipTypeId = TestUtils.createRelationshipTypesTypes(1 , 'Process', true)[0].Id;
        
        testProduct = TestUtils.createProducts(1 , 'Test Product', false)[0];
		testProduct.Product_Line__c = testProductLine.Id;
        testProduct.Relationship_Type__c = relationshipTypeId;
        insert testProduct; 
		
		testOrders = TestUtils.createOrders(1 , testProduct.Id , false);
		for (Order__c thisOrder : testOrders) {
			thisOrder.Name = '12345';
			thisOrder.Contact__c = testCnt[0].Id;
		}
		insert testOrders;
		
		/*
		Resources:
		JSON to string online converter -
		http://www.tools.knowledgewalls.com/jsontostring
		
		Online Multi Line to Single Line Converter -
		http://www.tools.knowledgewalls.com/onlinemultilinetosinglelineconverter
		*/
		testJSONstr = '{ \"CaseId\":\"005G0000996V5KL\", \"firstName\":\"John\", \"lastName\":\"Doe\", \"uuid\": \"aafc2e65-2868-4b9a-8abd-ca69804b42e3\", \"email\": \"johndoe@yahoo.com\", \"customerId\": \"123987635\", \"phone\": \"5555555555\", \"OrderNumber\":\"12345\", \"Processing Number\":\"2345678\", \"CustomerLogin\":\"AccountEmail@lz.com\", \"ValidatedRules\": [ { \"Description\": \"View Compliance Calendar\" }, { \"Description\": \"View Completed Orders\"}, { \"Description\": \"Print Invoice\"}, { \"Description\": \"Set up Attorney/Tax Consultation\"}, { \"Description\": \"Company Profile\"}, { \"Description\": \"Account Profile\"}, { \"Description\": \"Make a Payment\"} ] }';
		
		
	}
	
	@isTest
	static void testCreateCaseSuccess() {
		dataSetup();
		RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
		req.requestURI = '/services/apexrest/DDSWebService/';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(testJSONstr);

        Test.startTest();
	        RestContext.request = req;
	        RestContext.response = res;
	
	        DDSWebService.createCase();
	
	        System.debug(req);
	        System.debug(res);
	
        Test.stopTest();
	}
	
	@isTest
	static void testCreateCaseNoSuccess() {
		dataSetup();
		RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
		req.requestURI = '/services/apexrest/DDSWebService/';
        req.httpMethod = 'POST';
        
        Test.startTest();
        	req.requestBody = Blob.valueOf(testJSONstr);

        
	        RestContext.request = req;
	        RestContext.response = res;
	
	        DDSWebService.createCase();
	
	        System.debug(req);
	        System.debug(res);
	        
	        req.requestBody = Blob.valueOf(testJSONstr);

        
	        RestContext.request = req;
	        RestContext.response = res;
	
	        DDSWebService.createCase();
	
	        System.debug(req);
	        System.debug(res);
        
        	req.requestBody = Blob.valueOf('{}');

        
	        RestContext.request = req;
	        RestContext.response = res;
	
	        DDSWebService.createCase();
	
	        System.debug(req);
	        System.debug(res);
	
        	req.requestBody = Blob.valueOf('');

        
	        RestContext.request = req;
	        RestContext.response = res;
	
	        DDSWebService.createCase();
	
	        System.debug(req);
	        System.debug(res);
        
        
        	req.requestBody = Blob.valueOf('empty');

        
	        RestContext.request = req;
	        RestContext.response = res;
	
	        DDSWebService.createCase();
	
	        System.debug(req);
	        System.debug(res);
	
        
        
        	req.requestBody = Blob.valueOf('{"orderNumber" : 123453}');

        
	        RestContext.request = req;
	        RestContext.response = res;
	
	        DDSWebService.createCase();
	
	        System.debug(req);
	        System.debug(res);
	
        Test.stopTest();
	}
    
}