src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies who the Account Manager is on the account</description>
        <label>Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Assigned_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Assigned User</description>
        <label>Assigned User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <description>Order Manager number. Cloud Trigger coded this field to open a new window and look up the order in order manager.</description>
        <externalId>true</externalId>
        <label>Order Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processing_Number__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>Order Manager Product Categories</description>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attorney Services</fullName>
                </value>
                <value>
                    <fullName>Business Formations</fullName>
                </value>
                <value>
                    <fullName>Intellectual Property</fullName>
                </value>
                <value>
                    <fullName>Legal Forms</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Personal Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <description>Queue field</description>
        <label>Queue</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Biz 501c3</fullName>
                </value>
                <value>
                    <fullName>Biz Alt Names</fullName>
                </value>
                <value>
                    <fullName>Biz Escalation</fullName>
                </value>
                <value>
                    <fullName>Biz HA Sweeps</fullName>
                </value>
                <value>
                    <fullName>Biz QC Approval</fullName>
                </value>
                <value>
                    <fullName>BIZ RA SOP</fullName>
                </value>
                <value>
                    <fullName>CC Biz</fullName>
                </value>
                <value>
                    <fullName>CC IP</fullName>
                </value>
                <value>
                    <fullName>CC Manager Call-Back</fullName>
                </value>
                <value>
                    <fullName>CC Mock Launch Requests</fullName>
                </value>
                <value>
                    <fullName>CC PS</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Billing Updates</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Materials</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Order Updates</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Post Filing</fullName>
                </value>
                <value>
                    <fullName>IP Copyrights</fullName>
                </value>
                <value>
                    <fullName>IP Partners and Firms</fullName>
                </value>
                <value>
                    <fullName>IP Patent Billing Updates</fullName>
                </value>
                <value>
                    <fullName>IP Patent Drawings</fullName>
                </value>
                <value>
                    <fullName>IP Patent Materials</fullName>
                </value>
                <value>
                    <fullName>IP Patent Order Updates</fullName>
                </value>
                <value>
                    <fullName>IP Patent Search Approval</fullName>
                </value>
                <value>
                    <fullName>IP Patents</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Billing Updates</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Monitoring</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Order Updates</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Search</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Search Approvals</fullName>
                </value>
                <value>
                    <fullName>IP Trademarks</fullName>
                </value>
                <value>
                    <fullName>IP Trademarks Goods and Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_outbound_emails__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Outbound Emails</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Product_Line__c</fullName>
        <formula>Base_Product__r.Product_Line__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Line</label>
        <referenceTo>Product_Line__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product_Line__c.object
<CustomObject>
    <description>matching ProductLine lookup table in LZData</description>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/QueueMap__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Maps the Email to the Queue Id.Used to map Cases to Queue based on Case Origin.</description>
    <fields>
        <fullName>AM_Queue_Name__c</fullName>
        <label>AM Queue Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <length>120</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <label>Queue Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>QueueMap</label>
</CustomObject>

src/objects/QueueMap_Default__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default Queue when QueueMap cannot be matched.</description>
    <fields>
        <fullName>Default_Queue_Name__c</fullName>
        <label>Default Queue Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>QueueMap Default</label>
</CustomObject>

src/objects/Relationship_Type__c.object
<CustomObject>
    <description>matching RelationshipType table in LZData</description>
    <label>Relationship Type</label>
    <nameField>
        <label>Relationship Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CaseServiceTest.cls
@isTest
public class CaseServiceTest{
    static       List<Case>    testCases;
    static       List<Account> testAccounts;
    static final Integer       CASE_SIZE = 10;
    static final String        ORIGIN = 'Tester@testy.com';
    static final String        CASEOBJECT = 'Case';
    static final String        BAD_ORIGIN = 'test5646@test.tst';
    static final String        WRONG_ORIGIN = 'testWrong1234@test.tst';
    static       Group         firstGroup;
    static       Group         secondGroup;
    static final String        QUEUE = 'Queue';
    static final String        FIRST_QUEUE = 'First Queue';
    static final String        SECOND_QUEUE = 'Second Queue';
    static final String        FIRST_QUEUE_DEV_NAME = 'First_Queue';
    static final String        SECOND_QUEUE_DEV_NAME = 'Second_Queue';
    static final String        WRONG_QUEUE_DEV_NAME = 'Wrong_Queue';

    static void setupData(){
        testCases = TestUtils.createCases(CASE_SIZE, false);
        
        // A Queue is a Group of Type 'Queue'. These are two Queues
        firstGroup  = new Group(Name = FIRST_QUEUE,  DeveloperName = FIRST_QUEUE_DEV_NAME,  Type = QUEUE);
        secondGroup = new Group(Name = SECOND_QUEUE, DeveloperName = SECOND_QUEUE_DEV_NAME, Type = QUEUE);
        
        insert new List<Group>{ firstGroup , secondGroup};
        
        QueueSobject firstMappingObject  = new QueueSobject(QueueId = firstGroup.Id,  SobjectType = CASEOBJECT);
        QueueSobject secondMappingObject = new QueueSobject(QueueId = secondGroup.Id, SobjectType = CASEOBJECT);
        
        System.runAs(TestUtils.ADMIN_USER){
            insert new List<QueueSobject>{firstMappingObject , secondMappingObject};
            QueueMap__c theMapping = new QueueMap__c(Name = ORIGIN, Origin__c = ORIGIN, 
                Queue_Name__c = FIRST_QUEUE_DEV_NAME);
            QueueMap__c theWrongMapping = new QueueMap__c(Name = WRONG_ORIGIN, Origin__c = WRONG_ORIGIN, 
                Queue_Name__c = WRONG_QUEUE_DEV_NAME);    
            insert new QueueMap__c[]{theMapping, theWrongMapping};
            
        }
        
    }
    
    static testMethod void testPopulateOwnerWithMissspellQueueName(){
        setupData();
        
        for(Case theCase : testCases){
            theCase.Origin = WRONG_ORIGIN;
        }
        
        QueueMap_Default__c defaultqueue = new QueueMap_Default__c();
        defaultqueue.name = 'QueueMap';
        defaultqueue.Default_Queue_Name__c = FIRST_QUEUE;
        insert defaultqueue;
        
        Test.startTest();
        insert testCases;
        Test.stopTest();
        List<Case> updatedCases = [SELECT Id, OwnerId , Queue__c FROM Case WHERE Id IN :testCases];
        for(Case theCase : updatedCases){
            System.assertEquals(firstGroup.Id,   theCase.OwnerId,  'Owner should have been updated to Queue');
            System.assertEquals(firstGroup.Name, theCase.Queue__c, 'Queue field should have been updated to right queue value');
        }
    }
    
    
    static testMethod void testPopulateOwnerWithQueueForOriginInCustomSetting(){
        setupData();
        
        for(Case theCase : testCases){
            theCase.Origin = ORIGIN;
        }
        
        Test.startTest();
        insert testCases;
        Test.stopTest();
        List<Case> updatedCases = [SELECT Id, OwnerId , Queue__c FROM Case WHERE Id IN :testCases];
        for(Case theCase : updatedCases){
            System.assertEquals(firstGroup.Id,   theCase.OwnerId,  'Owner should have been updated to Queue');
            System.assertEquals(firstGroup.Name, theCase.Queue__c, 'Queue field should have been updated to right queue value');
        }
    }
    
    static testMethod void testPopulateOwnerWithCreatedUserForOriginNotInCustomSetting(){
        setupData();
        
        for(Case theCase : testCases){
            theCase.Origin = BAD_ORIGIN;
        }
        
        Test.startTest();
        insert testCases;
        Test.stopTest();
        List<Case> updatedCases = [SELECT Id, OwnerId FROM Case WHERE Id IN :testCases];
        for(Case theCase : updatedCases){
            System.assertEquals(UserInfo.getUserId() , theCase.OwnerId , 'Owner should have been Created Owner as there is no custom setting defined.');
        }
    }
    
    static testMethod void testOwnerPopulatedWithSelectedQueue(){
        setupData();
        insert testCases;
        testCases = [SELECT Id, OwnerId , Origin FROM Case WHERE Id IN :testCases];
        for(Case theCase : testCases){
            theCase.Queue__c = SECOND_QUEUE;
        }
        
        Test.startTest();
          update testCases;   
        Test.stopTest();
        List<Case> updatedCases = [SELECT Id, OwnerId FROM Case WHERE Id IN :testCases];
        for(Case theCase : updatedCases){
            System.assertEquals(secondGroup.id , theCase.OwnerId , 'Owner should have been updated to Queue');
        }
    }
    /*
    static testmethod void testAMoverride(){
        User am = TestUtils.ACCOUNT_MANAGER_USER;
        System.runAs(TestUtils.ADMIN_USER){
            insert am;
        }
        
        Group nonAmGroup  = new Group(Name = FIRST_QUEUE,  DeveloperName = FIRST_QUEUE_DEV_NAME,  Type = QUEUE);
        Group amGroup = new Group(Name = SECOND_QUEUE, DeveloperName = SECOND_QUEUE_DEV_NAME, Type = QUEUE);
        
        insert new List<Group>{ nonAmGroup , amGroup};
        
        QueueSobject nonAmQueue  = new QueueSobject(QueueId = nonAmGroup.Id,  SobjectType = CASEOBJECT);
        QueueSobject amQueue = new QueueSobject(QueueId = amGroup.Id, SobjectType = CASEOBJECT);
        
        System.runAs(TestUtils.ADMIN_USER){
            insert new List<QueueSobject>{nonAmQueue , amQueue};
            QueueMap__c theMapping = new QueueMap__c(Name = ORIGIN, Origin__c = ORIGIN, 
                Queue_Name__c = FIRST_QUEUE_DEV_NAME, AM_Queue_Name__c = SECOND_QUEUE_DEV_NAME);
            insert theMapping;
        }
        Account amAcct = new Account(Name='AM Account', Business_Account_Manager__c=am.Id);
        Account nonAmAcct = new Account(Name='Non AM Account');
        insert new Account[]{amAcct, nonAmAcct};
        Contact amContact = new Contact(LastName='AM Contact', AccountId=amAcct.Id);
        Contact nonAmContact = new Contact(LastName='Non AM Contact', AccountId=nonAmAcct.Id);
        insert new Contact[]{amContact, nonAmContact};
        Case amCase = new Case(Subject='AM Case Subject', ContactId=amContact.Id, Origin=ORIGIN, Assigned_User__c=null);
        Case nonAmCase = new Case(Subject='Non AM Case Subject', ContactId=nonAmContact.Id, Origin=ORIGIN, Assigned_User__c=null);
        
        Test.startTest();
        
        System.assertEquals(amAcct.Business_Account_Manager__c, am.Id, 
            'amAcct.Business_Account_Manager__c should be equal to am.Id but it is ' + amAcct.Business_Account_Manager__c);
        insert new Case[]{amCase, nonAmCase};
        
        amCase = [SELECT Id, OwnerId, Subject, Assigned_User__c FROM Case WHERE Id = :amCase.Id LIMIT 1];
        nonAmCase = [SELECT Id, OwnerId, Subject, Assigned_User__c FROM Case WHERE Id = :nonAmCase.Id LIMIT 1];
        // amCase should have Assigned User set, nonAmCase should not
        System.assertEquals(amCase.Assigned_User__c, am.Id);
        System.assertNotEquals(nonAmCase.Assigned_User__c, am.Id);
        
        // amCase should be owned by amQueue, nonAmCase by nonAmQueue
        System.assertEquals( amCase.OwnerId, amGroup.Id);
        System.assertEquals( nonAmCase.OwnerId, nonAmGroup.Id);
        Test.stopTest();
    }
    */
     static testmethod void testCloseExceptionsAndCases() {
       IADTestMockGenerator mock = new IADTestMockGenerator();
       Map<String,Map<String,Object>> mapMap = new Map<String,Map<String,Object>>();
        Map<String, Object> orderItemIdToPdtCnfgId = new Map<String, Object>();
        orderItemIdToPdtCnfgId.put('overallRuleStatus',(Object)'passed');
        mapMap.put('overallOrderRuleStatus',orderItemIdToPdtCnfgId);
        String JSONresponse = JSON.serialize(mapMap);
        
        mock.testBody = JSONresponse;
        mock.statusCode = 200;
       
        Test.setMock(HttpCalloutMock.class, mock);
    Product2 testProduct;
    String PRODUCT_LINE = 'Intellectual Property';
    Product_Line__c testProductLine;
    testProductLine = TestUtils.createProductLines(1 , PRODUCT_LINE , false)[0];
        testProductLine.Name = PRODUCT_LINE;
        insert testProductLine;
        
        Id relationshipTypeId = TestUtils.createRelationshipTypesTypes(1 , 'Process', true)[0].Id;
        
        testProduct = TestUtils.createProducts(1 , 'Test Product', false)[0];
    testProduct.Product_Line__c = testProductLine.Id;
        testProduct.Relationship_Type__c = relationshipTypeId;
        insert testProduct; 
    
    Order__c testOrder = TestUtils.createOrders(1 , testProduct.Id , true)[0];

    Order_Exception__c newExc = new Order_Exception__c();
        newExc.Order_Number__c = testOrder.Id;
        newexc.Processing_Number__c='1234567';
        newexc.Status__c='resolved';
        insert newExc;
    
    Case testCase = TestUtils.createCases(1, false)[0];
    testCase.Order_Exception__c = newExc.Id;
    testcase.Processing_Number__c='1234567';
        insert testCase;
        Set<Id> orderIds = new Set<Id>();
        orderIds.add(testOrder.Id);
        List<id> caseid = new list<id>();
        caseid.add(testcase.id);
        test.starttest();
        
        caseservice.problemCaseCloseUpdates(caseid);
        
        test.stoptest();
        
        }
        static testmethod void testCloseExceptionsAndCasesorders() {
       IADTestMockGenerator mock = new IADTestMockGenerator();
       Map<String,Map<String,Object>> mapMap = new Map<String,Map<String,Object>>();
        Map<String, Object> orderItemIdToPdtCnfgId = new Map<String, Object>();
        orderItemIdToPdtCnfgId.put('overallRuleStatus',(Object)'passed');
        mapMap.put('overallOrderRuleStatus',orderItemIdToPdtCnfgId);
        String JSONresponse = JSON.serialize(mapMap);
        
        mock.testBody = JSONresponse;
        mock.statusCode = 200;
       
        Test.setMock(HttpCalloutMock.class, mock);
    Product2 testProduct;
    String PRODUCT_LINE = 'Intellectual Property';
    Product_Line__c testProductLine;
    testProductLine = TestUtils.createProductLines(1 , PRODUCT_LINE , false)[0];
        testProductLine.Name = PRODUCT_LINE;
        insert testProductLine;
        
        Id relationshipTypeId = TestUtils.createRelationshipTypesTypes(1 , 'Process', true)[0].Id;
        
        testProduct = TestUtils.createProducts(1 , 'Test Product', false)[0];
    testProduct.Product_Line__c = testProductLine.Id;
        testProduct.Relationship_Type__c = relationshipTypeId;
        insert testProduct; 
    
    Order__c testOrder = TestUtils.createOrders(1 , testProduct.Id , true)[0];

    Order_Exception__c newExc = new Order_Exception__c();
        newExc.Order_Number__c = testOrder.Id;
        newexc.Processing_Number__c='1234567';
        newexc.Status__c='resolved';
        insert newExc;
     
    Case testCase = TestUtils.createCases(1, false)[0];
    testCase.Order_Exception__c = newExc.Id;
    testcase.Processing_Number__c='1234567';
        insert testCase;
        Set<Id> orderIds = new Set<Id>();
        orderIds.add(testOrder.Id);
         Id rtId_Biz = Schema.SObjectType.Failed_Rules__c.getRecordTypeInfosByName().get('Manual').getRecordTypeId();
        Failed_Rules__c rl = new Failed_Rules__c();
                rl.Parent_Exception__c = newExc.id;
                rl.Rule_Type__c = 'Manual';
                
                
                rl.RecordTypeId = rtId_Biz;
                   rl.Description__c = 'test';
                rl.Status__c = 'Active';
                insert rl;
        List<id> caseid = new list<id>();
        caseid.add(newExc.id);
        test.starttest();
        
        caseservice.problemCaseCloseUpdates(caseid);
        
        test.stoptest();
        
        }
        static testmethod void testCloseExceptionsccclosure() {
       IADTestMockGenerator mock = new IADTestMockGenerator();
       Map<String,Map<String,Object>> mapMap = new Map<String,Map<String,Object>>();
        Map<String, Object> orderItemIdToPdtCnfgId = new Map<String, Object>();
        orderItemIdToPdtCnfgId.put('overallRuleStatus',(Object)'passed');
        mapMap.put('overallOrderRuleStatus',orderItemIdToPdtCnfgId);
        String JSONresponse = JSON.serialize(mapMap);
        
        mock.testBody = JSONresponse;
        mock.statusCode = 200;
       
        Test.setMock(HttpCalloutMock.class, mock);
    Product2 testProduct;
    String PRODUCT_LINE = 'Intellectual Property';
    Product_Line__c testProductLine;
    testProductLine = TestUtils.createProductLines(1 , PRODUCT_LINE , false)[0];
        testProductLine.Name = PRODUCT_LINE;
        insert testProductLine;
        
        Id relationshipTypeId = TestUtils.createRelationshipTypesTypes(1 , 'Process', true)[0].Id;
        
        testProduct = TestUtils.createProducts(1 , 'Test Product', false)[0];
    testProduct.Product_Line__c = testProductLine.Id;
        testProduct.Relationship_Type__c = relationshipTypeId;
        insert testProduct; 
    
    Order__c testOrder = TestUtils.createOrders(1 , testProduct.Id , true)[0];

    Order_Exception__c newExc = new Order_Exception__c();
        newExc.Order_Number__c = testOrder.Id;
        newexc.Processing_Number__c='1234567';
        newexc.Status__c='resolved';
        insert newExc;
     
    Case testCase = TestUtils.createCases(1, false)[0];
    testCase.Order_Exception__c = newExc.Id;
    testcase.Processing_Number__c='1234567';
        insert testCase;
        Set<Id> orderIds = new Set<Id>();
        orderIds.add(testOrder.Id);
         Id rtId_Biz = Schema.SObjectType.Failed_Rules__c.getRecordTypeInfosByName().get('Manual').getRecordTypeId();
        Failed_Rules__c rl = new Failed_Rules__c();
                rl.Parent_Exception__c = newExc.id;
                rl.Rule_Type__c = 'Manual';
                
                
                rl.RecordTypeId = rtId_Biz;
                   rl.Description__c = 'test';
                rl.Status__c = 'Active';
                insert rl;
        List<id> caseid = new list<id>();
        caseid.add(newExc.id);
        test.starttest();
        
        caseservice.ccCaseClosure(testcase.id,'1234567');
        
        test.stoptest();
        
        }
        
    //@Sai
    @isTest
    static void updateContactOnCase_Test() {

        Product2 testProduct;
        String PRODUCT_LINE = 'Intellectual Property';
        Product_Line__c testProductLine;
        testProductLine = TestUtils.createProductLines(1 , PRODUCT_LINE , false)[0];
        testProductLine.Name = PRODUCT_LINE;
        insert testProductLine;

        Id relationshipTypeId = TestUtils.createRelationshipTypesTypes(1 , 'Process', true)[0].Id;

        testProduct = TestUtils.createProducts(1 , 'Test Product', false)[0];
        testProduct.Product_Line__c = testProductLine.Id;
        testProduct.Relationship_Type__c = relationshipTypeId;
        insert testProduct;

        Order__c testOrder = TestUtils.createOrders(1 , testProduct.Id , true)[0];

        Order_Exception__c newExc = new Order_Exception__c();
        newExc.Order_Number__c = testOrder.Id;
        newexc.Processing_Number__c = '1234567';
        newexc.Status__c = 'resolved';
        insert newExc;

        Case theCase = new Case();
        theCase.Order_Exception__c = newExc.Id;
        theCase.Processing_Number__c = '1234567';
        theCase.Order__c = testOrder.Id;
        theCase.recordTypeId = ProblemOrderRoutingService.developerNameToRecordTypeIds.get(ProblemOrderConstants.PROBLEM_CASE_RECORD_TYPE);
        theCase.Total_outbound_emails__c = 100;
        //theCase.ManualruleStatus__c = 'Problem';
        insert theCase;

        update theCase; //==> to call updateContactOnCase()

        system.assert([select Total__c from Order_Exception__c].Total__c == 100);
    }
}