src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Case_Status__c</fullName>
        <label>Case Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Researching</fullName>
                </value>
                <value>
                    <fullName>Waiting on Customer</fullName>
                </value>
                <value>
                    <fullName>Updated by Customer</fullName>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_Reasons__c</fullName>
        <label>Status Reasons</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Researching</fullName>
                </value>
                <value>
                    <fullName>Updated by Customer</fullName>
                </value>
                <value>
                    <fullName>Waiting on Customer</fullName>
                </value>
                <value>
                    <fullName>Assigned for Resolution</fullName>
                </value>
                <value>
                    <fullName>Issue Resolved</fullName>
                </value>
                <value>
                    <fullName>Order Cancelled</fullName>
                </value>
                <value>
                    <fullName>Customer Proceeding As Is</fullName>
                </value>
                <value>
                    <fullName>Customer-Requested Item Complete</fullName>
                </value>
                <value>
                    <fullName>Auto Closed (Timeout)</fullName>
                </value>
                <value>
                    <fullName>No Action Required</fullName>
                </value>
                <value>
                    <fullName>LZM</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Social Media</fullName>
                </value>
                <value>
                    <fullName>BBB</fullName>
                </value>
                <value>
                    <fullName>Escalated Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Closed_When_Opened__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Closed When Opened</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status_Reasons__c</fullName>
        <label>Status Reasons</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned for Customer Outreach</fullName>
                </value>
                <value>
                    <fullName>LZ Research Required</fullName>
                </value>
                <value>
                    <fullName>Assigned for Resolution</fullName>
                </value>
                <value>
                    <fullName>Updated by Customer</fullName>
                </value>
                <value>
                    <fullName>Customer Submitting Revision</fullName>
                </value>
                <value>
                    <fullName>Customer Submitting Materials</fullName>
                </value>
                <value>
                    <fullName>Customer didn&apos;t have needed info</fullName>
                </value>
                <value>
                    <fullName>Call attempted - Customer not reached (VM/disconnect)</fullName>
                </value>
                <value>
                    <fullName>Email Sent, Pending Response</fullName>
                </value>
                <value>
                    <fullName>LZM</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Social Media</fullName>
                </value>
                <value>
                    <fullName>BBB</fullName>
                </value>
                <value>
                    <fullName>Escalated Customer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Issue Resolved (non Proofer resolution)</fullName>
                </value>
                <value>
                    <fullName>Revision Placed for Customer</fullName>
                </value>
                <value>
                    <fullName>Proofer Updated</fullName>
                </value>
                <value>
                    <fullName>Customer Proceeding As Is/No Update Required</fullName>
                </value>
                <value>
                    <fullName>Order Cancelled</fullName>
                </value>
                <value>
                    <fullName>Customer-Requested Item Complete</fullName>
                </value>
                <value>
                    <fullName>No Order Problem (Case Created in Error)</fullName>
                </value>
                <value>
                    <fullName>Auto Closed (Timeout) - Unresolved</fullName>
                </value>
                <value>
                    <fullName>Revision placed on LZ.com</fullName>
                </value>
                <value>
                    <fullName>Revision placed on LZ.com (after 7 day closure)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Genesys_Interaction_Id__c</fullName>
        <description>Genesys Interaction Id</description>
        <externalId>true</externalId>
        <label>Genesys Interaction Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IADCaseHelper.cls
public with sharing class IADCaseHelper {
   
     public static void createActivityForCaseInsert(Case theCase , String description)
   {
       createActivity(theCase , description , false);
       if(theCase.Status == 'Closed')
           theCase.Closed_When_Opened__c = true;
            
       update theCase;
   }
   
   public static void createActivityForCaseUpdate(Case theCase , String description)
   {
       createActivity(theCase , description , true);
   }
    public static void createActivity(Case theCase , String description , Boolean isCreateComment)
    {   
        Recordtype ccRecType = [select id, name from recordtype where sobjecttype = 'Task' and name = 'CC Task' limit 1];
        Task theTask = new Task();
        theTask.CallObject = theCase.Contact.Genesys_Interaction_Id__c ;
        theTask.Subject = 'Case Activity';
        theTask.Status = 'Completed';
        theTask.Case_Status__c = theCase.Status;
        theTask.Status_Reasons__c = theCase.Status_Reasons__c;
        theTask.whatId = theCase.Id;
        theTask.whoId = theCase.ContactId;
        theTask.Case_Status__c = theCase.Status;
        theTask.recordtype = ccRecType;
        theTask.Description = description;
        
        insert theTask;
        if(isCreateComment)
        {
            CaseComment theComment = new CaseComment();
            theComment.commentBody = theTask.Description;
            theComment.ParentId = theCase.Id;
            insert theComment;
        }        
      
    }
    
}