src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <label>Processing Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <label>Queue</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abandoner</fullName>
                </value>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>RA Renewal</fullName>
                </value>
                <value>
                    <fullName>Decline</fullName>
                </value>
                <value>
                    <fullName>Retention</fullName>
                </value>
                <value>
                    <fullName>Biz Starter</fullName>
                </value>
                <value>
                    <fullName>Quick Start</fullName>
                </value>
                <value>
                    <fullName>Pilot Group</fullName>
                </value>
                <value>
                    <fullName>PostUp</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order_Number__c</fullName>
        <description>Order Manager number. Cloud Trigger coded this field to open a new window and look up the order in order manager.</description>
        <externalId>true</externalId>
        <label>Order Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processing_Number__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <label>Processing Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <description>Queue field</description>
        <label>Queue</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Biz 501c3</fullName>
                </value>
                <value>
                    <fullName>Biz Alt Names</fullName>
                </value>
                <value>
                    <fullName>Biz Escalation</fullName>
                </value>
                <value>
                    <fullName>Biz HA Sweeps</fullName>
                </value>
                <value>
                    <fullName>Biz QC Approval</fullName>
                </value>
                <value>
                    <fullName>BIZ RA SOP</fullName>
                </value>
                <value>
                    <fullName>CC Biz</fullName>
                </value>
                <value>
                    <fullName>CC IP</fullName>
                </value>
                <value>
                    <fullName>CC Manager Call-Back</fullName>
                </value>
                <value>
                    <fullName>CC Mock Launch Requests</fullName>
                </value>
                <value>
                    <fullName>CC PS</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Billing Updates</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Materials</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Order Updates</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Post Filing</fullName>
                </value>
                <value>
                    <fullName>IP Copyrights</fullName>
                </value>
                <value>
                    <fullName>IP Partners and Firms</fullName>
                </value>
                <value>
                    <fullName>IP Patent Billing Updates</fullName>
                </value>
                <value>
                    <fullName>IP Patent Drawings</fullName>
                </value>
                <value>
                    <fullName>IP Patent Materials</fullName>
                </value>
                <value>
                    <fullName>IP Patent Order Updates</fullName>
                </value>
                <value>
                    <fullName>IP Patent Search Approval</fullName>
                </value>
                <value>
                    <fullName>IP Patents</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Billing Updates</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Monitoring</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Order Updates</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Search</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Search Approvals</fullName>
                </value>
                <value>
                    <fullName>IP Trademarks</fullName>
                </value>
                <value>
                    <fullName>IP Trademarks Goods and Services</fullName>
                </value>
                <value>
                    <fullName>CC General Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <description>matching the fkUserOrder field of OrderItem table in lzdata</description>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Processing_Status__c.object
<CustomObject>
    <label>Processing Status</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processing Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductLine_Queue_Map__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Map of ProductLine to Queue Map when the Processors create the Case on Notepad</description>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <label>Queue Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ProductLine Queue Map</label>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Note</fullName>
        <active>true</active>
        <description>Order Note from Notepad</description>
        <label>Note</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NextPadController.cls
public with sharing class NextPadController
{
    
    public String processingNumber{get;set;}
    public String customerOrderNumber{get;set;}
    public String description{get;set;}
    public NextPadService theNextPadService{get;set;}  
    public String selectedNoteType{get;set;}
    public String productName{get;set;}
    public String productLine{get;set;}
    public String contactState{get;set;}
    public String processingStatus{get;set;}
    public Id contactId{get;set;}
    public String orderId{get;set;}
    public String orderNumber{get;set;}
   
    public Map<String,NoteWrapper> objectIdToWrapper{get;set;}
    
    public String sortOrder{get;set;}
    public String filterNoteType{get;set;}
    
    public transient List<NoteWrapper> allNotes{get;set;}
    public String userSortOrder{get;set;}
    private final Order_Item__c theItem;
    public Boolean showEdit{get;set;}
    final  static String NO_EDIT = 'noEdit';
    public String orderItemId{get;set;}
    public String stateOfFormation{get;set;}
    final static String BUSINESS_FORMATIONS = 'Business Formations';
	public Boolean getIsClassic() {
    	return (UserInfo.getUiThemeDisplayed() == 'Theme3');
    }
    public NextPadController(ApexPages.StandardController stdController) 
    {
         
        showEdit = true;
        theNextPadService = new NextPadService();
        filterNoteType = NextPadService.ALL;
        sortOrder = NextPadService.DESC_ORDER;
        userSortOrder = '';   
        if(stdController.getRecord() != null)
        {
            orderItemId = stdController.getId();
            for(Order_Item__c theItem : [SELECT Id , User_Order_ID__c FROM Order_Item__c WHERE Id = :stdController.getId()])
            {
                processingNumber = theItem.User_Order_ID__c;
                
            }
            if(orderItemId != null)
                showEdit = false;//don't show NextPadEdit Section inside Salesforce
        }
        Map<String, String> currentParams = ApexPages.currentPage().getParameters();
        if(currentParams.containsKey(NextPadService.PROCESS_NUMBER))
        {
           processingNumber = currentParams.get(NextPadService.PROCESS_NUMBER);
           
        }
        //Story B-19202 SF Archival Ledger Update - Added customerOrderNumber to parse the parameter and use to 
        //get Order details in case of no Order items due to archival - 
        if(currentParams.containsKey(NextPadService.ORDER_NUMBER))
        {
           customerOrderNumber = currentParams.get(NextPadService.ORDER_NUMBER);
           
        }
        system.debug ('customerOrderNumber:'+customerOrderNumber);
        if((processingNumber != null && processingNumber != '0' && processingNumber != '') || orderItemId != null || customerOrderNumber !=null)
        {
            theNextPadService.processingNumber = processingNumber;
            theNextPadService.customerOrderNumber = customerOrderNumber;
            theNextPadService.populateAllInformationByProcessingNumber(processingNumber , orderItemId, customerOrderNumber);
            allNotes = theNextPadService.noteWrappers;
            sortNotes();         
        }
        else
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Order note cannot be entered since there is no processing number'));
        }
    
    }
    public PageReference Save()
    {
        return null;
    }
  
    public PageReference SaveNote()
    {
               
        if(description == '' || description == null)
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Please enter description'));
        }
        else
        {
            processingNumber = theNextPadService.processingNumber;
            orderNumber = theNextPadService.orderNumber;
            orderId = theNextPadService.orderId;
            productLine = theNextPadService.productLine;
            contactState = theNextPadService.contactState;
            processingStatus = theNextPadService.processingStatus;
            stateOfFormation = theNextPadService.stateOfFormation;
            contactId = theNextPadService.contactId;
            productName = theNextPadService.productName;
       
            if(selectedNoteType == NextPadService.ORDER_NOTE)
            {
                
                createOrderNotes(description);
                description = '';
                //Create Order Activity
            }
            else if(selectedNoteType == NextPadService.PROBLEM_ORDER)
            {
                createCase(description);
                description = '';
                //Create Case
            }
        }
        populateAllNotes(); 
        sortNotes();
        return null;
    }

    public PageReference clear()
    {
        description = '';
        populateAllNotes();
        sortNotes(); 
        return null;
    }

  
  
      //Needs to create Activity
    public void createOrderNotes(String description)
    {
        Task theTask = new Task();
        theTask.Description = description;
        theTask.WhatId = orderId;
        theTask.Subject = NextPadService.ORDER_NOTE;
        theTask.Status = 'Completed';
        theTask.ActivityDate = Date.today();
        theTask.Type = 'Note';
        theTask.User_Order_ID__c = processingNumber;
        
        try
        {
            insert theTask;//TODO-Error Handling
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Order Note Created'));
        }
        catch(DMLException dmlEx)
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Failed Creating Order Note'));
        }
    }

    public void createCase(String description)
    {
        Case theCase = new Case();
        String theState = '';
        if(productline == BUSINESS_FORMATIONS && (stateOfFormation != null && stateOfFormation != ''))
            theState = stateOfFormation;
        else
            theState = contactState;

        theCase.Subject = processingNumber+' - '+productName+' - '+theState;
        theCase.description = description;
        theCase.Processing_Number__c = processingNumber;
        theCase.Order_Number__c = orderNumber;
        theCase.Processing_Status__c = processingStatus;
        theCase.Origin = 'Fulfillment';
        theCase.ContactId = contactId;
        
        if(productLineToQueueName.containsKey(productLine))
            theCase.Queue__c = productLineToQueueName.get(productLine);
        else
            theCase.Queue__c = 'CC General Support';
        try
        {
            insert theCase;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Case Created'));

        }
        catch(DMlException dmlEx)
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Failed Creating Case '+dmlEx.getMessage()));
        }
    }


    public void populateAllNotes()
    {
       
        theNextPadService.populateAllInformationByProcessingNumber(processingNumber ,orderItemId, customerOrderNumber);
        allNotes = theNextPadService.noteWrappers;
    }
    
    public void sortNotesByDateTime()
    {
        
        userSortOrder = '';
      
        NoteWrapper.SORT_FIELD = NoteWrapper.SortField.DateTimeCreated;
        if(sortOrder == NextPadService.DESC_ORDER)
            NoteWrapper.SORT_DIR = NoteWrapper.SortDirection.DESCENDING;
        else
            NoteWrapper.SORT_DIR = NoteWrapper.SortDirection.ASCENDING;
        
        if(allNotes == null)
            populateAllNotes();
                
        if(allNotes != null)
        {
            allNotes.sort();
            for(NoteWrapper theWrapper : allNotes)
            {
                theWrapper.caseComments.sort();
            }
        }

    }

    public void sortNotesByUser()
    {
        sortOrder = '';
       
        NoteWrapper.SORT_FIELD = NoteWrapper.SortField.Name;
        if(userSortOrder == NextPadService.DESC_ORDER)
            NoteWrapper.SORT_DIR = NoteWrapper.SortDirection.DESCENDING;
        else
            NoteWrapper.SORT_DIR = NoteWrapper.SortDirection.ASCENDING;
        
        if(allNotes == null)
            populateAllNotes();

        if(allNotes != null)
        {
            allNotes.sort();
            for(NoteWrapper theWrapper : allNotes)
            {
                theWrapper.caseComments.sort();
            }
        }   
    }

    public void filterNotes()
    {
        
        theNextPadService.filterNoteType = filterNoteType;
        populateAllNotes();
        sortNotes();
    }
    
   

    public void sortNotes()
    {
        if(sortOrder != '')
            sortNotesByDateTime();
        else if(userSortOrder != '')
            sortNotesByUser();
    }

    public Map<String,String> productLineToQueueName
    {
        get
        {
            if(productLineToQueueName == null)
            {
                productLineToQueueName = new Map<String,String>();
                for(ProductLine_Queue_Map__c theMap : ProductLine_Queue_Map__c.getAll().values())
                {
                    productLineToQueueName.put(theMap.Name , theMap.Queue_Name__c);
                }
                
            }
            return productLineToQueueName;
        }
        set;
    }

}