src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Call_Type__c</fullName>
        <label>Call Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unique Queue</fullName>
                </value>
                <value>
                    <fullName>Unique Outbound</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Outbound Follow Up</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No-VM</fullName>
                </value>
                <value>
                    <fullName>No-NM</fullName>
                </value>
                <value>
                    <fullName>No-Email</fullName>
                </value>
                <value>
                    <fullName>No-Final</fullName>
                </value>
                <value>
                    <fullName>Yes-SNE</fullName>
                </value>
                <value>
                    <fullName>Yes-Talk</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Commission Eligible</fullName>
                </value>
                <value>
                    <fullName>VM Attempt 1</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 2</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 3</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 4</fullName>
                </value>
                <value>
                    <fullName>VM Final Attempt</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Ineligible</fullName>
                </value>
                <value>
                    <fullName>Call Transferred</fullName>
                </value>
                <value>
                    <fullName>Service Unavailable</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inbound_Outbound__c</fullName>
        <label>Call Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <label>Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress (Assigned)</fullName>
                </value>
                <value>
                    <fullName>Qualified (Interested)</fullName>
                </value>
                <value>
                    <fullName>Closed Lost - No Interest</fullName>
                </value>
                <value>
                    <fullName>Closed/Lost - No Activity</fullName>
                </value>
                <value>
                    <fullName>Closed/Lost - Bad Info</fullName>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                </value>
                <value>
                    <fullName>VM - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Unable to Contact/Bad Number/NM</fullName>
                </value>
                <value>
                    <fullName>Already Purchased</fullName>
                </value>
                <value>
                    <fullName>Response/Research Pending</fullName>
                </value>
                <value>
                    <fullName>Do Not Call</fullName>
                </value>
                <value>
                    <fullName>NM - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>NM - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>VM - Final Attempt</fullName>
                </value>
                <value>
                    <fullName>Transaction Complete</fullName>
                </value>
                <value>
                    <fullName>Soft SNE</fullName>
                </value>
                <value>
                    <fullName>Hard SNE</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_For_Contact__c</fullName>
        <label>Reason For Contact</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing Inquiry</fullName>
                </value>
                <value>
                    <fullName>Cancel Order</fullName>
                </value>
                <value>
                    <fullName>EIN Inquiry</fullName>
                </value>
                <value>
                    <fullName>General Service Inquiry</fullName>
                </value>
                <value>
                    <fullName>Make Revisions/Updates to Order</fullName>
                </value>
                <value>
                    <fullName>Problem Status Inquiry</fullName>
                </value>
                <value>
                    <fullName>Requesting Documents</fullName>
                </value>
                <value>
                    <fullName>Submitting Materials</fullName>
                </value>
                <value>
                    <fullName>Subscription Assistance</fullName>
                </value>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>Change Package/Upgrade/Downgrade</fullName>
                </value>
                <value>
                    <fullName>Order in Problem Status</fullName>
                </value>
                <value>
                    <fullName>Update Order</fullName>
                </value>
                <value>
                    <fullName>Status Inquiry</fullName>
                </value>
                <value>
                    <fullName>Questionnaire Inquiries</fullName>
                </value>
                <value>
                    <fullName>Product/Service Overview</fullName>
                </value>
                <value>
                    <fullName>Pricing Questions/Quotes</fullName>
                </value>
                <value>
                    <fullName>Transfer to Customer Care</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_For_Transfer__c</fullName>
        <label>Reason For Transfer</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Reason_For_Contact__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>New Sales Inquiry</fullName>
                </value>
                <value>
                    <fullName>G&amp;S Team Inquiry</fullName>
                </value>
                <value>
                    <fullName>SET Team Inquiry</fullName>
                </value>
                <value>
                    <fullName>Cancel Subscription</fullName>
                </value>
                <value>
                    <fullName>501c3</fullName>
                </value>
                <value>
                    <fullName>VIP/Escalation</fullName>
                </value>
                <value>
                    <fullName>Mock Launch Request</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VM Attempt 1</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 2</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 3</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 4</fullName>
                </value>
                <value>
                    <fullName>VM Final Attempt</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Commission Eligible</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Ineligible</fullName>
                </value>
                <value>
                    <fullName>Call Transferred</fullName>
                </value>
                <value>
                    <fullName>Service Unavailable</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Genesys_Interaction_Id__c</fullName>
        <description>Genesys Interaction Id</description>
        <externalId>true</externalId>
        <label>Genesys Interaction Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <label>Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hard SNE</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress (Assigned)</fullName>
                </value>
                <value>
                    <fullName>Qualified (Interested)</fullName>
                </value>
                <value>
                    <fullName>Closed/Lost - No Interest</fullName>
                </value>
                <value>
                    <fullName>Closed/Lost - No Descision / Activity</fullName>
                </value>
                <value>
                    <fullName>Closed/Lost - Bad Info</fullName>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Genesys_Interaction_Id__c</fullName>
        <description>Genesys Interaction Id</description>
        <externalId>true</externalId>
        <label>Genesys Interaction Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Sales_Task</fullName>
        <active>true</active>
        <label>Sales Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LogCallContactController_Ltng.cls
/*
Log a Call for Opps and Lead, Ltng version.
Created by Artyom M.
Per Story: B-25879

*/

public without sharing class LogCallContactController_Ltng {
	
	@AuraEnabled
	public static List<String> getReasonForContactValues() {
		List<String> options = new List<String>();
		Schema.DescribeFieldResult fieldResult = Task.Reason_For_Contact__c.getDescribe();
        List<Schema.PicklistEntry> pickListValues = fieldResult.getPicklistValues();
        options.add('--None--'); 
        /*
        for(Schema.PicklistEntry value : pickListValues) {
            options.add(value.getValue());
        }
        */
        options.add('Transfer');
        options.add('Other');
        return options;
	}
	
    @AuraEnabled
	public static List<String> getReasonForTransferValues() {
		List<String> options = new List<String>();
		Schema.DescribeFieldResult fieldResult = Task.Reason_For_Transfer__c.getDescribe();
        List<Schema.PicklistEntry> pickListValues = fieldResult.getPicklistValues();
        options.add('--None--');
        /*
        for(Schema.PicklistEntry value : pickListValues) {
            options.add(value.getValue());
        }
        */
        options.add('Transfer to CC');
        options.add('Transfer to Hybrid');
        options.add('Transfer to SET');
        options.add('Transfer to PRT');
        options.add('Transfer to N-Able');
        options.add('Transfer to LifePlan');
        return options;
	}
	
	@AuraEnabled
	public static String createTask(Id contactId, String reasonForContact, String reasonForTransfer, String otherReason, String description) {
		String lastError;
        Boolean cancellationError = false;
        Datetime startTime = system.now().addDays(-1);
        Datetime endTime = system.now();
        List<Task> theTasks = new List<Task>();
        Contact theContact;
        try {
           	theContact = [SELECT ID, Genesys_Interaction_Id__c  FROM Contact WHERE ID =: contactId LIMIT 1];
            system.debug(theContact.Genesys_Interaction_Id__c);
                    
			if(theContact.Genesys_Interaction_Id__c != null) {
				theTasks = [SELECT Id , Contact_Status__c , Lead_Status__c , Call_Type__C , Description , Inbound_Outbound__c FROM Task WHERE CallObject =: theContact.Genesys_Interaction_Id__c 
                                 AND (CreatedDate >=: startTime and CreatedDate <=: endTime) and createdById =: UserInfo.getUserId() and Subject != 'Case Activity' order by createdDate desc LIMIT 1];
			}
                      
			Task theQueriedTask;
            if(theTasks.size() != 0) {
            	theQueriedTask = theTasks[0];
            }

			system.debug(theQueriedTask);
            if(theQueriedTask != null) {
            	theQueriedTask.Status = 'Completed';
                theQueriedTask.ActivityDate = Date.today();
                theQueriedTask.WhoId = contactId;
                        
                //theTask.Reason_For_Contact__c = theTask.Reason_For_Contact_Cnt__c;
                //theTask.Reason_For_Transfer__c = theTask.Reason_For_Transfer_Cnt__c;
                        
                theQueriedTask.Reason_For_Contact__c = reasonForContact;
                        
                       

                theQueriedTask.RecordTypeId = LogCallContactControllerPilot.salesTaskRecordTypeId;
                        
				theQueriedTask.Description = description;
                        
                    	
                if (theQueriedTask.Reason_For_Contact__c == 'Transfer') {
					theQueriedTask.Other_Reason__c = null;
					theQueriedTask.Reason_For_Transfer__c = reasonForTransfer;
				}
				else
				if (theQueriedTask.Reason_For_Contact__c == 'Other') {
					theQueriedTask.Reason_For_Transfer__c = null;
					theQueriedTask.Other_Reason__c = otherReason;
				}
				else {
					theQueriedTask.Other_Reason__c = null;
					theQueriedTask.Reason_For_Transfer__c = null;
				}
                    	
                    	
                Update theQueriedTask;
                        

    
				return 'Activity Logged';

                        
			}
            else {
            	throw new AuraHandledException('Cannot Log activity at this time.');
			}
                

       
               
                       
                
		} 
        catch(System.Exception ex) {
			lastError = ex.getMessage();
            throw new AuraHandledException(lastError + ' ' + theTasks);
		}
        return null;
    }

    public static Id salesTaskRecordTypeId
    {
        get
        {
            if(salesTaskRecordTypeId == null)
            {
                List<RecordType> recordTypes = [SELECT Id , DeveloperName FROM RecordType WHERE sObjectType = 'Task' AND DeveloperName = 'Sales_Task'];
                if(!recordTypes.isEmpty())
                    salesTaskRecordTypeId = recordTypes[0].Id;
            }
            
            return salesTaskRecordTypeId;
        }
        set;
    }
    
}