src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No-VM</fullName>
                </value>
                <value>
                    <fullName>No-NM</fullName>
                </value>
                <value>
                    <fullName>No-Email</fullName>
                </value>
                <value>
                    <fullName>No-Final</fullName>
                </value>
                <value>
                    <fullName>Yes-SNE</fullName>
                </value>
                <value>
                    <fullName>Yes-Talk</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Commission Eligible</fullName>
                </value>
                <value>
                    <fullName>VM Attempt 1</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 2</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 3</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 4</fullName>
                </value>
                <value>
                    <fullName>VM Final Attempt</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Ineligible</fullName>
                </value>
                <value>
                    <fullName>Call Transferred</fullName>
                </value>
                <value>
                    <fullName>Service Unavailable</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inbound_Outbound__c</fullName>
        <label>Call Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VM Attempt 1</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 2</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 3</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 4</fullName>
                </value>
                <value>
                    <fullName>VM Final Attempt</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Commission Eligible</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Ineligible</fullName>
                </value>
                <value>
                    <fullName>Call Transferred</fullName>
                </value>
                <value>
                    <fullName>Service Unavailable</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Call_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Voicemail</fullName>
                </value>
                <value>
                    <fullName>No Message</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Spoke</fullName>
                </value>
                <value>
                    <fullName>VM Attempt 1</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 2</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 3</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 4</fullName>
                </value>
                <value>
                    <fullName>VM Final Attempt</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Commission Eligible</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Ineligible</fullName>
                </value>
                <value>
                    <fullName>Call Transferred</fullName>
                </value>
                <value>
                    <fullName>Service Unavailable</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact_State__c</fullName>
        <label>Contact State</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CampaignConstants.cls
public with sharing class CampaignConstants
{
   public final static String INTEGRATION_USER = 'Integration User';
   public final static String MAGIC_TIME = 'Magic Time';
   public final static String POST_PURCHASE = 'Post-Purchase';
   public final static String CUSTOMER_COMPLETE = 'Customer Complete';
   public final static String PRE_PURCHASE = 'Pre-Purchase';
   public final static String PRODUCT_LINE = 'Test ProductLine';
   public static final String SENT_TO_CUSTOMER = 'Sent To Customer';
   public static final String ABANDONER_DRIP = 'Abandoner/Drip';
   public static final String RA_OUTBOUND_UPSELL = 'RA Outbound Upsell';
   public static final String BIZ_LICENSE_OUTBOUND_UPSELL = 'Business License Outbound Upsell';
   public static final String TM_SEARCH_OUTBOUND_UPSELL = 'TM Search Outbound Upsell';
   public static final String SIX_MONTH_BIZ_CHECKUP = 'Six Month BIZ Checkup';
   public static final String MOBILE = 'Mobile';
   public final static String TMS = 'TMS';
   public final static String INBOUND = 'Inbound';
   public final static String TASK = 'Task';
   public final static String THE_ENTRY = 'Entry';
   public final static String THE_EXIT = 'Exit';
   public final static String THE_CONTACT = 'Contact';
   public final static String THE_LEAD = 'Lead';
   public final static String THE_ORDER = 'Order__c';
   public final static String THE_NAME = 'Name';
   public final static String THE_PHONE = 'Phone';
   public final static String HOME_PHONE = 'HomePhone';

   public final static String REGISTERED_AGENT = 'Registered Agent Service';
   public final static String BUSINESS_FORMATIONS = 'Business Formations';
   public final static String CONTACT_STATE = 'Contact_State__c';
   public final static String AWAITING_SIGNATURE = 'Awaiting Signature';
   public final static String BUSINESS_LICENSES = 'Business Licenses';
   public final static String THE_PROCESS = 'Process';
   public final static String TM_SEARCH = 'TM Search';
   public final static String TRADEMARK_GOLD = 'Trademark Gold package';
   public final static String FIRST_BASE_PRODUCT = 'First Base Product';
   public final static String SECOND_BASE_PRODUCT = 'Second Base Product';
   public final static String THIRD_BASE_PRODUCT = 'Third Base Product';
   public final static String BOA = 'Bank Of America';
   public final static String REMOVED = 'Removed';
   public final static String MEMBER_SINCE = 'Member Since';
   public final static String LEAD_CONTACT_MODIFIED = 'Lead/Contact Modified';
   public final static String LEAD_SOURCE = 'LeadSource';
   public final static String CONTACT_STATUS = 'Contact_Status__c';
   public final static String LEAD_CONTACT_STATUS = 'Lead_Call_Status__c';
   public final static String CAMPAIGN = 'Campaign__c';
   public final static String ORDER_PLACED = 'Order Placed';
   public final static String ADDED = 'Added';
   public final static String SALES_ACTIVITY = 'Sales Activity';
   public final static String VM_FINAL = 'VM Final Attempt';
   public final static String SENT = 'Sent';
   public final static String INBOUND_OUTBOUND = 'Inbound_Outbound__c';
   public final static String LIVING_TRUST = 'Living Trust';
   public final static String EP_UPSELL_CAMPAIGN = 'EP Upsell Campaign';

}