src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No-VM</fullName>
                </value>
                <value>
                    <fullName>No-NM</fullName>
                </value>
                <value>
                    <fullName>No-Email</fullName>
                </value>
                <value>
                    <fullName>No-Final</fullName>
                </value>
                <value>
                    <fullName>Yes-SNE</fullName>
                </value>
                <value>
                    <fullName>Yes-Talk</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Commission Eligible</fullName>
                </value>
                <value>
                    <fullName>VM Attempt 1</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 2</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 3</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 4</fullName>
                </value>
                <value>
                    <fullName>VM Final Attempt</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Ineligible</fullName>
                </value>
                <value>
                    <fullName>Call Transferred</fullName>
                </value>
                <value>
                    <fullName>Service Unavailable</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <label>Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress (Assigned)</fullName>
                </value>
                <value>
                    <fullName>Qualified (Interested)</fullName>
                </value>
                <value>
                    <fullName>Closed Lost - No Interest</fullName>
                </value>
                <value>
                    <fullName>Closed/Lost - No Activity</fullName>
                </value>
                <value>
                    <fullName>Closed/Lost - Bad Info</fullName>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                </value>
                <value>
                    <fullName>VM - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Unable to Contact/Bad Number/NM</fullName>
                </value>
                <value>
                    <fullName>Already Purchased</fullName>
                </value>
                <value>
                    <fullName>Response/Research Pending</fullName>
                </value>
                <value>
                    <fullName>Do Not Call</fullName>
                </value>
                <value>
                    <fullName>NM - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>NM - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>VM - Final Attempt</fullName>
                </value>
                <value>
                    <fullName>Transaction Complete</fullName>
                </value>
                <value>
                    <fullName>Soft SNE</fullName>
                </value>
                <value>
                    <fullName>Hard SNE</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VM Attempt 1</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 2</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 3</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 4</fullName>
                </value>
                <value>
                    <fullName>VM Final Attempt</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Commission Eligible</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Ineligible</fullName>
                </value>
                <value>
                    <fullName>Call Transferred</fullName>
                </value>
                <value>
                    <fullName>Service Unavailable</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Genesys_Interaction_Id__c</fullName>
        <description>Genesys Interaction Id</description>
        <externalId>true</externalId>
        <label>Genesys Interaction Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order360__c.object
<CustomObject>
    <fields>
        <fullName>LZ_Order_Item_Id__c</fullName>
        <externalId>true</externalId>
        <label>LZ Order Item Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipName>Order360</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Order360</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_cancellation__c</fullName>
        <label>Reason for cancellation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unaware of service</fullName>
                </value>
                <value>
                    <fullName>(Free Trial) Used service during Free Trial and is no longer needed</fullName>
                </value>
                <value>
                    <fullName>Did not understand service value</fullName>
                </value>
                <value>
                    <fullName>(Paid) No longer needed</fullName>
                </value>
                <value>
                    <fullName>Price too expensive</fullName>
                </value>
                <value>
                    <fullName>Previously retained but still wants to cancel</fullName>
                </value>
                <value>
                    <fullName>Already has an Attorney</fullName>
                </value>
                <value>
                    <fullName>Poor Consultation with an Attorney</fullName>
                </value>
                <value>
                    <fullName>Attorney referred customer elsewhere</fullName>
                </value>
                <value>
                    <fullName>Has not started business</fullName>
                </value>
                <value>
                    <fullName>Business has closed</fullName>
                </value>
                <value>
                    <fullName>Upset and unwilling to listen</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Order Saved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Active Revenue</label>
    <nameField>
        <displayFormat>Ord360-{0000}</displayFormat>
        <label>Order360 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Active Revenue</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Show process name of the base product on the order</description>
        <formula>Base_Product__r.Process__r.Name</formula>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>LZ_Order_Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>LZ Order Item ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship field to the parent record within Order Item object.</description>
        <label>Parent</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Cancellation_Date__c</fullName>
        <label>Subscription Cancellation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <label>Subscription End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <label>Subscription Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Active Won&apos;t Renew</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Not Yet Started</fullName>
                </value>
                <value>
                    <fullName>Payment Due</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order_Matching_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Order Matching Activities</relationshipLabel>
        <relationshipName>Order_Matching_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>OrderLeadOpportunitys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Matching Activity</label>
    <nameField>
        <displayFormat>Match-{0000}</displayFormat>
        <label>Order Matching Activity  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Matching Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SubscriptionSaveController_Ltng.cls
/*
Subscription Save application.
Created by Artyom M.
Per Story: B-24904
*/


public without sharing class SubscriptionSaveController {
    private final static List<String> activeSubscriptionStatuses = new List<String>{'Active','Active Won\'t Renew','Pending'};
    
    
    @AuraEnabled
    public static List<SubscriptionItemWrapper> getRelatetOrderItems(Id contactId) {
        List<SubscriptionItemWrapper> subscriptionItems = new List<SubscriptionItemWrapper>();
    	List<Order_Item__c> orderItemListToreturn = new List<Order_Item__c>();
    	List<Order__c> allOrders = [SELECT Id , Name,  (Select Id, Name, Product__r.Name , Subscription_Cancellation_Date__c , Subscription_Start_Date__c , 
                                                    LZ_Order_Item_ID__c , Order__c, Subscription_Status__c , Subscription_End_Date__c FROM Order_Items__r WHERE Subscription_Status__c IN :activeSubscriptionStatuses order by Subscription_Status__c asc) FROM Order__c WHERE Contact__c = :contactId];
		for(Order__c theOrder : allOrders) {
			for(Order_Item__c theItem : theOrder.Order_Items__r) {
				if(theItem.Subscription_Status__c != null) {
					//orderItemListToreturn.add(theItem);
					subscriptionItems.add(new SubscriptionItemWrapper(theItem.Subscription_Start_Date__c , theItem.Subscription_End_Date__c , theOrder.Name , theItem.Subscription_Status__c , theItem.Product__r.Name, theItem.Order__c , theItem.LZ_Order_Item_ID__c , theItem.Id ));
				}
        	}
        }
        System.debug('orderItemListToreturn' + subscriptionItems.size());
        for (SubscriptionItemWrapper s : subscriptionItems) {
            System.debug('Prod Name : ' + s.productName);
        }
		return subscriptionItems;
    }
    
    
    public class SubscriptionItemWrapper {
        @AuraEnabled public Boolean isSelected{get;set;}
        @AuraEnabled public String subscriptionStartDate{get;set;}
        @AuraEnabled public String subscriptionEndDate{get;set;}
        @AuraEnabled public String parentOrderNumber{get;set;}
        @AuraEnabled public String susbcriptionStatus{get;set;}
        @AuraEnabled public String productName{get;set;}
        @AuraEnabled public Id orderId{get;set;}
        @AuraEnabled public String lzOrderItemId{get;set;}
        @AuraEnabled public Id itemId{get;set;}
        @AuraEnabled public String cancellationReason{get; set;}
        
        public SubscriptionItemWrapper(DateTime theSubscriptionStartDate , DateTime theSubscriptionEndDate , String theParentOrderNumber , String theSusbcriptionStatus , String theProductName , Id theOrderId , String theLZOrderItemId , Id theItemId)
        {
            if(theSubscriptionStartDate != null)
            {
                subscriptionStartDate = (Date.newInstance(theSubscriptionStartDate.year() , theSubscriptionStartDate.month() , theSubscriptionStartDate.day())).format();
            }
            if(theSubscriptionEndDate!= null)
            {
                subscriptionEndDate = (Date.newInstance(theSubscriptionEndDate.year() , theSubscriptionEndDate.month() , theSubscriptionEndDate.day())).format();
            }
            parentOrderNumber = theParentOrderNumber;
            susbcriptionStatus = theSusbcriptionStatus;
            productName = theProductName;
            isSelected = false;
            orderId = theOrderId;
            lzOrderItemId = theLZOrderItemId;
            itemId = theItemId;
            
        } 
    }
    @AuraEnabled
    public static List<String> getCancellationReasons() {
        List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult = Order360__c.Reason_for_cancellation__c.getDescribe();
        List<Schema.PicklistEntry> pickListValues = fieldResult.getPicklistValues();
        options.add('--None--'); 
        for( Schema.PicklistEntry value : pickListValues) {
        	options.add(value.getValue());
        }
        
        return options;
    }
    
    @AuraEnabled
    public static void doSubmit(Id contactId, String selected) {
    	
    	List<SubscriptionItemWrapper> listToSave = (List<SubscriptionItemWrapper>)JSON.deserialize(selected, List<SubscriptionItemWrapper>.class);
    	
    	
    	System.debug('submit: ' + contactId);
    	//selectedSubscriptions = selected;
    	//System.debug('selectedSubscriptions' + selectedSubscriptions.size());
    	Contact theContact = new Contact();
    	List<Task> theTasks = new List<Task>();
        Datetime startTime = system.now().addDays(-1);
		Datetime endTime = system.now();
    	try {
    		theContact = [SELECT ID, Genesys_Interaction_Id__c  FROM Contact WHERE ID =: contactId LIMIT 1];
    		System.debug('theContact: ' + theContact);
    	}
    	catch (QueryException e) {
    		System.debug('QueryException: ' + e.getMessage());
    	}

        System.debug('found contact');
        
        if(theContact != null && theContact.Genesys_Interaction_Id__c != null) {
        	try {
        		System.debug('Searching for task');
        		theTasks = [SELECT Id , Contact_Status__c , Lead_Status__c , Call_Type__C , Description , Inbound_Outbound__c FROM Task WHERE CallObject =: theContact.Genesys_Interaction_Id__c 
                                 AND (CreatedDate >=: startTime and CreatedDate <=: endTime) and createdById =: UserInfo.getUserId() and Subject != 'Case Activity' order by createdDate desc LIMIT 1];
        	}
        	catch (QueryException e) {
    			System.debug('QueryException: ' + e.getMessage());
    		}
        	
		System.debug('is there task?: ' + theTasks.size());	            
        }
        if (!theTasks.isEmpty()) {
        	System.debug('found task');
        	Task theQueriedTask = theTasks[0];
        	theQueriedTask.Status = 'Completed';
			theQueriedTask.ActivityDate = Date.today();
			theQueriedTask.Commission_Eligible__c = true;
			theQueriedTask.Contact_Status__c = 'Contacted/Spoke - Commission Eligible';
			theQueriedTask.Is_Subscription_Activity__c  = true;
			try {
				Update theQueriedTask;
			}
			catch (QueryException e) {
				System.debug('QueryException: ' + e.getMessage());
			}
			
			
			theContact.Contact_Status__c = theQueriedTask.Contact_Status__c;
			theContact.ownerId  = UserInfo.getUserId();
            
            try {
				update theContact;
			}
			catch (QueryException e) {
				System.debug('QueryException: ' + e.getMessage());
			}
            
			
			createOrder360Records(theQueriedTask, listToSave);
   
        }
        
        
    	
    }
    
    
    @AuraEnabled
    public static Boolean checkForCall(Id contactId) {
    	Contact theContact = new Contact();
    	List<Task> theTasks = new List<Task>();
        Datetime startTime = system.now().addDays(-1);
		Datetime endTime = system.now();
    	try {
    		theContact = [SELECT ID,Genesys_Interaction_Id__c  FROM Contact WHERE ID =: contactId LIMIT 1];
    	}
    	catch (QueryException e) {
    		
    	}

        
        if(theContact != null && theContact.Genesys_Interaction_Id__c != null) {
        	try {
        		theTasks = [SELECT Id , Contact_Status__c , Lead_Status__c , Call_Type__C , Description , Inbound_Outbound__c FROM Task WHERE CallObject =: theContact.Genesys_Interaction_Id__c 
                                 AND (CreatedDate >=: startTime and CreatedDate <=: endTime) and createdById =: UserInfo.getUserId() and Subject != 'Case Activity' order by createdDate desc LIMIT 1];
        	}
        	catch (QueryException e) {
    			
    		}
        	
			            
        }
        System.debug('checkForCall is ' + theTasks.isEmpty());
        if (theTasks.isEmpty()) {
        	return false;    
        }
        else {
            return true;
        }
        
        
        
    }
    @AuraEnabled
    public static void createOrder360Records(Task taskToUse, List<SubscriptionItemWrapper> selected) {
    	List<SubscriptionItemWrapper> selectedSubscriptions = new List<SubscriptionItemWrapper>();
    	selectedSubscriptions = selected;
    	System.debug('createOrder360Records');
    	System.debug('taskToUse.Id + ' + taskToUse.Id);
    	List<Order_Matching_Activity__c> oMAs = new List<Order_Matching_Activity__c>();
    	try {
    		oMAs = [SELECT Id FROM Order_Matching_Activity__c WHERE Activity_SFDC_Id__c = :taskToUse.Id];
    	}
    	catch(QueryException e) {
    		System.debug('QueryException: ' + e.getMessage());
    	}
        System.debug('oMAs = ' + oMAs.size());
        List<Order360__c> order360ToCreate = new List<Order360__c>();
        
        if (!oMAs.isEmpty()) {
        	System.debug('starting OMA');
        	System.debug('selectedSubscriptions size: ' + selectedSubscriptions.size());
        	System.debug('selectedSubscriptions first: ' + selectedSubscriptions[0]);
        	
        	for(Order_Matching_Activity__c matchingActivity : oMAs) {
        		System.debug('First loop');
	            for(SubscriptionSaveController.SubscriptionItemWrapper theItemWrapper : selectedSubscriptions) { 
	            	System.debug('creating 360');
	                order360ToCreate.add(new Order360__c(LZ_Order_Item_Id__c = theItemWrapper.lzOrderItemId, 
	                                                     Parent_Order_Item__c = theItemWrapper.itemId, 
	                                                     Order_Matching_Activity__c = matchingActivity.Id, 
	                                                     Order__c = theItemWrapper.orderId,
	                                                     Reason_for_cancellation__c = theItemWrapper.cancellationReason));
	            }
	        }
        
        }
      
        
      System.debug('order360ToCreate = ' + order360ToCreate.size());
       if(!order360ToCreate.isEmpty())
            insert order360ToCreate;
    }
    
}