src/objects/Authorized_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Authorized Orders / Customer Login</relationshipLabel>
        <relationshipName>Authorized_Customer_Login_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Authorized Contact</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorized Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>FkUser__c</fullName>
        <externalId>true</externalId>
        <label>FkUser</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Time_TOS_Accepted__c</fullName>
        <description>The datetime when Terms of Services (TOS) is accepted by the customer</description>
        <label>Date/Time TOS Accepted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OrderID__c</fullName>
        <externalId>true</externalId>
        <label>OrderID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order_Date_Time_Created__c</fullName>
        <description>Store the created date time of the order created in LZ Data</description>
        <label>Order Date/Time Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TOS_Accepted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if Terms of Services (TOS) is accepted by the customer</description>
        <label>TOS Accepted</label>
        <type>Checkbox</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/RelatedOrdersController_ltng.cls
public class RelatedOrdersController_ltng {
     
    @AuraEnabled public String orderNumber{get;set;}    
    
    @AuraEnabled public Order__c thisOrder {get;set;}
    @AuraEnabled public static RelatedOrdersService_ltng  relatedService{get;set;}
    
    @AuraEnabled public List<Authorized_Contact__c> authorizedContacts{get;set;}
    @AuraEnabled public  String customerId{get;set;}     
    
   
    
    @AuraEnabled public static  RelatedOrdersController_ltng ctrl {get; set;}
    
     
    public static void init(String orderRecordId)
    {
         ctrl = new RelatedOrdersController_ltng();
               
        if(String.isNotBlank(orderRecordId))
        {
            ctrl.thisOrder = [SELECT Id , Name , OrderID__c , Contact__r.FkUser__c,Language_Preferance__c, Order_Date_Time_Created__c, Date_Time_TOS_Accepted__c, TOS_Accepted__c, OrderTerms__c, CreatedBy.Name, LastModifiedBy.Name FROM Order__c WHERE Id = :orderRecordId limit 1][0];
            ctrl.orderNumber = ctrl.thisOrder.Name;
            ctrl.customerId = ctrl.thisOrder.Contact__r.FkUser__c;
            
            
        }
       
        
    }
    
    @AuraEnabled
    public static RelatedOrdersService_ltng getOrderByOrderId(String orderRecordId) 
    {   
        system.debug('orderRecordId: '+orderRecordId);
        
        relatedservice  = new RelatedOrdersService_ltng();
             
        init(orderRecordId);
        relatedservice.customerid=ctrl.customerId;
        
        try
        {   
            IADServiceBase_ltng.initWrapper(RelatedOrdersService_ltng.GETORDERBYORDERID);
            RelatedOrdersService_ltng.getOrderByOrderId(ctrl.orderNumber);            
        }
        catch(Exception theException)
        {
            system.debug('exception thrown in startRequestsInParallel');
            IADServiceBase_ltng.populateErrorMessage(theException);
            RelatedOrdersService_ltng.iadServiceMessages = IADServiceBase_ltng.iadMessages;
        }
        
       
        return relatedservice;        
    }
    
@AuraEnabled
    public static RelatedOrdersService_ltng getRelatedOrders(String ordergroupid) 
    {   
        
        
        relatedservice  = new RelatedOrdersService_ltng();
        
       
        
        try
        {   
            IADServiceBase_ltng.initWrapper(RelatedOrdersService_ltng.GETRELATEDORDERSBYORDERID);
          RelatedOrdersService_ltng.getRelatedOrders(ordergroupid);            
        }
        catch(Exception theException)
        {
            system.debug('exception thrown in startRequestsInParallel');
            IADServiceBase_ltng.populateErrorMessage(theException);
            RelatedOrdersService_ltng.iadServiceMessages = IADServiceBase_ltng.iadMessages;
        }
        
       
        return relatedservice;        
    }
    
}