src/objects/Campaign_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Across_Orders__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Across Orders</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Base_Process__c</fullName>
        <description>Comma Separated Process Name</description>
        <label>Base Process</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Base_Product_Line__c</fullName>
        <label>Base Product Line</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Intellectual Property</fullName>
                </value>
                <value>
                    <fullName>Personal Services</fullName>
                </value>
                <value>
                    <fullName>Attorney Services</fullName>
                </value>
                <value>
                    <fullName>Business Formations</fullName>
                </value>
                <value>
                    <fullName>Legal Forms</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Base_Product_Name__c</fullName>
        <description>Comma separated Base Product Name</description>
        <label>Base Product Name</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Rules</relationshipLabel>
        <relationshipName>Campaign_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Child_Product_Name__c</fullName>
        <description>Comma separated Child Product Name</description>
        <label>Child Product Name</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Entry_Exit__c</fullName>
        <label>Entry/Exit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Entry</fullName>
                </value>
                <value>
                    <fullName>Exit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field_To_Evaluate__c</fullName>
        <label>Field To Evaluate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Value__c</fullName>
        <label>Field Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Has_Purchased__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Purchased</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Days__c</fullName>
        <label>Number of Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Order__c</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rule_Id__c</fullName>
        <label>Rule Id</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Campaign Rule</label>
    <nameField>
        <displayFormat>Rule-{0000}</displayFormat>
        <label>Campaign Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Base_Product_Name__c</fullName>
        <formula>Base_Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Base Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processing_Status_Date_Time__c</fullName>
        <formula>User_Order_Extension__r.Processing_Status_Date_Time__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Processing Status Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <formula>User_Order_Extension__r.Processing_Status__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Processing Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Order Extension</label>
        <referenceTo>User_Order_Extension__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Order_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Order Extension</label>
        <referenceTo>User_Order_Extension__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Processing_Status__c.object
<CustomObject>
    <label>Processing Status</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processing Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_Order_Extension__c.object
<CustomObject>
    <fields>
        <fullName>Processing_Status_Date_Time__c</fullName>
        <label>Processing Status Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Processing Status</label>
        <referenceTo>Processing_Status__c</referenceTo>
        <relationshipName>User_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Order Extension</label>
    <nameField>
        <displayFormat>UOE-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Order Extensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CampaignEngineTest.cls
@isTest
public class CampaignEngineTest  
{
    static List<Account> testAccounts;
    static List<Contact> testContacts;
    static List<Order__c> testOrders;
    static List<Order_Item__c> testOrderItems;
    static User_Order_Extension__c firstUserOrderExtension;
    static User_Order_Extension__c secondUserOrderExtension;
  
    final static String TEST_ACCOUNT = 'Test Account';
    final static String TEST_CONTACT = 'Test Contact';
    final static Integer SIZE = 200; 

    static void setupData()
    {
        testContacts = new List<Contact>();
        testOrderItems = new List<Order_Item__c>();
        testAccounts = TestUtils.createAccounts(SIZE , TEST_ACCOUNT , false);
        insert testAccounts;

        for(Account theAccount : testAccounts)
        {
            Contact theContact = TestUtils.createContacts(1 , TEST_CONTACT , theAccount.Id , false)[0];
            testContacts.add(theContact);
        }
    

        firstUserOrderExtension = new User_Order_Extension__c();
        firstUserOrderExtension.Processing_Status__c = CampaignRulesSetup.sentToCustomerProcessingStatus.Id;
        firstUserOrderExtension.Processing_Status_Date_Time__c = Date.today().addDays(-16);
        insert firstUserOrderExtension;

        secondUserOrderExtension = new User_Order_Extension__c();
        secondUserOrderExtension.Processing_Status__c = CampaignRulesSetup.sentToCustomerProcessingStatus.Id;
        secondUserOrderExtension.Processing_Status_Date_Time__c = Date.today().addDays(-190);
        insert secondUserOrderExtension;

    }

    
    static testMethod void testAssignCampaignForOrders()
    {
        CampaignRulesSetup.setupCampaignWithRules();
        setupData();
        insert testContacts;
        testOrders = new List<Order__c>();
        for(Integer i = 0 ; i<SIZE/2 ; ++i)
        {
            Order__c theOrder = TestUtils.createOrders(1 , CampaignRulesSetup.testProducts[0].Id , false)[0]; //Product Line of Business Formation
            theOrder.User_Order_Extension__c = firstUserOrderExtension.Id; //2 Weeks since Order status sent to Customer
            theOrder.Contact__c = testContacts[i].Id;
            testOrders.add(theOrder);   
        }
        for(Integer i = SIZE/2 ; i<SIZE ; ++i)
        {
            Order__c theOrder = TestUtils.createOrders(1 , CampaignRulesSetup.testProducts[1].Id , false)[0]; // Trademark Search
            theOrder.Contact__c = testContacts[i].Id;
            theOrder.User_Order_Extension__c = firstUserOrderExtension.Id; //2 Weeks since Order status sent to Customer
            testOrders.add(theOrder);   
        }
        insert testOrders;

        List<CampaignMember> campaignMembers;
        Set<String> campaignNames = new Set<String>();
        campaignNames.add(CampaignConstants.BIZ_LICENSE_OUTBOUND_UPSELL);
        campaignNames.add(CampaignConstants.TM_SEARCH_OUTBOUND_UPSELL);
        
        Test.startTest();
            CampaignEngine theEngine = new CampaignEngine();
            campaignMembers = theEngine.assignCampaignsForOrders(testOrders , campaignNames);
        Test.stopTest();
        System.assertEquals(SIZE, campaignMembers.size() , SIZE+ ' Campaign Members should have been returned');

    }
    
  
    
    
    static testMethod void testAssignCampaignForLeads()
    {
        CampaignRulesSetup.setupCampaignWithRules();
        List<Lead> newLeads = TestUtils.createLeads(SIZE ,  'Test LastName' , false);
        for(Integer i = 0; i <SIZE/2 ; ++i)
        {
            newLeads[i].Phone = '555555555'+String.ValueOf(i);
        }
        DuplicateChecker.NoDuplicateCheck = true;
        insert newLeads;

        Test.startTest();
            LeadService.processForCampaigns(newLeads);
        Test.stopTest();
        List<CampaignMember> campaignMembers = [SELECT id , Status FROM CampaignMember];
        System.assertEquals(SIZE/2 , campaignMembers.size() , SIZE/2+' Campaign Members should have been returned');

    }
    
    
    static testMethod void testAssignCampaignForContacts()
    {
        CampaignRulesSetup.setupCampaignWithRules();
        setupData();
        
        for(Integer i = 0 ; i < SIZE/2 ; ++i)
        {
            testContacts[i].HomePhone = '5555555555';
        }
        insert testContacts;

        Test.startTest();
            ContactService.processForCampaignsEntry(testContacts);
        Test.stopTest();
        List<CampaignMember> campaignMembers = [SELECT Id , Status FROM CampaignMember];
        System.assertEquals(SIZE/2 , campaignMembers.size() , SIZE/2+' Campaign Members should have been returned');

    }
    
    

    
    
    static testMethod void testExitCampaignForContact()
    {
        
        CampaignRulesSetup.setupCampaignWithRules();
        setupData();
        insert testContacts;
        List<CampaignMember> campaignMembers = new List<CampaignMember>();
        for(Integer i = 0; i <SIZE ; ++i)
        {
            CampaignMember theMember = new CampaignMember();
            theMember.ContactId = testContacts[i].Id;
            theMember.CampaignId = CampaignRulesSetup.abandonerCampaign.Id;
            campaignMembers.add(theMember);
        }
        insert campaignMembers;
        
        testOrders = new List<Order__c>();
        for(Integer i = 0 ; i<SIZE/2 ; ++i)
        {
            Order__c theOrder = TestUtils.createOrders(1 , CampaignRulesSetup.testProducts[0].Id , false)[0]; //Product Line of Business Formation
            theOrder.Contact__c = testContacts[i].Id;
            testOrders.add(theOrder);   
        }
                
        Test.startTest();
            insert testOrders;
        Test.stopTest();
        List<CampaignMember> returnedCampaignmembers = [SELECT Id , Status FROM CampaignMember WHERE Status = :CampaignConstants.ORDER_PLACED];
        System.assertEquals(SIZE/2 , returnedCampaignMembers.size() , SIZE/2 + ' Campaign Members should have been returned');
        
    }
    
    
    static testMethod void testAssignCampaignForContactsWithExistingContactInCampaign()
    {
        CampaignRulesSetup.setupCampaignWithRules();
        setupData();
        for(Contact theContact : testContacts)
        {
            theContact.HomePhone = '5555555555';
        }
        insert testContacts;
    
        List<Contact> sameContactsForCampaigns = new List<Contact>();
        for(Integer  i = 0 ; i<SIZE/2; ++i)
        {
            testContacts[i].HomePhone = '5555555555';
            sameContactsForCampaigns.add(testContacts[i]);
        }
        Set<String> campaignNames = new Set<String>();
        campaignNames.add(CampaignConstants.ABANDONER_DRIP);
        
        List<CampaignMember> returnedCampaignMembers;
        Test.startTest();
            CampaignEngine theEngine = new CampaignEngine();
            returnedCampaignMembers = theEngine.assignCampaignsForContact(sameContactsForCampaigns , campaignNames);
        Test.stopTest();
        System.assertEquals(SIZE/2 , returnedCampaignMembers.size() , SIZE/2 + ' Campaign Members should have been returned');

    }
    
    
    static testMethod void testAssignCampaignForLeadsWithExistingLeadInCampaign()
    {
        CampaignRulesSetup.setupCampaignWithRules();
        List<Lead> newLeads = TestUtils.createLeads(SIZE ,  'Test LastName' , false);
        integer count = 0;
        for(Lead theLead : newLeads)
        {
            theLead.Phone = '555555555'+String.ValueOf(count);
            count++;
        }
        DuplicateChecker.NoDuplicateCheck = true;
        insert newLeads;

        LeadService.processForCampaigns(newLeads);


        List<CampaignMember> campaignMembers = new List<CampaignMember>();
        Set<String> campaignNames = new Set<String>();
        campaignNames.add(CampaignConstants.ABANDONER_DRIP);

        List<Lead> sameLeadsForCampaigns = new List<Lead>();
        for(Integer  i = 0 ; i<SIZE/2; ++i)
        {
            sameLeadsForCampaigns.add(newLeads[i]);
        }


        List<CampaignMember> returnedCampaignMembers;
        Test.startTest();
            CampaignEngine theEngine = new CampaignEngine();
            returnedCampaignMembers = theEngine.assignCampaignsForLead(sameLeadsForCampaigns , campaignNames);
        Test.stopTest();
        System.assertEquals(SIZE/2 , returnedCampaignMembers.size() , SIZE/2 + ' Campaign Members should have been returned');

    }
    
    static testMethod void testEvaluateLead()
    {
        CampaignRulesSetup.setupCampaignWithRules();
        Lead testLead = TestUtils.createLeads(1 , 'Test Lead', false)[0];
        testLead.Phone = '5555555555';
        insert testLead;

        Lead queriedLead = [SELECT Id , Name , Phone FROM Lead limit 1];
        List<Campaign_Rule__c> theRulesForCampaign = [SELECT Id , Rule_Id__c, Field_To_Evaluate__c , Field_Value__c , Base_Product_Line__c , Base_Process__c,
                                      Child_Product_Name__c , RecordType.DeveloperName  , Has_Purchased__c , Base_Product_Name__c , Number_of_Days__c , 
                                      Status__c , Object__c , Across_Orders__c FROM Campaign_Rule__c  WHERE Entry_Exit__c = :CampaignConstants.THE_ENTRY AND Campaign__c = :CampaignRulesSetup.abandonerCampaign.Id 
                                      ORDER BY Rule_Id__c ASC];
        String postfixExpression = '12&34&|';

        Boolean theResult;
        Test.startTest();
            CampaignEngine theEngine = new CampaignEngine();
            theResult = theEngine.evaluateLead(queriedLead,CampaignRulesSetup.abandonerCampaign, theRulesForCampaign, postfixExpression, null , null);
        Test.stopTest();

        System.assert(theResult , 'Result must have been true');                             
    }
    
    
}