src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-Purchase</fullName>
                </value>
                <value>
                    <fullName>Magic Time</fullName>
                </value>
                <value>
                    <fullName>Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Customer Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postfix_Expression_Exit__c</fullName>
        <label>Postfix Expression Exit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Campaign_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Rules</relationshipLabel>
        <relationshipName>Campaign_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entry_Exit__c</fullName>
        <label>Entry/Exit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Entry</fullName>
                </value>
                <value>
                    <fullName>Exit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Days__c</fullName>
        <label>Number of Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rule_Id__c</fullName>
        <label>Rule Id</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Campaign Rule</label>
    <nameField>
        <displayFormat>Rule-{0000}</displayFormat>
        <label>Campaign Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Rules</pluralLabel>
    <recordTypes>
        <fullName>Days_Rule</fullName>
        <active>true</active>
        <label>Days Rule</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>DateTime_Added_to_Campaign__c</fullName>
        <label>DateTime Added to Campaign</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

src/classes/AbandonerCampaignMemberBatch.cls
global class AbandonerCampaignMemberBatch implements Database.Batchable<sObject> ,  Database.Stateful{
    
    //Batch job to remove abandoner campaign member
    String query;
    Set<String> campaignNames = new Set<String>();
    //only for Post-Purchase
    DateTime theDateTime;
    global AbandonerCampaignMemberBatch()
    {
            
        Decimal numberOfDays; 
        for(Campaign theCampaign : [SELECT Id , Name , (SELECT Id , Rule_Id__c, Number_of_Days__c , RecordType.DeveloperName  FROM Campaign_Rules__r  WHERE Entry_Exit__c = 'Exit' 
                                        AND RecordType.DeveloperName = 'Days_Rule' limit 1) FROM Campaign  WHERE Category__c = :CampaignConstants.PRE_PURCHASE])
        {
                
            campaignNames.add(theCampaign.Name);
            if(!theCampaign.Campaign_Rules__r.isEmpty())
            {
                    numberOfDays = theCampaign.Campaign_Rules__r[0].Number_of_Days__c;
                
            }
        }
        theDateTime = Datetime.now().addDays(numberOfDays.intValue()*(-1));
        if(theDateTime != null)
            query = 'SELECT Id  , LeadId , Status , DateTime_Added_to_Campaign__c FROM CampaignMember WHERE Campaign.Category__c = \'+CampaignConstants.PRE_PURCHASE+\' AND Campaign.Postfix_Expression_Exit__c != null AND Status = \'Sent\' AND CreatedDate <= :theDateTime';
    
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope)
    {
        processCampaigns(scope);
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
    
    global void processCampaigns(List<CampaignMember> campaignMembers)
    {
        
        for(CampaignMember theMember : campaignMembers)
        {
            theMember.Status = 'Removed';
        }
        upsert campaignMembers;
    }
}