src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processing_Number__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <label>User Order ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State_of_Formation__c</fullName>
        <label>State of Formation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <description>matching the fkUserOrder field of OrderItem table in lzdata</description>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IADContactCaseHistoryPanelControllerTest.cls
@isTest
public class IADContactCaseHistoryPanelControllerTest {

  static testmethod void IADContactCaseHistoryPanelControllerTest()
  {
    //insert Account
    Account newAccount = TestUtils.createAccounts(1 , 'the Account' , true)[0];

    //insert contact
    Contact newContact = TestUtils.createContacts(1 , 'the Contact' , newAccount.Id , false)[0];
    newContact.Email = 'lztest@lzTestClass.com';
    insert newContact;
    List<Order__c> testOrders = TestUtils.createOrders(5 , null , true);
    List<Order_Item__c> orderItems = new List<Order_Item__c>();
    for(Order__c theOrder : testOrders)
    {
        theOrder.State_Of_Formation__c = 'CA';
        orderItems.add(TestUtils.createOrderItems(1 , theOrder.Id , false)[0]);
    }
    update testOrders;
    
    Integer i = 1;
    for(Order_Item__c theItem : orderItems)
    {
        theItem.User_Order_ID__c = i+'';
    }
    insert orderItems;    

    List<Case> newCases = TestUtils.createCases(5,false);
    i = 1;
    for(Case theCase : newCases)
    {
        theCase.ContactId = newContact.ID;
        theCase.Processing_Number__c = i+'';
        ++i;
        system.debug(theCase);
    }
    insert newCases;

    Test.startTest();

        PageReference pageRef = Page.IADContactCaseHistoryPanelPage;
        pageRef.getParameters().put('id', String.valueOf(newContact.Id));
        Test.setCurrentPage(pageRef);
        IADContactCaseHistoryPanelController thecontroller = new IADContactCaseHistoryPanelController();
      
        
        System.assertEquals(newCases.size(), (thecontroller.allCases).size(), 'Right number of cases should have been displayed');
    Test.stopTest();  
  } 
}