src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order_Number__c</fullName>
        <description>Order Manager number. Cloud Trigger coded this field to open a new window and look up the order in order manager.</description>
        <externalId>true</externalId>
        <label>Order Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processing_Number__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <label>User Order ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>OrderID__c</fullName>
        <externalId>true</externalId>
        <label>OrderID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <description>matching the fkUserOrder field of OrderItem table in lzdata</description>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SEAD_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Lead_Days_from_Ownership__c</fullName>
        <description>Days from Lead or Opp&apos;s first ownership, part of the exit criteria</description>
        <label>Lead Days from Ownership</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_New_Stage_Activity_Limit__c</fullName>
        <label>Lead New Stage Activity Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_Qualified_Stage_Activity_Limit__c</fullName>
        <label>Lead Qualified Stage Activity Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_Validated_Stage_Activity_Minimum__c</fullName>
        <label>Lead Validated Stage Activity Minimum</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SEAD Configuration</label>
</CustomObject>

src/classes/NextPadControllerTest.cls
@isTest
public class NextPadControllerTest
{
    
    static Order__c testOrder;
    static Order_Item__c testOrderItem;
    static Contact testContact;
    static Account testAccount;
    static List<Case> testCases;
    static List<Task> noteTasks;
    static List<CaseComment> caseComments; 
    final static Integer SIZE_ONE = 1;
    final static Integer SIZE_THREE = 3;
    final static String TEST_ACCOUNT = 'Test Account';
    final static String TEST_CONTACT = 'Test Contact';
    final static String ORDER_NUMBER = '3456789';
    final static String USER_ORDER_ID = '54321675';
    final static String DESCRIPTION = 'This is description';
    static void setup()
    {
        SEAD_Configuration__c config = new SEAD_Configuration__c();
        config.Name = 'Default';
        config.Lead_New_Stage_Activity_Limit__c = 1;
        config.Lead_Qualified_Stage_Activity_Limit__c = 2;
        config.Lead_Validated_Stage_Activity_Minimum__c = 3;
        config.Lead_Abandoner_Score__c = 1;
        config.Lead_Chat_Score__c = 1;
        config.Lead_Days_from_Ownership__c = 2;
        config.Lead_Email_Score__c = 1;
        config.Lead_Inbound_Score__c = 2;
        config.Lead_Mobile_Score__c = 3;
        config.Lead_Score_Initial__c = 3;
        config.Lead_Social_Media_Score__c = 1;


        insert config;
    }
    static void setupData()
    {
        setup();
        testAccount = TestUtils.createAccounts(SIZE_ONE , TEST_ACCOUNT, true)[0];
        testContact = TestUtils.createContacts(SIZE_ONE , TEST_CONTACT , testAccount.Id , true)[0];
        
        
        testCases = TestUtils.createCases( SIZE_THREE , false);
        for(Case theCase : testCases)
        {
            theCase.Order_Number__c = ORDER_NUMBER;
            theCase.Processing_Number__c = USER_ORDER_ID;
        }
        
        
        
        testOrder = TestUtils.createOrders(SIZE_ONE, null , false)[0];
        testOrder.OrderID__c = ORDER_NUMBER;
        insert testOrder;
        noteTasks = TestUtils.createTasks(SIZE_THREE , testOrder.Id , false); 
        testOrderItem = TestUtils.createOrderItems(SIZE_ONE , testOrder.Id ,  false)[0];
        testOrderItem.User_Order_ID__c = USER_ORDER_ID;
        insert testOrderItem;

    }

    static testMethod void testSave_Case()
    {   
        setupData();
        ApexPages.StandardController sc = new ApexPages.standardController(testOrderItem);
        NextPadController theController = new NextPadController(sc);
        theController.description = DESCRIPTION;
        theController.theNextPadService.orderNumber = USER_ORDER_ID;
        theController.theNextPadService.orderId = testOrder.Id;
        theController.selectedNoteType = NextPadService.PROBLEM_ORDER;
        Test.startTest();
            theController.SaveNote();
        Test.stopTest();

        List<Case> createdCases = [SELECT Id , Description FROM Case];
        System.assertEquals(SIZE_ONE , createdCases.size() , SIZE_ONE+' record should have been created');
        System.assertEquals(DESCRIPTION , createdCases[0].Description , 'Right description should have been populated');
    }

    static testMethod void testSave_Task()
    {   
        setupData();
        ApexPages.StandardController sc = new ApexPages.standardController(testOrderItem);
        NextPadController theController = new NextPadController(sc);
        theController.description = DESCRIPTION;
        theController.theNextPadService.orderNumber = USER_ORDER_ID;
        theController.theNextPadService.orderId = testOrder.Id;
        theController.selectedNoteType = NextPadService.ORDER_NOTE;
        Test.startTest();
            theController.SaveNote();
        Test.stopTest();

        List<Task> createdTasks = [SELECT Id , Description FROM Task];
        System.assertEquals(SIZE_ONE , createdTasks.size() , SIZE_ONE+' record should have been created');
        System.assertEquals(DESCRIPTION , createdTasks[0].Description , 'Right description should have been populated');
    }


    static testMethod void testPopulateProcessingNumber()
    {
        setupData();
        PageReference pageRef = Page.NextPad;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('processingNumber', USER_ORDER_ID);
      
        Test.startTest();
              ApexPages.StandardController sc = new ApexPages.standardController(testOrderItem);
              NextPadController theController = new NextPadController(sc);
        Test.stopTest();

        System.assertEquals(USER_ORDER_ID , theController.processingNumber , 'Right processing number should have been populated'); 

    }

    static testMethod void testCancel()
    {
        setupData();
        PageReference pageRef = Page.NextPad;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('processingNumber', USER_ORDER_ID);
        
        ApexPages.StandardController sc = new ApexPages.standardController(testOrderItem);
        NextPadController theController = new NextPadController(sc);

        theController.description = 'Test Description';
        Test.startTest();
              theController.clear();
        Test.stopTest();

        System.assertEquals('' , theController.description , 'Description should have been cleared out');   

    }

    static testMethod void testPopulateAllNotes()
    {
        setupData();
        insert testCases;
        caseComments = new List<CaseComment>();
        for(Case theCase : testCases)
        {
            CaseComment theComment = new CaseComment();
            theComment.commentBody = 'Test Comment';
            theComment.ParentId = theCase.Id;
            caseComments.add(theComment);
        }

        insert caseComments;
        insert noteTasks;
        ApexPages.StandardController sc = new ApexPages.standardController(testOrderItem);
        NextPadController theController = new NextPadController(sc);
        theController.processingNumber = USER_ORDER_ID;
        Test.startTest();
            theController.populateAllNotes();
        Test.stopTest();

        System.assertEquals(6 , theController.allNotes.size() ,'6 records hsould have been populated');
    }


    static testMethod void testFilterNotes()
    {
        setupData();
        insert testCases;
        caseComments = new List<CaseComment>();
        for(Case theCase : testCases)
        {
            CaseComment theComment = new CaseComment();
            theComment.commentBody = 'Test Comment';
            theComment.ParentId = theCase.Id;
            caseComments.add(theComment);
        }

        insert caseComments;
        insert noteTasks;
        ApexPages.StandardController sc = new ApexPages.standardController(testOrderItem);
        NextPadController theController = new NextPadController(sc);

        theController.processingNumber = USER_ORDER_ID;
        update testCases;
        theController.filterNoteType = NextPadService.THE_CASE;
        Test.startTest();
            theController.filterNotes();
        Test.stopTest();
        System.assertEquals(SIZE_THREE ,theController.allNotes.size() ,SIZE_THREE + ' record should have been populated');
    }

    static testMethod void testSortNotesByUser()
    {
        setupData();
        insert testCases;
        caseComments = new List<CaseComment>();
        for(Case theCase : testCases)
        {
            CaseComment theComment = new CaseComment();
            theComment.commentBody = 'Test Comment';
            theComment.ParentId = theCase.Id;
            caseComments.add(theComment);
        }

        insert caseComments;
        insert noteTasks;
        ApexPages.StandardController sc = new ApexPages.standardController(testOrderItem);
        NextPadController theController = new NextPadController(sc);

        theController.processingNumber = USER_ORDER_ID;
        update testCases;
        Test.startTest();
            theController.sortNotesByUser();
        Test.stopTest();
        
    }



}