src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer_Login__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Login</label>
        <referenceTo>Customer_Login__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateTime_Problem_Identified__c</fullName>
        <label>Date/Time Problem Identified</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Problem_Order_Type__c</fullName>
        <label>Problem Order Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <description>Queue field</description>
        <label>Queue</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Biz 501c3</fullName>
                </value>
                <value>
                    <fullName>Biz Alt Names</fullName>
                </value>
                <value>
                    <fullName>Biz Escalation</fullName>
                </value>
                <value>
                    <fullName>Biz HA Sweeps</fullName>
                </value>
                <value>
                    <fullName>Biz QC Approval</fullName>
                </value>
                <value>
                    <fullName>BIZ RA SOP</fullName>
                </value>
                <value>
                    <fullName>CC Biz</fullName>
                </value>
                <value>
                    <fullName>CC IP</fullName>
                </value>
                <value>
                    <fullName>CC Manager Call-Back</fullName>
                </value>
                <value>
                    <fullName>CC Mock Launch Requests</fullName>
                </value>
                <value>
                    <fullName>CC PS</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Billing Updates</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Materials</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Order Updates</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Post Filing</fullName>
                </value>
                <value>
                    <fullName>IP Copyrights</fullName>
                </value>
                <value>
                    <fullName>IP Partners and Firms</fullName>
                </value>
                <value>
                    <fullName>IP Patent Billing Updates</fullName>
                </value>
                <value>
                    <fullName>IP Patent Drawings</fullName>
                </value>
                <value>
                    <fullName>IP Patent Materials</fullName>
                </value>
                <value>
                    <fullName>IP Patent Order Updates</fullName>
                </value>
                <value>
                    <fullName>IP Patent Search Approval</fullName>
                </value>
                <value>
                    <fullName>IP Patents</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Billing Updates</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Monitoring</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Order Updates</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Search</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Search Approvals</fullName>
                </value>
                <value>
                    <fullName>IP Trademarks</fullName>
                </value>
                <value>
                    <fullName>IP Trademarks Goods and Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Automatic_Outbound_Emails__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Automatic Outbound Emails</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_outbound_emails__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Outbound Emails</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <label>User Order ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Customer_Login__c.object
<CustomObject>
    <description>The equivalent of LZData User table</description>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Login</relationshipLabel>
        <relationshipName>Customer_Login</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Login</label>
    <nameField>
        <label>Customer Login/Email</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Login</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Login__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Login</label>
        <referenceTo>Customer_Login__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LZ_Product_ID__c</fullName>
        <formula>Text(Order_Item__r.Product__r.LZ_Product_ID__c)</formula>
        <label>LZ Product ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <formula>Base_Product__r.Process__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Show process name of the base product on the order</description>
        <formula>Base_Product__r.Process__r.Name</formula>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>LZ_Product_ID__c</fullName>
        <formula>Text( Product__r.LZ_Product_ID__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LZ Product ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <description>matching the fkUserOrder field of OrderItem table in lzdata</description>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/POR_case_routing_queues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Map of Product to Queue Map for case creation when the a Problem order is created by DI.</description>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <description>Stores the API name of Queue</description>
        <label>Queue Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_DeveloperName__c</fullName>
        <label>Template DeveloperName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>POR Case Routing Queues</label>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <description>matching Process table in LZData</description>
    <fields>
        <fullName>Process_ID__c</fullName>
        <description>From iProcess field in pkProcess table of LZData database</description>
        <externalId>true</externalId>
        <label>Process ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LZ_Product_ID__c</fullName>
        <description>matching pkProductConfiguration column of ProductConfiguation table in LZData</description>
        <externalId>true</externalId>
        <label>LZ Product ID</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Relationship_Type__c.object
<CustomObject>
    <description>matching RelationshipType table in LZData</description>
    <fields>
        <fullName>Relationship_Type_ID__c</fullName>
        <externalId>true</externalId>
        <label>Relationship Type ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Relationship Type</label>
    <nameField>
        <label>Relationship Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ProblemOrderRoutingServiceTest.cls
@isTest
public class ProblemOrderRoutingServiceTest 
{
public static List<Order__c> newOrders = new List<Order__c>();
public static Customer_Login__c newCustomerLogin = new Customer_Login__c();
public static Contact newContact = new Contact();
final static Datetime problemIdentified = system.today().addDays(-2);
public static Id relationshipTypeId;
public static Process__c newProcess;
public static Process__c newProcess2;
public static Product2 newProducts_revision;
public static Product2 newProduct;
public static Relationship_Type__c relationshipTypeId_Revised;
public final static Integer SIZE = 1;

    public static void setupData()
    {
        OrderService.hasOrderMatchingTriggerRun = true;
        //insert custom seetings for queue
        POR_case_routing_queues__c PORSetting = new POR_case_routing_queues__c(
            Name = ProblemOrderConstants.POA, 
            Queue_Name__c = ProblemOrderConstants.QUEUE_NAME,
            Template_DeveloperName__c = ProblemOrderConstants.EMAIL_TEMPLATE);
        insert PORSetting;

        //create relationship id for a process
        relationshipTypeId = TestUtils.createRelationshipTypesTypes(1 , 'Process' , true)[0].Id;
        relationshipTypeId_Revised = TestUtils.createRelationshipTypesTypes(1 , '' , false)[0];
        relationshipTypeId_Revised.Name = 'Revision';
        relationshipTypeId_Revised.Relationship_Type_ID__c = '1';
        insert relationshipTypeId_Revised;
        system.debug(relationshipTypeId_Revised);

        //create process
        newProcess = new Process__c();
            newProcess.Name = ProblemOrderConstants.POA;
            newProcess.Process_ID__c = 1;
         insert newProcess;

         //create process for revision
        Process__c newProcess_revision = new Process__c();
            newProcess_revision.Name = ProblemOrderConstants.REVISION;
            newProcess_revision.Process_ID__c = 2;
         insert newProcess_revision;

        //create new product
        List<Product2> newProducts = TestUtils.createProducts(1 , '', false);
        newProducts[0].Name = ProblemOrderConstants.POA;
        newProducts[0].Relationship_Type__c = relationshipTypeId;
        newProducts[0].Process__c = newProcess.Id;
        insert newProducts;

         newProcess2 = new Process__c();
            newProcess2.Name = ProblemOrderConstants.EP_BUNDLE;
            newProcess2.Process_ID__c = 3;
         insert newProcess2;

        newProduct = TestUtils.createProducts(1 , '', false)[0];
        newProduct.Name = ProblemOrderConstants.EP_BUNDLE;
        newProduct.Relationship_Type__c = TestUtils.createRelationshipTypesTypes(1 , 'Cross Sell' , true)[0].Id;
        newProduct.LZ_Product_ID__c = 3;
        newProduct.Process__c = newProcess2.Id;
        insert newProduct;

        //insert Account
        Account newAccount = TestUtils.createAccounts(1 , 'POR Account' , true)[0];

        //insert contact
        newContact = TestUtils.createContacts(1 , 'POR Contact' , newAccount.Id , false)[0];
        newContact.Email = 'lzPORtest@lzTestClass.com';
        insert newContact;

        //insert Customer login
        newCustomerLogin = TestUtils.createCustomerLogins(1 , 'Cust Login' , false)[0];
        newCustomerLogin.Primary_Contact__c = newContact.Id;
        insert newCustomerLogin;

        //insert dummy orders
        newOrders = TestUtils.createOrders(SIZE, newProducts[0].Id, false);
        integer i=0;
        for(Order__c theOrder : newOrders)
        {
            theOrder.contact__c = newContact.Id;
            theOrder.customer_Login__c = newCustomerLogin.Id;
            theOrder.User_Order_ID__c = '500000'+i;
            i++;
        }
        insert newOrders;

        List<Order_Item__c> orderItemsToinsert = new List<Order_Item__c>();
        for(Order__c theOrder : newOrders)
        {
            Order_Item__c newOrderItem = new Order_Item__c();
            newOrderItem.Order__c = theOrder.Id;
            newOrderItem.Product__c = newProducts[0].Id;
            newOrderItem.User_Order_ID__c = theOrder.User_Order_ID__c;
            orderItemsToinsert.add(newOrderItem);
        }
        insert orderItemsToinsert;
    }
    
    
    static testMethod void createCaseForProblemOrderTest_NotIntegrationUser()
    {
        setupData();
        Set<Id> orderIds = new Set<Id>(); 
        List<Task> tasksToCreate = new List<Task>();

        //create problem orders(tasks with action type = Manual Problem Order)
        for(Order__C theOrder : newOrders)
        {
            Task theTask = new Task();
            theTask.WhatId = theOrder.id;
            theTask.Description = 'Test Description';
            theTask.Action_Type__C = ProblemOrderConstants.ACTION_TYPE;
            theTask.Datetime_Created_External_System__c = problemIdentified;
            theTask.User_Order_ID__c = theOrder.User_Order_ID__c;
            tasksToCreate.add(theTask);
            orderIds.add(theOrder.Id);
        }

        Test.startTest();
            insert tasksToCreate;
        Test.stopTest();


        List<Case> insertedCases = [Select Id, Queue__c , Product__c , Problem_Order_Type__c , Total_Automatic_Outbound_Emails__c , Customer_Login__c , ContactId , DateTime_Problem_Identified__c , Total_Outbound_Emails__c From Case Where Order__c In: orderIds];
        //System.assertEquals(insertedCases.size(),SIZE, SIZE+' cases should have been created');

        for(Case theCase : insertedCases)
        {
            system.assertEquals(ProblemOrderConstants.QUEUE_NAME, theCase.Queue__c);
            system.assertEquals(ProblemOrderConstants.POA, theCase.Product__c);
            system.assertEquals(ProblemOrderConstants.ACTION_TYPE, theCase.Problem_Order_Type__c);
            system.assertEquals(newCustomerLogin.id, theCase.Customer_Login__c);
            system.assertEquals(newContact.Id, theCase.ContactId);
            system.assertEquals(problemIdentified, theCase.DateTime_Problem_Identified__c);
            system.assertEquals(1, theCase.Total_Outbound_Emails__c);
            system.assertEquals(0, theCase.Total_Automatic_Outbound_Emails__c);
        }
    }

    static testMethod void createCaseForProblemOrderTest_IntegrationUser()
    {
        setupData();
        Set<Id> orderIds = new Set<Id>(); 
        List<Task> tasksToCreate = new List<Task>();

        //create problem orders(tasks with action type = Manual Problem Order)
        for(Order__C theOrder : newOrders)
        {
            Task theTask = new Task();
            theTask.WhatId = theOrder.id;
            theTask.Description = 'Test Description';
            theTask.Action_Type__C = ProblemOrderConstants.ACTION_TYPE;
            theTask.Datetime_Created_External_System__c = problemIdentified;
            theTask.User_Order_ID__c = theOrder.User_Order_ID__c;
            tasksToCreate.add(theTask);
            orderIds.add(theOrder.Id);
        }

        Test.startTest();
            System.runAs(UtilityLibrary.integrationUser) //used the Utility library to retrieve the integration user: B-38758
            {
                insert tasksToCreate;
            }
        Test.stopTest();


        List<Case> insertedCases = [Select Id, Queue__c , Product__c , Problem_Order_Type__c , Total_Automatic_Outbound_Emails__c , Customer_Login__c , ContactId , DateTime_Problem_Identified__c , Total_Outbound_Emails__c From Case Where Order__c In: orderIds];
        //System.assertEquals(insertedCases.size(),SIZE, SIZE+' cases should have been created');

        for(Case theCase : insertedCases)
        {
            system.assertEquals(ProblemOrderConstants.QUEUE_NAME, theCase.Queue__c);
            system.assertEquals(ProblemOrderConstants.POA, theCase.Product__c);
            system.assertEquals(ProblemOrderConstants.ACTION_TYPE, theCase.Problem_Order_Type__c);
            system.assertEquals(newCustomerLogin.id, theCase.Customer_Login__c);
            system.assertEquals(newContact.Id, theCase.ContactId);
            system.assertEquals(problemIdentified, theCase.DateTime_Problem_Identified__c);
            system.assertEquals(1, theCase.Total_Outbound_Emails__c);
            system.assertEquals(1, theCase.Total_Automatic_Outbound_Emails__c);
        }
    }

    static testMethod void createCaseForProblemOrderTest_CrossSell()
    {
        setupData();
        //insert dummy orders
        newOrders = TestUtils.createOrders(SIZE, newProduct.Id, false);
        integer i=0;
        for(Order__c theOrder : newOrders)
        {
            theOrder.contact__c = newContact.Id;
            theOrder.customer_Login__c = newCustomerLogin.Id;
            theOrder.User_Order_ID__c = '500000'+i;
            i++;
        }
        insert newOrders;

        List<Order_Item__c> orderItemsToinsert = new List<Order_Item__c>();
        for(Order__c theOrder : newOrders)
        {
            Order_Item__c newOrderItem = new Order_Item__c();
            newOrderItem.Order__c = theOrder.Id;
            newOrderItem.Product__c = newProduct.Id;
            newOrderItem.User_Order_ID__c = theOrder.User_Order_ID__c;
            orderItemsToinsert.add(newOrderItem);
        }
        insert orderItemsToinsert;
        system.debug(orderItemsToinsert);
        Set<Id> orderIds = new Set<Id>(); 
        List<Task> tasksToCreate = new List<Task>();

        //create problem orders(tasks with action type = Manual Problem Order)
        for(Order__C theOrder : newOrders)
        {
            Task theTask = new Task();
            theTask.WhatId = theOrder.id;
            theTask.Description = 'Test Description';
            theTask.Action_Type__C = ProblemOrderConstants.ACTION_TYPE;
            theTask.Datetime_Created_External_System__c = problemIdentified;
            theTask.User_Order_ID__c = theOrder.User_Order_ID__c;
            tasksToCreate.add(theTask);
            orderIds.add(theOrder.Id);
        }
        system.debug(tasksToCreate);
        Test.startTest();
            System.runAs(UtilityLibrary.integrationUser)//used the Utility library to retrieve the integration user: B-38758
            {
                insert tasksToCreate;
            }
        Test.stopTest();

        List<Case> insertedCases = [Select Id, Queue__c , Product__c , Problem_Order_Type__c , Total_Automatic_Outbound_Emails__c , Customer_Login__c , ContactId , DateTime_Problem_Identified__c , Total_Outbound_Emails__c From Case Where Order__c In: orderIds];
        //System.assertEquals(insertedCases.size(),SIZE, SIZE+' cases should have been created');
        system.debug(insertedCases);
        for(Case theCase : insertedCases)
        {
            system.assertEquals(ProblemOrderConstants.QUEUE_NAME, theCase.Queue__c);
            system.assertEquals(ProblemOrderConstants.EP_BUNDLE, theCase.Product__c);
            system.assertEquals(ProblemOrderConstants.ACTION_TYPE, theCase.Problem_Order_Type__c);
            system.assertEquals(newCustomerLogin.id, theCase.Customer_Login__c);
            system.assertEquals(newContact.Id, theCase.ContactId);
            system.assertEquals(1, theCase.Total_Outbound_Emails__c);
            system.assertEquals(1, theCase.Total_Automatic_Outbound_Emails__c);
        }


    }
    

    static testMethod void closeRelatedOpenCasesForRevisedOrderTest()
    {
        setupData();
        Set<Id> orderIds = new Set<Id>(); 
        List<Task> tasksToCreate = new List<Task>();
        List<Order_Item__c> revisedItems = new List<Order_Item__c>();

        //create problem orders(tasks with action type = Manual Problem Order)
        for(Order__C theOrder : newOrders)
        {
            Task theTask = new Task();
            theTask.WhatId = theOrder.id;
            theTask.Description = 'Test Description';
            theTask.Action_Type__C = ProblemOrderConstants.ACTION_TYPE;
            theTask.Datetime_Created_External_System__c = problemIdentified;
            theTask.User_Order_ID__c =  theOrder.User_Order_ID__c; 
            tasksToCreate.add(theTask);
            orderIds.add(theOrder.Id);
        }
        test.starttest();
        insert tasksToCreate;
        test.stoptest();
        for(Order__c theOrder : newOrders)
        {
            Order_Item__c revisedOrder = new Order_Item__c();
            revisedOrder.Order__c = theOrder.Id;
            revisedOrder.User_Order_ID__c = theOrder.User_Order_ID__c;
            revisedOrder.Relationship_Type__c = relationshipTypeId_Revised.Id;
            revisedOrder.Name = '3'+theOrder.User_Order_ID__c;
            revisedItems.add(revisedOrder);
        }

        
            insert revisedItems;
        
       system.debug(newOrders);
        List<Case> insertedCases = [Select Id, Status, Problem_Order_Resolution__c From Case Where Order__c In: orderIds];
        for(Case theCase : insertedCases)
        {
            system.assertEquals('Closed',theCase.Status);
            system.assertEquals('Resolved – Revision Placed on LZ.com',theCase.Problem_Order_Resolution__c);
        }
    }
    
    static testMethod void closeRelatedOpenCasesForRevisedOrderTest_after7day()
    {
        setupData();
        Set<Id> orderIds = new Set<Id>(); 
        List<Task> tasksToCreate = new List<Task>();
        List<Order_Item__c> revisedItems = new List<Order_Item__c>();

        //create problem orders(tasks with action type = Manual Problem Order)
        for(Order__C theOrder : newOrders)
        {
            Task theTask = new Task();
            theTask.WhatId = theOrder.id;
            theTask.Description = 'Test Description';
            theTask.Action_Type__C = ProblemOrderConstants.ACTION_TYPE;
            theTask.Datetime_Created_External_System__c = problemIdentified;
            theTask.User_Order_ID__c =  theOrder.User_Order_ID__c; 
            tasksToCreate.add(theTask);
            orderIds.add(theOrder.Id);
        }
        test.starttest();
        insert tasksToCreate;
        test.stoptest();
        List<Case> insertedCases = [Select Id, Status, Problem_Order_Resolution__c From Case Where Order__c In: orderIds];
        for(Case theCase : insertedCases)
        {
            theCase.Problem_Order_Resolution__c = ProblemOrderConstants.UNRESOLVED_CLOSED;
        }
        update insertedCases;

        for(Order__c theOrder : newOrders)
        {
            Order_Item__c revisedOrder = new Order_Item__c();
            revisedOrder.Order__c = theOrder.Id;
            revisedOrder.User_Order_ID__c = theOrder.User_Order_ID__c;
            revisedOrder.Relationship_Type__c = relationshipTypeId_Revised.Id;
            revisedOrder.Name = '3'+theOrder.User_Order_ID__c;
            revisedItems.add(revisedOrder);
        }

        
            insert revisedItems;
        
       system.debug(newOrders);
        List<Case> insertedCases2 = [Select Id, Status, Problem_Order_Resolution__c From Case Where Order__c In: orderIds];
        for(Case theCase : insertedCases2)
        {
            system.assertEquals('Closed',theCase.Status);
            system.assertEquals(ProblemOrderConstants.REVISION_AFTER_7DAY_STATUS,theCase.Problem_Order_Resolution__c);
        }
    }
    
}