src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <description>Customer Id of the Account</description>
        <formula>Account.Customer_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Login__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Login</label>
        <referenceTo>Customer_Login__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>FkUser__c</fullName>
        <externalId>true</externalId>
        <label>FkUser</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Genesys_Interaction_Id__c</fullName>
        <description>Genesys Interaction Id</description>
        <externalId>true</externalId>
        <label>Genesys Interaction Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Customer_Login__c.object
<CustomObject>
    <description>The equivalent of LZData User table</description>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <description>fkUser in User table in LZData</description>
        <externalId>true</externalId>
        <label>Customer Number</label>
        <length>13</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Login</relationshipLabel>
        <relationshipName>Customer_Login</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Login</label>
    <nameField>
        <label>Customer Login/Email</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Login</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DisplayPrimaryContactController.cls
public with sharing class DisplayPrimaryContactController {
    
    private final Contact cont;

    public Id primaryContactId{get;set;}
    public String contactId{get;set;}
    public List<IADMessage> iadMessages{get;set;}
    public String interactionId{get;set;}

    public DisplayPrimaryContactController(ApexPages.StandardController stdController) {
        
        iadMessages = new List<IADMessage>();
        this.cont = (Contact)stdController.getRecord();
        contactId = cont.Id;
        if(contactId != null)
        {
            List<Contact> contacts = [SELECT FkUser__c , Genesys_Interaction_Id__c FROM Contact WHERE Id = :contactId];
            if(!contacts.isEmpty() && contacts[0].FkUser__c != null)
            {
                List<Customer_Login__c> customerLogins = [SELECT Id , Primary_Contact__c FROM Customer_Login__c WHERE Customer_ID__c = :contacts[0].FkUser__c];
                if(!customerLogins.isEmpty())
                {
                    primaryContactId = customerLogins[0].Primary_Contact__c;
                    if(contacts[0].Genesys_Interaction_Id__c != null)
                    {
                        interactionId = contacts[0].Genesys_Interaction_Id__c;
                        
                    }
                    else
                    {
                        iadMessages.add(IADMessageFactory.createMessage('error' , 'Genesys Activity Not Found')); 
                    }
                }
                else
                {
                      iadMessages.add(IADMessageFactory.createMessage('error' , 'Can\'t find Primary Contact'));  
                }
            }
            else
            {
                 iadMessages.add(IADMessageFactory.createMessage('error' , 'Can\'t find Customer Login Id (FKUser) on Authorized Contact'));
            }
        }
    }


    public void transferTask()
    {
        Datetime startTime = system.now().addHours(-2);
        Datetime endTime = system.now();
        List<Task> tasks = [SELECT Id FROM Task WHERE whoId = :contactId AND CallObject = :interactionId  AND (CreatedDate >=: startTime and 
        				   CreatedDate <=: endTime) AND Subject != 'Case Activity' order by createddate desc];
        Savepoint sp = Database.setSavepoint();
        if(!tasks.isEmpty())
        {
            try
            {
                
                tasks[0].whoId = primaryContactId;
                update tasks;
                Contact theContact = new Contact(Id = primaryContactId , Genesys_Interaction_Id__c = interactionId);
                update theContact;
            }
            catch(DmlException dmlEx)
            {
                 Database.rollback(sp);
                 iadMessages.add(IADMessageFactory.createMessage('error' , 'Failed associating Genesys Activity to Primary Contact'));
            }

        }
    }


    public void openPrimaryContact()
    {
        if(primaryContactId != null && interactionId != null)
            transferTask();
    }
}