src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Email_Subject__c</fullName>
        <label>Email Subject</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Draft_Email__c.object
<CustomObject>
    <fields>
        <fullName>AdditionToAddresses__c</fullName>
        <label>AdditionToAddresses</label>
        <length>3745</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BCCAddresses__c</fullName>
        <label>BCCAddresses</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCAddresses__c</fullName>
        <label>CCAddresses</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Custom_Email_Messages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ToAddresses__c</fullName>
        <label>ToAddresses</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Draft Email</label>
    <nameField>
        <label>Draft Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Draft Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Email_Subject__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used while sending the email.</description>
    <label>Email Subject</label>
</CustomObject>

src/objects/HVCR_Email_New__c.object
<CustomObject>
    <fields>
        <fullName>BCCAddresses__c</fullName>
        <label>BCC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCAddresses__c</fullName>
        <label>CC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>HVCR_Case_New</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FromAddressLong__c</fullName>
        <label>From</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsInbound__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsInbound</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ToAddressesLong__c</fullName>
        <label>To</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ToAddresses__c</fullName>
        <label>To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>HVCR Email New</label>
    <nameField>
        <label>HVCR_Email_New_Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HVCR Emails New</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Email_Forward_Controller_Test.cls
@isTest 
public with sharing class Email_Forward_Controller_Test 
{
	static EmailMessage testEmailMessage;
	static Case testCase;
	static Contact testContact;
	static Account testAccount;
	static final Integer SIZE = 1;
	static final String ID = 'id';
	static final String CUSTOM_EMAIL_ID = 'customemailid';
	static final String OBJECT_NAME = 'objectName';
	static final String OPTION = 'option';
	static HVCR_Email_New__c hvcrEmail;
	static Draft_Email__c testDraftEmail;
	
	static void setupData()
	{
		testAccount = TestUtils.createAccounts(SIZE , 'Test Account', true)[0];
		testContact = TestUtils.createContacts( SIZE ,  'Buffet ', testAccount.Id , true)[0];
		testCase = TestUtils.createCases( SIZE, false)[0];
		testCase.ContactId = testContact.Id;
		testCase.Email_Subject__c  = 'Test Subject';
		insert testCase;
		
		testEmailMessage = TestUtils.createEmailMessages(SIZE , testCase.Id , false)[0];
		testEmailMessage.FromAddress = 'testFromAddress@test.com';
		testEmailMessage.Incoming = true;
		testEmailMessage.CcAddress = 'testCcAddress@test.com';
		testEmailMessage.BccAddress = 'testBccAddress@test.com';
		testEmailMessage.HtmlBody = 'Test Body';
		
		insert testEmailMessage;
		
		hvcrEmail = TestUtils.createHVCRMessage(SIZE , testCase.Id , false)[0];
		hvcrEmail.FromAddressLong__c = 'testFromEmail@test.com';
		hvcrEmail.ToAddressesLong__c = 'testToEmail@test.com';
		hvcrEmail.IsInbound__c = true;
		hvcrEmail.Body__c = 'Test Body';
		insert hvcrEmail;
		
		testDraftEmail= TestUtils.createDraftEmails(1 , false)[0];
		testDraftEmail.Body__c = 'Draft Message Body';
		testDraftEmail.CCAddresses__c = 'draftCCAddress@test.com';
		testDraftEmail.bccaddresses__c = 'draftBccAddress@test.com';
		testDraftEmail.toaddresses__c = 'draftToAddress@test.com';
		testDraftEmail.additionToAddresses__c  = 'draftAdditionalToAddress@test.com';
		testDraftEmail.Case__c = testCase.Id;
		insert testDraftEmail;
	}
	
	static testMethod void testForwardEmailFor_EmailMessage()
	{
		setupData();
		List<Attachment> draftEmailAttachments = TestUtils.createAttachments( 10 , testEmailMessage.Id, false);
		insert draftEmailAttachments;
		
		PageReference pageRef = Page.Email_Forward_Page;
		pageRef.getParameters().put(ID , testCase.Id);
		pageRef.getParameters().put('value' , testEmailMessage.Id);
		pageRef.getParameters().put('objectName' , 'EmailMessage');
		Test.setCurrentPage(pageRef);
		Test.startTest();
			Email_Forward_Controller theController = new Email_Forward_Controller();
			theController.sendEmail();
		Test.stopTest();
	}
	
	static testMethod void testForwardEmailFor_HVCRMessage()
	{
		setupData();
		List<Attachment> draftEmailAttachments = TestUtils.createAttachments( 10 , hvcrEmail.Id, false);
		insert draftEmailAttachments;
		
		PageReference pageRef = Page.Email_Forward_Page;
		pageRef.getParameters().put(ID , testCase.Id);
		pageRef.getParameters().put('value' , hvcrEmail.Id);
		pageRef.getParameters().put('objectName' , 'HVCR_Email_New__c');
		Test.setCurrentPage(pageRef);
		Test.startTest();
			Email_Forward_Controller theController = new Email_Forward_Controller();
			theController.tohid = testContact.Id;
			theController.sendEmail();
		Test.stopTest();
	}
	
	static testMethod void testMethods()
	{
		setupData();
		List<Attachment> draftEmailAttachments = TestUtils.createAttachments( 10 , hvcrEmail.Id, false);
		insert draftEmailAttachments;
				
		PageReference pageRef = Page.Email_Forward_Page;
		pageRef.getParameters().put(ID , testCase.Id);
		pageRef.getParameters().put('value' , hvcrEmail.Id);
		pageRef.getParameters().put('objectName' , 'HVCR_Email_New__c');
		Test.setCurrentPage(pageRef);
		Email_Forward_Controller theController = new Email_Forward_Controller();
		
		Test.startTest();
			theController.ClearResult();
			theController.Cancel();
			theController.sendAndClose();
			List<Email_Forward_Controller.FileDetail> files = theController.attfile;
			List<SelectOption> selectOptions = theController.getemailsOptions();
		Test.stopTest();
	}
}