src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer_Login__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Login</label>
        <referenceTo>Customer_Login__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processing_Number__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Standard_Case</fullName>
        <active>true</active>
        <businessProcess>LegalZoom Standard Support Process</businessProcess>
        <description>Standard Customer-Facing Case</description>
        <label>Standard Service Inquiry</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <label>User Order ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Customer_Login__c.object
<CustomObject>
    <description>The equivalent of LZData User table</description>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Login</relationshipLabel>
        <relationshipName>Customer_Login</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Login</label>
    <nameField>
        <label>Customer Login/Email</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Login</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Login__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Login</label>
        <referenceTo>Customer_Login__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <formula>Base_Product__r.Process__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Show process name of the base product on the order</description>
        <formula>Base_Product__r.Process__r.Name</formula>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <description>matching the fkUserOrder field of OrderItem table in lzdata</description>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/POR_case_routing_queues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Map of Product to Queue Map for case creation when the a Problem order is created by DI.</description>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <description>Stores the API name of Queue</description>
        <label>Queue Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_DeveloperName__c</fullName>
        <label>Template DeveloperName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>POR Case Routing Queues</label>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <description>matching Process table in LZData</description>
    <fields>
        <fullName>Process_ID__c</fullName>
        <description>From iProcess field in pkProcess table of LZData database</description>
        <externalId>true</externalId>
        <label>Process ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Relationship_Type__c.object
<CustomObject>
    <description>matching RelationshipType table in LZData</description>
    <fields>
        <fullName>Relationship_Type_ID__c</fullName>
        <externalId>true</externalId>
        <label>Relationship Type ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Relationship Type</label>
    <nameField>
        <label>Relationship Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/IADHighlightsPanelPORCasesControllerTest.cls
@isTest
public class IADHighlightsPanelPORCasesControllerTest {

    static List<Order__c> newOrders = new List<Order__c>();
    static Customer_Login__c newCustomerLogin = new Customer_Login__c();
    static Contact newContact = new Contact();
    final static Datetime problemIdentified = system.today().addDays(-2);
    static Id relationshipTypeId;
    static Process__c newProcess;
    static Product2 newProduct;
    static Relationship_Type__c relationshipTypeId_Revised;
    final static Integer SIZE = 1;
    
    static void setupData()
    {
       
        //insert custom seetings for queue
        POR_case_routing_queues__c PORSetting = new POR_case_routing_queues__c(
            Name = ProblemOrderConstants.POA, 
            Queue_Name__c = ProblemOrderConstants.QUEUE_NAME,
            Template_DeveloperName__c = ProblemOrderConstants.EMAIL_TEMPLATE);
        insert PORSetting;

        //create relationship id for a process
        relationshipTypeId = TestUtils.createRelationshipTypesTypes(1 , 'Process' , true)[0].Id;
        relationshipTypeId_Revised = TestUtils.createRelationshipTypesTypes(1 , '' , false)[0];
        relationshipTypeId_Revised.Name = 'Revision';
        relationshipTypeId_Revised.Relationship_Type_ID__c = '1';
        insert relationshipTypeId_Revised;
        system.debug(relationshipTypeId_Revised);

        //create process
        newProcess = new Process__c();
            newProcess.Name = ProblemOrderConstants.POA;
            newProcess.Process_ID__c = 1;
         insert newProcess;

        //create new product
        List<Product2> newProducts = TestUtils.createProducts(1 , '', false);
        newProducts[0].Name = ProblemOrderConstants.POA;
        newProducts[0].Relationship_Type__c = relationshipTypeId;
        newProducts[0].Process__c = newProcess.Id;
        insert newProducts;

        //insert Account
        Account newAccount = TestUtils.createAccounts(1 , 'POR Account' , true)[0];

        //insert contact
        newContact = TestUtils.createContacts(1 , 'POR Contact' , newAccount.Id , false)[0];
        newContact.Email = 'lzPORtest@lzTestClass.com';
        insert newContact;

        //insert Customer login
        newCustomerLogin = TestUtils.createCustomerLogins(1 , 'Cust Login' , false)[0];
        newCustomerLogin.Primary_Contact__c = newContact.Id;
        insert newCustomerLogin;

        //insert dummy orders
        newOrders = TestUtils.createOrders(SIZE, newProducts[0].Id, false);
        integer i=0;
        for(Order__c theOrder : newOrders)
        {
            theOrder.contact__c = newContact.Id;
            theOrder.customer_Login__c = newCustomerLogin.Id;
            theOrder.User_Order_ID__c = '500000'+i;
            i++;
        }
        insert newOrders;

        List<Order_Item__c> orderItemsToinsert = new List<Order_Item__c>();
        for(Order__c theOrder : newOrders)
        {
            Order_Item__c newOrderItem = new Order_Item__c();
            newOrderItem.Order__c = theOrder.Id;
            newOrderItem.Product__c = newProducts[0].Id;
            newOrderItem.User_Order_ID__c = theOrder.User_Order_ID__c;
            orderItemsToinsert.add(newOrderItem);
        }
        insert orderItemsToinsert;
        
        
        List<Case> createCasesRelatedToContact = TestUtils.createCasesRelatedToContact(SIZE, true, newContact);
        
        RecordType rt = [SELECT Id,Name,DeveloperName FROM RecordType 
                 WHERE sObjectType = 'Case' and DeveloperName = 'Standard_Case']; 
        
        
        for(Case c : createCasesRelatedToContact)
        {
            c.RecordTypeId = rt.Id;
            c.Processing_Number__c = newOrders[0].User_Order_ID__c;
        }
        update createCasesRelatedToContact;
    }

  static testMethod void IADHighlightsPanelPORCasesControllerTest() 
  {
    setupData();

    PageReference pageRef = Page.IADHighlightsPanelPOROpenCasesPage;
    pageRef.getParameters().put('id', String.valueOf(newContact.Id));
    Test.setCurrentPage(pageRef);
    IADHighlightsPanelPOROpenCasesController thecontroller = new IADHighlightsPanelPOROpenCasesController();
    thecontroller.refreshPage();

    system.assertEquals(SIZE, thecontroller.problemCases.size(), 'Write number of cases should have been displayed');


  }
}