src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processing_Number__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <label>User Order ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IAD_Case_Status_Reasons__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business Services</fullName>
                </value>
                <value>
                    <fullName>Intellectual Property</fullName>
                </value>
                <value>
                    <fullName>Personal Services</fullName>
                </value>
                <value>
                    <fullName>Attorney Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Problem</fullName>
                </value>
                <value>
                    <fullName>Service Inquiry</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_Reason__c</fullName>
        <label>Status Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>--None--</fullName>
                </value>
                <value>
                    <fullName>Assigned for Customer Outreach</fullName>
                </value>
                <value>
                    <fullName>LZ Research Required</fullName>
                </value>
                <value>
                    <fullName>Assigned for Resolution</fullName>
                </value>
                <value>
                    <fullName>Auto Closed (Timeout) - Unresolved</fullName>
                </value>
                <value>
                    <fullName>Customer Submitting Materials</fullName>
                </value>
                <value>
                    <fullName>Customer didn&apos;t have needed info</fullName>
                </value>
                <value>
                    <fullName>Customer not reached (VM/disconnect)</fullName>
                </value>
                <value>
                    <fullName>Email Sent, Pending Response</fullName>
                </value>
                <value>
                    <fullName>Customer Submitting Revision</fullName>
                </value>
                <value>
                    <fullName>Issue Resolved (non Proofer resolution)</fullName>
                </value>
                <value>
                    <fullName>Revision Placed for Customer</fullName>
                </value>
                <value>
                    <fullName>Proofer Updated</fullName>
                </value>
                <value>
                    <fullName>Proceeding As Is/No Update Required</fullName>
                </value>
                <value>
                    <fullName>Order Cancelled</fullName>
                </value>
                <value>
                    <fullName>Customer-Requested Item Complete</fullName>
                </value>
                <value>
                    <fullName>No Order Problem (Case created in error)</fullName>
                </value>
                <value>
                    <fullName>Revision Placed on LZ.com</fullName>
                </value>
                <value>
                    <fullName>Revision Placed (after 7 day closure)</fullName>
                </value>
                <value>
                    <fullName>LZML</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Social Media</fullName>
                </value>
                <value>
                    <fullName>BBB</fullName>
                </value>
                <value>
                    <fullName>Escalated Customer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>LZ Working on Case</fullName>
                </value>
                <value>
                    <fullName>Waiting on Customer</fullName>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IAD Case Status Reasons</label>
    <nameField>
        <displayFormat>SR - {000}</displayFormat>
        <label>IAD Case Status Reasons Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IAD Case Status Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_State__c</fullName>
        <label>Contact State</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderID__c</fullName>
        <externalId>true</externalId>
        <label>OrderID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Show process name of the base product on the order</description>
        <formula>Base_Product__r.Process__r.Name</formula>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <description>matching the fkUserOrder field of OrderItem table in lzdata</description>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Relationship_Type__c.object
<CustomObject>
    <description>matching RelationshipType table in LZData</description>
    <label>Relationship Type</label>
    <nameField>
        <label>Relationship Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/IADUpdateCaseControllerTest.cls
@isTest
public with sharing class IADUpdateCaseControllerTest {
    
    final static String RESERACHING = 'Researching';
    final static String DESCRIPTION = 'Test Description';
    final static String OPEN = 'Open';
    final static String PROBLEM = 'Problem';
    final static String BBB = 'BBB';
    final static String ASSIGNED_FOR_CUSTOMER_OUTREACH = 'Assigned for Customer Outreach';

    static testMethod void testUpdateCase()
    {
            Account testAccount = TestUtils.createAccounts(1, 'accName', true)[0];

            Contact testContact = TestUtils.createContacts(1, 'lname', testAccount.Id, true)[0];
            
            Order__c testOrder = TestUtils.createOrders(1, null , false)[0];
            testOrder.OrderID__c = '43534534';
            testOrder.Contact_Name__c = 'Joe Montana';
            testOrder.Contact_State__c = 'CA';
            testOrder.Contact__c = testContact.Id;
            insert testOrder;

            Id relationshipTypeId = TestUtils.createRelationshipTypesTypes(1 , 'Process', true)[0].Id;
            
            Product2 testProduct = TestUtils.createProducts(1 , 'Test Product', false)[0];
            testProduct.Relationship_Type__c = relationshipTypeId;
            insert testProduct;

            Order_Item__c testOrderItem = TestUtils.createOrderItems(1 , testOrder.Id ,  false)[0];
            testOrderItem.User_Order_ID__c = '123456789';
            testOrderItem.Product__c = testProduct.Id;
            insert testOrderItem;

            List<Case> testCases = TestUtils.createCases(2, true);

            Case testCase1 = testCases[0];
            testCase1.ContactId = testContact.Id;

            Case testCase2 = testCases[1];
            testCase2.ContactId = testContact.Id;

            update new List<Case>{testCase1,testCase2};

            ApexPages.StandardController sc = new ApexPages.StandardController(testCase1);
            IADUpdateCaseController theController = new IADUpdateCaseController(sc);
            //theController.hideModal();
            //theController.setMsg();
            PageReference pageRef = Page.IADUpdateCasePage;
            pageRef.getParameters().put('id', String.valueOf(testCase1.Id));
            Test.setCurrentPage(pageRef);

            Test.startTest(); 
                theController.theCase.Processing_Number__c = '123456789';
                theController.description = DESCRIPTION;
                theController.theCase.Subject = 'Test create Case';
                theController.selectedtype = PROBLEM;
                theController.selectedStatus = OPEN;
                theController.selectedStatusReason = BBB;
                theController.selectedProduct = 'Business Services';
                theController.updateCase();
            Test.stopTest();

            List<Case> updatedCases  = [SELECT Id , Status , Description  FROM Case WHERE Id =:testCase1.Id];
            System.assertEquals(OPEN , updatedCases[0].Status , 'Right status should have been populated');
           
           
    }
    
    static testMethod void testStatusReasons()
    {
        Account testAccount = TestUtils.createAccounts(1 , 'Test Account' , true)[0];
        Contact testContact = TestUtils.createContacts(1 , 'Test Contact' , testAccount.Id , true)[0];
        List<Case> testCases = TestUtils.createCases(2, true);
        Case testCase1 = testCases[0];
        
        IAD_Case_Status_Reasons__c newStatusReason = new IAD_Case_Status_Reasons__c();
        newStatusReason.Product__c = 'Business Services';
        newStatusReason.Record_Type__c = PROBLEM;
        newStatusReason.Status__c = 'LZ Working on Case';
        newStatusReason.Status_Reason__c = ASSIGNED_FOR_CUSTOMER_OUTREACH;
        insert newStatusReason;

        ApexPages.StandardController sc = new ApexPages.StandardController(testCase1);
        IADUpdateCaseController theController = new IADUpdateCaseController(sc);
        PageReference pageRef = Page.IADUpdateCasePage;
        pageRef.getParameters().put('id', String.valueOf(testContact.Id));
        Test.setCurrentPage(pageRef);

        Test.startTest(); 
            theController.getproducts();
            theController.getTypes();
            theController.getStatus();
            theController.selectedtype = PROBLEM;
            theController.selectedStatus = 'LZ Working on Case';
            theController.selectedProduct = 'Business Services';
        Test.stopTest();
theController.dismiss();
theController.closePopup();
        
        System.assertEquals(ASSIGNED_FOR_CUSTOMER_OUTREACH, theController.getStatusReasons()[0].getValue(), 'Right status reason should have been populated');
    }
}