src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Number_Inbound_Emails__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Count of the number of inbound emails on a case</description>
        <label>Number Inbound Emails</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <description>Queue field</description>
        <label>Queue</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Biz 501c3</fullName>
                </value>
                <value>
                    <fullName>Biz Alt Names</fullName>
                </value>
                <value>
                    <fullName>Biz Escalation</fullName>
                </value>
                <value>
                    <fullName>Biz HA Sweeps</fullName>
                </value>
                <value>
                    <fullName>Biz QC Approval</fullName>
                </value>
                <value>
                    <fullName>BIZ RA SOP</fullName>
                </value>
                <value>
                    <fullName>CC Biz</fullName>
                </value>
                <value>
                    <fullName>CC IP</fullName>
                </value>
                <value>
                    <fullName>CC Manager Call-Back</fullName>
                </value>
                <value>
                    <fullName>CC Mock Launch Requests</fullName>
                </value>
                <value>
                    <fullName>CC PS</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Billing Updates</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Materials</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Order Updates</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Post Filing</fullName>
                </value>
                <value>
                    <fullName>IP Copyrights</fullName>
                </value>
                <value>
                    <fullName>IP Partners and Firms</fullName>
                </value>
                <value>
                    <fullName>IP Patent Billing Updates</fullName>
                </value>
                <value>
                    <fullName>IP Patent Drawings</fullName>
                </value>
                <value>
                    <fullName>IP Patent Materials</fullName>
                </value>
                <value>
                    <fullName>IP Patent Order Updates</fullName>
                </value>
                <value>
                    <fullName>IP Patent Search Approval</fullName>
                </value>
                <value>
                    <fullName>IP Patents</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Billing Updates</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Monitoring</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Order Updates</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Search</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Search Approvals</fullName>
                </value>
                <value>
                    <fullName>IP Trademarks</fullName>
                </value>
                <value>
                    <fullName>IP Trademarks Goods and Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>CC_Task</fullName>
        <active>true</active>
        <label>CC Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EmailIncomingCreateTask.cls
public with sharing class EmailIncomingCreateTask 
{
    public static final String SOBJECT_TYPE = 'Task';
    public static final String RECORDTYPE_DEVNAME = 'CC_Task';
    
    public static void createTask(List<EmailMessage> newEmail)
    {
        List<Task> createNewTaskList = new List<Task>();
        List<case> casesToUpdate = new List<Case>();
        Set<Id> caseId = new Set<Id>();
        try
        {
            for(EmailMessage email : newEmail)
            {
                caseId.add(email.ParentId);
            }
            
            Map<Id, Case> caseMap = new Map<Id, Case>([SELECT Id, Queue__c, Number_Inbound_Emails__c FROM Case WHERE Id =: caseId]);
            String emailBody = '';
            for(EmailMessage email : newEmail)
            {
                if(email.Incoming == true)
                {
                    if(email.HtmlBody != null)
                    {
                        emailBody = email.HtmlBody;
                    }
                    else if(email.TextBody != null)
                    {
                        emailBody = email.TextBody;
                    }
                    createNewTaskList = EmailFunction.createTask(email.Subject, emailBody, null, null, null, null, null, null, 'Incoming', null, 
                                         caseMap.get(email.ParentId).Queue__c, 'New', email.ParentId, null, false);

                    Case caseToUpdate = new Case(Id = email.ParentId);
                    caseToUpdate.Number_Inbound_Emails__c = caseMap.get(email.ParentId).Number_Inbound_Emails__c + 1;
                    casesToUpdate.add(caseToUpdate);
                }
                
            }
            insert createNewTaskList;
            update casesToUpdate;
        }
        catch(Exception ex)
        {
            System.debug('>>>>> EmailIncomingCreateTask Error Message : '+ex.getMessage());
        }
    }
}