src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processing_Number__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <description>Complete list of products from Order Manager. May contain Legacy products.</description>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Line__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>501(c)3 Preparation</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Annual Reports</fullName>
                </value>
                <value>
                    <fullName>Attorney Consultation Requests</fullName>
                </value>
                <value>
                    <fullName>Attorney Prepared Provisional Patent</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Business Advantage Pro Standalone</fullName>
                </value>
                <value>
                    <fullName>Bylaws &amp; Resolutions</fullName>
                </value>
                <value>
                    <fullName>Certificate of Good Standing</fullName>
                </value>
                <value>
                    <fullName>Certified Copies</fullName>
                </value>
                <value>
                    <fullName>Compliance Calendar</fullName>
                </value>
                <value>
                    <fullName>Compliance Calendar Renewal</fullName>
                </value>
                <value>
                    <fullName>Consultation Subscription</fullName>
                </value>
                <value>
                    <fullName>Consultation Subscription Renewal</fullName>
                </value>
                <value>
                    <fullName>Conversion</fullName>
                </value>
                <value>
                    <fullName>Copyright</fullName>
                </value>
                <value>
                    <fullName>Corporate Dissolution</fullName>
                </value>
                <value>
                    <fullName>Corporate Minutes</fullName>
                </value>
                <value>
                    <fullName>DBA</fullName>
                </value>
                <value>
                    <fullName>Design Patent</fullName>
                </value>
                <value>
                    <fullName>Divorce</fullName>
                </value>
                <value>
                    <fullName>EIN Obtainment</fullName>
                </value>
                <value>
                    <fullName>Entity Name Availability Check</fullName>
                </value>
                <value>
                    <fullName>Entity Name Reservation</fullName>
                </value>
                <value>
                    <fullName>Foreign Qualification</fullName>
                </value>
                <value>
                    <fullName>Forms Subscription</fullName>
                </value>
                <value>
                    <fullName>Forms Subscription Renewal</fullName>
                </value>
                <value>
                    <fullName>General Partnership Agreement</fullName>
                </value>
                <value>
                    <fullName>Immigration - Citizenship</fullName>
                </value>
                <value>
                    <fullName>Immigration - Greencards</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>Order Manager Product Categories</description>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attorney Services</fullName>
                </value>
                <value>
                    <fullName>Business Formations</fullName>
                </value>
                <value>
                    <fullName>Intellectual Property</fullName>
                </value>
                <value>
                    <fullName>Legal Forms</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Personal Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_for_Contact_new__c</fullName>
        <label>CC Reason for Contact</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Add/Purchase</fullName>
                    <color>#CC0000</color>
                    <label>Add/Purchase</label>
                </value>
                <value>
                    <fullName>Cancel/Remove</fullName>
                    <color>#FF6600</color>
                    <label>Cancel/Remove</label>
                </value>
                <value>
                    <fullName>Error/Problem</fullName>
                    <color>#FFCC33</color>
                    <label>Error/Problem</label>
                </value>
                <value>
                    <fullName>Information Request</fullName>
                    <color>#33CC00</color>
                    <label>Information Request</label>
                </value>
                <value>
                    <fullName>Product Question</fullName>
                    <color>#00CCCC</color>
                    <label>Product Question</label>
                </value>
                <value>
                    <fullName>Request Action</fullName>
                    <color>#6600CC</color>
                    <label>Request Action</label>
                </value>
                <value>
                    <fullName>Update Order</fullName>
                    <color>#CC33CC</color>
                    <label>Update Order</label>
                </value>
                <value>
                    <fullName>Technical Issues</fullName>
                    <color>#F96FB7</color>
                    <label>Technical Issues</label>
                </value>
                <value>
                    <fullName>Other Reason</fullName>
                    <color>#666666</color>
                    <label>Other Reason</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_Reasons__c</fullName>
        <label>Status Reasons</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned for Customer Outreach</fullName>
                </value>
                <value>
                    <fullName>LZ Research Required</fullName>
                </value>
                <value>
                    <fullName>Assigned for Resolution</fullName>
                </value>
                <value>
                    <fullName>Updated by Customer</fullName>
                </value>
                <value>
                    <fullName>Customer Submitting Revision</fullName>
                </value>
                <value>
                    <fullName>Customer Submitting Materials</fullName>
                </value>
                <value>
                    <fullName>Customer didn&apos;t have needed info</fullName>
                </value>
                <value>
                    <fullName>Call attempted - Customer not reached (VM/disconnect)</fullName>
                </value>
                <value>
                    <fullName>Email Sent, Pending Response</fullName>
                </value>
                <value>
                    <fullName>LZM</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Social Media</fullName>
                </value>
                <value>
                    <fullName>BBB</fullName>
                </value>
                <value>
                    <fullName>Escalated Customer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Issue Resolved (non Proofer resolution)</fullName>
                </value>
                <value>
                    <fullName>Revision Placed for Customer</fullName>
                </value>
                <value>
                    <fullName>Proofer Updated</fullName>
                </value>
                <value>
                    <fullName>Customer Proceeding As Is/No Update Required</fullName>
                </value>
                <value>
                    <fullName>Order Cancelled</fullName>
                </value>
                <value>
                    <fullName>Customer-Requested Item Complete</fullName>
                </value>
                <value>
                    <fullName>No Order Problem (Case Created in Error)</fullName>
                </value>
                <value>
                    <fullName>Auto Closed (Timeout) - Unresolved</fullName>
                </value>
                <value>
                    <fullName>Revision placed on LZ.com</fullName>
                </value>
                <value>
                    <fullName>Revision placed on LZ.com (after 7 day closure)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>created_date__c</fullName>
        <formula>DATEVALUE(CreatedDate)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>created date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Problem_Case</fullName>
        <active>true</active>
        <businessProcess>LegalZoom Standard Support Process</businessProcess>
        <description>Standard POR Case</description>
        <label>Standard Problem Order</label>
    </recordTypes>
    <recordTypes>
        <fullName>Standard_Case</fullName>
        <active>true</active>
        <businessProcess>LegalZoom Standard Support Process</businessProcess>
        <description>Standard Customer-Facing Case</description>
        <label>Standard Service Inquiry</label>
    </recordTypes>
    <recordTypes>
        <fullName>Web_Case</fullName>
        <active>true</active>
        <businessProcess>LegalZoom Standard Support Process</businessProcess>
        <description>Case Submitted via the Web</description>
        <label>Web Case</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact_State__c</fullName>
        <label>Contact State</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <formula>Base_Product__r.Product_Line__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Base_Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Show process name of the base product on the order</description>
        <formula>Base_Product__r.Process__r.Name</formula>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_of_Formation__c</fullName>
        <label>State of Formation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <description>Product Name at the time of the order item is created.</description>
        <inlineHelpText>Product Name at the time of the order item is created.</inlineHelpText>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <description>matching the fkUserOrder field of OrderItem table in lzdata</description>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Line</label>
        <referenceTo>Product_Line__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product_Line__c.object
<CustomObject>
    <description>matching ProductLine lookup table in LZData</description>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/IADContactCaseHistoryPanelController.cls
public with sharing class IADContactCaseHistoryPanelController
{
    public String theId{get;set;}
    public List<String> processingNumbers = new List<String>();
    public List<CaseWrapper> allCases{get;set;}
    public Boolean hasOpenCases{get;set;}
    public Map<String,String> processingNumberToOrderItemLabel;
    public String caseIcon{get;set;}
    public String checkIcon{get;set;}

    public IADContactCaseHistoryPanelController () 
    {
        theId = ApexPages.currentPage().getParameters().get('id');
        processingNumberToOrderItemLabel = new Map<String,String>();
            
        caseIcon = IADSGVIconStrings.caseIcon;
        checkIcon= IADSGVIconStrings.checkIcon;

        getAllCases();
        
    }
    
    public void getAllCases()
    {
            
        try
        {
            allCases = new List<CaseWrapper>();
            if(theId != null && theId != '')
            {
               List<Case> caseObjects = new List<Case>();
               for(Case theCase : [SELECT ID,Order_Exception__c, Processing_Number__c , created_date__c,Order_Exception__r.Exception_Type__c, CreatedDate, Reason_for_Contact_new__c, Subject, Status, Status_Reasons__c, CaseNumber, Product__c, Product2__c, Product_Line__c  FROM Case WHERE ContactId = :theId
                                    AND ((RecordTypeId = : ProblemOrderRoutingService.developerNameToRecordTypeIds.get('Standard_Case'))
                                      OR (RecordTypeId = : ProblemOrderRoutingService.developerNameToRecordTypeIds.get('Web_Case'))
                                      OR (Status = 'Closed' AND RecordTypeId = : ProblemOrderRoutingService.developerNameToRecordTypeIds.get('Problem_Case')) OR (Order_Exception__c!=null AND RecordTypeId = : ProblemOrderRoutingService.developerNameToRecordTypeIds.get('Problem_Case') )) ORDER BY LastModifiedDate DESC limit 5])
               {
                   caseObjects.add(theCase);
                   if(theCase.Processing_Number__c != null && theCase.Processing_number__c != '')
                   {
                       processingNumbers.add(theCase.Processing_Number__c);
                   }
               }
               if(!processingNumbers.isEmpty())
               {
                   for(Order_Item__c theOrderItem : [SELECT ID, User_Order_ID__c , Product__r.Name , Order__r.Contact_State__c , Order__r.State_of_Formation__c , Product_Name__c FROM Order_Item__c Where User_Order_ID__c IN: processingNumbers])// AND Product__r.Name IN: ])
                   {
                       String state = theOrderItem.Order__r.State_of_Formation__c==null?'':'-'+theOrderItem.Order__r.State_of_Formation__c;
                       String orderItemLabel = theOrderItem.Product_Name__c +'('+theOrderItem.User_Order_ID__c+')' + state;
                       processingNumberToOrderItemLabel.put(theOrderItem.User_Order_ID__c, orderItemLabel);
                   }

               }
                for(Case theCase : caseObjects)
                {
                    CaseWrapper theWrapper = new CaseWrapper(theCase , processingNumberToOrderItemLabel.get(theCase.Processing_Number__c));
                    allCases.add(theWrapper);
                }


            }
            hasOpenCases = false;
            if(!allCases.isEmpty())
                hasOpenCases = true;
        }
        catch(Exception theException)
        {
            if(UtilityLibrary.sendEmail)
                SendExceptionEmail.sendExceptionEmail(theException , 'IAD Exception');
        }

    }
    
    public PageReference refreshPage()
    {
        getAllCases();
        return null;
    }
    
  
    public class CaseWrapper
    {
        public Case theCase{get;set;}
        public String theOrderItemLabel{get;set;}
        
        public CaseWrapper(Case tCase , String orderItemLabel)
        {
            theCase = tCase;
            if(orderItemLabel != null && orderItemLabel != '')
                theOrderItemLabel = orderItemLabel;
        }
    }
   
    
}