src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Hours_Since_Creation__c</fullName>
        <formula>FLOOR((NOW() -   CreatedDate)*24)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hours Since Creation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>POR_Email_Status__c</fullName>
        <label>POR Email Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st Email Sent</fullName>
                </value>
                <value>
                    <fullName>2nd Email Sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <description>Complete list of products from Order Manager. May contain Legacy products.</description>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Line__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>501(c)3 Preparation</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Annual Reports</fullName>
                </value>
                <value>
                    <fullName>Attorney Consultation Requests</fullName>
                </value>
                <value>
                    <fullName>Attorney Prepared Provisional Patent</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Business Advantage Pro Standalone</fullName>
                </value>
                <value>
                    <fullName>Bylaws &amp; Resolutions</fullName>
                </value>
                <value>
                    <fullName>Certificate of Good Standing</fullName>
                </value>
                <value>
                    <fullName>Certified Copies</fullName>
                </value>
                <value>
                    <fullName>Compliance Calendar</fullName>
                </value>
                <value>
                    <fullName>Compliance Calendar Renewal</fullName>
                </value>
                <value>
                    <fullName>Consultation Subscription</fullName>
                </value>
                <value>
                    <fullName>Consultation Subscription Renewal</fullName>
                </value>
                <value>
                    <fullName>Conversion</fullName>
                </value>
                <value>
                    <fullName>Copyright</fullName>
                </value>
                <value>
                    <fullName>Corporate Dissolution</fullName>
                </value>
                <value>
                    <fullName>Corporate Minutes</fullName>
                </value>
                <value>
                    <fullName>DBA</fullName>
                </value>
                <value>
                    <fullName>Design Patent</fullName>
                </value>
                <value>
                    <fullName>Divorce</fullName>
                </value>
                <value>
                    <fullName>EIN Obtainment</fullName>
                </value>
                <value>
                    <fullName>Entity Name Availability Check</fullName>
                </value>
                <value>
                    <fullName>Entity Name Reservation</fullName>
                </value>
                <value>
                    <fullName>Foreign Qualification</fullName>
                </value>
                <value>
                    <fullName>Forms Subscription</fullName>
                </value>
                <value>
                    <fullName>Forms Subscription Renewal</fullName>
                </value>
                <value>
                    <fullName>General Partnership Agreement</fullName>
                </value>
                <value>
                    <fullName>Immigration - Citizenship</fullName>
                </value>
                <value>
                    <fullName>Immigration - Greencards</fullName>
                </value>
                <value>
                    <fullName>Power of Attorney</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Problem_Case</fullName>
        <active>true</active>
        <businessProcess>LegalZoom Standard Support Process</businessProcess>
        <description>Standard POR Case</description>
        <label>Standard Problem Order</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/POR_case_routing_queues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Map of Product to Queue Map for case creation when the a Problem order is created by DI.</description>
    <fields>
        <fullName>X2nd_Email_hours__c</fullName>
        <label>2nd Email hours</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>POR Case Routing Queues</label>
</CustomObject>

src/classes/POR2DayEmailBatch.cls
global class POR2DayEmailBatch implements Database.Batchable<sObject> {

    String query;
    String STATUS_NEW = 'New';
    String CLOSED = 'Closed';
    String UPDATED_BY_CUST = 'Updated by Customer';
    String RESEARCHING = 'Researching';
    String WAIT_FOR_CUST = 'Waiting on Customer';
    String FIRST_EMAIL = '1st Email Sent';
    String SECOND_EMAIL = '2nd Email Sent';
    final String PROBLEM_CASE_RECORD_TYPE = 'Problem_Case';
    Integer hoursFor2ndEmail = Integer.ValueOf(POR_case_routing_queues__c.getInstance('Power of Attorney').X2nd_Email_hours__c);

    global POR2DayEmailBatch()
    {
        query = 'SELECT Id , Product2__c FROM Case WHERE (Status =: STATUS_NEW) AND'; 
        query = query + ' POR_Email_Status__c = :FIRST_EMAIL AND POR_Email_Status__c != :SECOND_EMAIL AND '; 
        query = query + ' Hours_Since_Creation__C >= :hoursFor2ndEmail AND RecordType.DeveloperName = :PROBLEM_CASE_RECORD_TYPE';
    }

    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Case> scope)
    {
        List<Case> casesToUpdate = new List<Case>();
        for(Case theCase : scope)
        {
            theCase.POR_Email_Status__c = SECOND_EMAIL;
            casesToUpdate.add(theCase);
        }
        try
        {
            POREmailSender emailSender = new POREmailSender();
            emailSender.sendEmailsToCustomer(scope);
            system.debug(casesToUpdate);
            Update casesToUpdate;
        }
        catch(DMLException exp)
        {
            SendExceptionEmail.sendDMLExceptionEmail(exp, ProblemOrderConstants.PROBLEM_CASE_ERROR_MESSAGE);
        }
        
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }

}