src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer_Login__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Login</label>
        <referenceTo>Customer_Login__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateTime_Problem_Identified__c</fullName>
        <label>Date/Time Problem Identified</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <description>Order Manager number. Cloud Trigger coded this field to open a new window and look up the order in order manager.</description>
        <externalId>true</externalId>
        <label>Order Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POR_Email_Status__c</fullName>
        <label>POR Email Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st Email Sent</fullName>
                </value>
                <value>
                    <fullName>2nd Email Sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Problem_Order_Type__c</fullName>
        <label>Problem Order Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processing_Number__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <description>Complete list of products from Order Manager. May contain Legacy products.</description>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Line__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>501(c)3 Preparation</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Annual Reports</fullName>
                </value>
                <value>
                    <fullName>Attorney Consultation Requests</fullName>
                </value>
                <value>
                    <fullName>Attorney Prepared Provisional Patent</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Business Advantage Pro Standalone</fullName>
                </value>
                <value>
                    <fullName>Bylaws &amp; Resolutions</fullName>
                </value>
                <value>
                    <fullName>Certificate of Good Standing</fullName>
                </value>
                <value>
                    <fullName>Certified Copies</fullName>
                </value>
                <value>
                    <fullName>Compliance Calendar</fullName>
                </value>
                <value>
                    <fullName>Compliance Calendar Renewal</fullName>
                </value>
                <value>
                    <fullName>Consultation Subscription</fullName>
                </value>
                <value>
                    <fullName>Consultation Subscription Renewal</fullName>
                </value>
                <value>
                    <fullName>Conversion</fullName>
                </value>
                <value>
                    <fullName>Copyright</fullName>
                </value>
                <value>
                    <fullName>Corporate Dissolution</fullName>
                </value>
                <value>
                    <fullName>Corporate Minutes</fullName>
                </value>
                <value>
                    <fullName>DBA</fullName>
                </value>
                <value>
                    <fullName>Design Patent</fullName>
                </value>
                <value>
                    <fullName>Divorce</fullName>
                </value>
                <value>
                    <fullName>EIN Obtainment</fullName>
                </value>
                <value>
                    <fullName>Entity Name Availability Check</fullName>
                </value>
                <value>
                    <fullName>Entity Name Reservation</fullName>
                </value>
                <value>
                    <fullName>Foreign Qualification</fullName>
                </value>
                <value>
                    <fullName>Forms Subscription</fullName>
                </value>
                <value>
                    <fullName>Forms Subscription Renewal</fullName>
                </value>
                <value>
                    <fullName>General Partnership Agreement</fullName>
                </value>
                <value>
                    <fullName>Immigration - Citizenship</fullName>
                </value>
                <value>
                    <fullName>Immigration - Greencards</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <description>Queue field</description>
        <label>Queue</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Biz 501c3</fullName>
                </value>
                <value>
                    <fullName>Biz Alt Names</fullName>
                </value>
                <value>
                    <fullName>Biz Escalation</fullName>
                </value>
                <value>
                    <fullName>Biz HA Sweeps</fullName>
                </value>
                <value>
                    <fullName>Biz QC Approval</fullName>
                </value>
                <value>
                    <fullName>BIZ RA SOP</fullName>
                </value>
                <value>
                    <fullName>CC Biz</fullName>
                </value>
                <value>
                    <fullName>CC IP</fullName>
                </value>
                <value>
                    <fullName>CC Manager Call-Back</fullName>
                </value>
                <value>
                    <fullName>CC Mock Launch Requests</fullName>
                </value>
                <value>
                    <fullName>CC PS</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Billing Updates</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Materials</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Order Updates</fullName>
                </value>
                <value>
                    <fullName>IP Copyright Post Filing</fullName>
                </value>
                <value>
                    <fullName>IP Copyrights</fullName>
                </value>
                <value>
                    <fullName>IP Partners and Firms</fullName>
                </value>
                <value>
                    <fullName>IP Patent Billing Updates</fullName>
                </value>
                <value>
                    <fullName>IP Patent Drawings</fullName>
                </value>
                <value>
                    <fullName>IP Patent Materials</fullName>
                </value>
                <value>
                    <fullName>IP Patent Order Updates</fullName>
                </value>
                <value>
                    <fullName>IP Patent Search Approval</fullName>
                </value>
                <value>
                    <fullName>IP Patents</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Billing Updates</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Monitoring</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Order Updates</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Search</fullName>
                </value>
                <value>
                    <fullName>IP Trademark Search Approvals</fullName>
                </value>
                <value>
                    <fullName>IP Trademarks</fullName>
                </value>
                <value>
                    <fullName>IP Trademarks Goods and Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Problem_Case</fullName>
        <active>true</active>
        <businessProcess>LegalZoom Standard Support Process</businessProcess>
        <description>Standard POR Case</description>
        <label>Standard Problem Order</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Base_Product_Text__c</fullName>
        <formula>Base_Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Base Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_State__c</fullName>
        <label>Contact State</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Login__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Login</label>
        <referenceTo>Customer_Login__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderID__c</fullName>
        <externalId>true</externalId>
        <label>OrderID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Show process name of the base product on the order</description>
        <formula>Base_Product__r.Process__r.Name</formula>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type_Text__c</fullName>
        <formula>Relationship_Type__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Relationship Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <description>matching the fkUserOrder field of OrderItem table in lzdata</description>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/POR_case_routing_queues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Map of Product to Queue Map for case creation when the a Problem order is created by DI.</description>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <description>Stores the API name of Queue</description>
        <label>Queue Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>POR Case Routing Queues</label>
</CustomObject>

src/classes/ProblemOrderRoutingService.cls
public without Sharing class ProblemOrderRoutingService
{
    public static Map<Id,Order__c> orderIdToOrderMap = new Map<Id,Order__c>();
    public static  Map<String,String> processingNumberToProduct = new Map<String,String>();
    public static Map<String,POR_case_routing_queues__c> productToPORInfo
    {
        get
        {
            if(productToPORInfo == null) 
            {
                productToPORInfo = new Map<String,POR_case_routing_queues__c>();
                for (POR_case_routing_queues__c productToQueueMap : [SELECT Name , Queue_Name__c FROM POR_case_routing_queues__c])
                {
                    productToPORInfo.put(productToQueueMap.Name,productToQueueMap);
                }
            }
            return productToPORInfo;
        } 
        set;
    }

    public static Map<String,Id> developerNameToRecordTypeIds
    { 
        get
        {
            if(developerNameToRecordTypeIds == null)
            {
                List<RecordType> recordTypes = [SELECT Id,Name,DeveloperName FROM RecordType WHERE sObjectType = 'Case'];    
                developerNameToRecordTypeIds = new Map<String,Id>();
                if(!recordTypes.isEmpty())
                {
                    for(RecordType theRecordType : recordTypes)
                    {
                        developerNameToRecordTypeIds.put(theRecordType.DeveloperName , theRecordType.Id);
                    }
                }
            }
            
            return developerNameToRecordTypeIds;
        }
        set;
    }


    public static void createCaseForProblemOrder(List<Task> tasksWithProblem)
    {
        List<Case> problemCasesToInsert = new List<Case>();
        Set<Id> orderIds = new Set<Id>();
        Set<String> processingNumbers = new Set<String>();
        List<Order_Item__c> orderItems = new List<Order_Item__c>();

        for(Task theTask : tasksWithProblem)
        {
            orderIds.add(theTask.WhatId);
            if(theTask.User_Order_ID__c != null || theTask.User_Order_ID__c != '')
                processingNumbers.add(theTask.User_Order_ID__c); 
        }
        system.debug(processingNumbers);
        if(!orderIds.isEmpty())
            orderIdToOrderMap = new Map<Id,Order__c>([Select Id, Name, Base_Product_Text__c ,Contact__c, User_Order_ID__c , Contact_State__c , Customer_Login__c , OrderID__c From Order__c Where Id IN: orderIds]);

        if(!processingNumbers.isEmpty())
            for(Order_Item__c theOrderItem : [SELECT ID, User_Order_ID__c , Product__r.Name FROM Order_Item__c Where User_Order_ID__c IN: processingNumbers])// AND Product__r.Name IN: ])
            {
                processingNumberToProduct.put(theOrderItem.User_Order_ID__c, theOrderItem.Product__r.Name);
            }
        system.debug(processingNumberToProduct);
        for(Task theTask : tasksWithProblem)
        {
            problemCasesToInsert.add(createProblemCase(theTask));
        }
        if(!problemCasesToInsert.isEmpty())
            try
            {
                insert problemCasesToInsert;
                POREmailSender emailSender = new POREmailSender();
                emailSender.sendEmailsToCustomer(problemCasesToInsert);

            }
            catch(DmlException exp)
            {
                system.debug(exp+'exception');
                SendExceptionEmail.sendDMLExceptionEmail(exp, ProblemOrderConstants.PROBLEM_CASE_ERROR_MESSAGE);
            }
    }

    public static Case createProblemCase(Task theTask)
    {

        Case newCase = new Case();
            Order__c relatedOrder = orderIdToOrderMap.get(theTask.WhatId);
            newCase.Order__c = theTask.WhatId;
            newCase.Order_Number__c = relatedOrder.OrderID__c;
            newCase.Product__c = processingNumberToProduct.get(theTask.User_Order_ID__c); //from map
            newCase.Product2__c = ProblemOrderConstants.POA; // hardcode
            newCase.Problem_Order_Type__c = theTask.Action_type__c;
            newCase.ContactId = relatedOrder.Contact__c;
            newCase.Customer_Login__c = relatedOrder.Customer_Login__c;
            newCase.RecordTypeId =  developerNameToRecordTypeIds.get(ProblemOrderConstants.PROBLEM_CASE_RECORD_TYPE);
            newCase.Subject = theTask.User_Order_ID__c +'-'+processingNumberToProduct.get(theTask.User_Order_ID__c)+'-'+relatedOrder.Contact_State__c;
            newCase.Processing_Number__c = theTask.User_Order_ID__c; 
            newCase.DateTime_Problem_Identified__c= theTask.Datetime_Created_External_System__c;
            newCase.POR_Email_Status__c = ProblemOrderConstants.FIRST_EMAIL;
            if(productToPORInfo.containsKey(ProblemOrderConstants.POA))
                newCase.Queue__c = productToPORInfo.get(ProblemOrderConstants.POA).Queue_Name__c;
        return newCase;
    }

    public static void closeRelatedOpenCasesForRevisedOrder(List<Order_Item__c> newOrderItems)
    {
        Set<String> processingNummbers = new Set<String>();
        List<Case> casesToClose = new List<Case>();
        for(Order_Item__c theOrderItem : newOrderItems)
        {
            system.debug(theOrderItem.Relationship_Type_Text__c);
            system.debug(theOrderItem.Relationship_Type__c);
            if(theOrderItem.Relationship_Type_Text__c == ProblemOrderConstants.REVISION)
            {
                processingNummbers.add(theOrderItem.User_Order_ID__c);
            }
        }
        
        if(!processingNummbers.isEmpty())
            for(Case caseToClose : [Select Id, Processing_Number__c, Order_Exception__c, Status, Problem_Order_Resolution__c From Case Where Processing_Number__c In: processingNummbers AND  RecordTypeId = : developerNameToRecordTypeIds.get('Problem_Case')])
            {
                    caseToClose.Status = ProblemOrderConstants.CLOSED_STATUS;
                    if(caseToClose.Problem_Order_Resolution__c != ProblemOrderConstants.UNRESOLVED_CLOSED)
                        caseToClose.Problem_Order_Resolution__c = ProblemOrderConstants.REVISED_ORDER_RESOLUTION_REASON;
                    else if(caseToClose.Problem_Order_Resolution__c == ProblemOrderConstants.UNRESOLVED_CLOSED)
                            caseToClose.Problem_Order_Resolution__c = ProblemOrderConstants.REVISION_AFTER_7DAY_STATUS;
                if (caseToClose.Order_Exception__c == null) {
                    casesToClose.add(caseToClose); 
                }
                    
            }


        if(!casesToClose.isEmpty())
            try
            {
                Update casesToClose;
            }
            catch(DmlException exp)
            {
                SendExceptionEmail.sendDMLExceptionEmail(exp, 'Unable to Close cases for revised order.');
            }
    }

    public static void countNumberOfOutboundEmails(List<EmailMessage> newEmails)
    {
        system.debug(UserInfo.getName()+'Current User Name');
        List<Case> casesToUpdate = new List<Case>();
        Set<Id> caseIds = new Set<Id>();
        Map<Id,Integer> idToNoOfEmails = new Map<Id,Integer>();
        Map<Id,Integer> idToNoOfAutoEmails = new Map<Id,Integer>();
        for(EmailMessage theEmail : newEmails)
        {
           if(theEmail.Incoming == false)
           {
             caseIds.add(theEmail.ParentId);
             if(idToNoOfEmails.containsKey(theEmail.ParentId))
             {
                 idToNoOfEmails.put(theEmail.ParentId, idToNoOfEmails.get(theEmail.ParentId)+1);
             }
             else
             {
                 idToNoOfEmails.put(theEmail.ParentId,1);
             }
           }
           //if(theEmail.CreatedById == CampaignFutureHandler.integrationUser.Id || theEmail.CreatedById == TaskService.emailToCaseUser.Id)
           //removed the reference of integration user from CampaignFutureHandler class and used the Utility library instead: B-38758
           if(UtilityLibrary.allIntegrationUserIds.contains(theEmail.CreatedById) || theEmail.CreatedById == TaskService.emailToCaseUser.Id)
           {
                if(idToNoOfAutoEmails.containsKey(theEmail.ParentId))
                 {
                     idToNoOfAutoEmails.put(theEmail.ParentId, idToNoOfAutoEmails.get(theEmail.ParentId)+1);
                 }
                 else
                 {
                     idToNoOfAutoEmails.put(theEmail.ParentId,1);
                 }
           }
        }

        Map<Id,Case> caseIdToCase = new Map<Id,Case>();
        if(!caseIds.isEmpty())
        caseIdToCase = new Map<Id,Case>([Select Id, Total_Outbound_Emails__c , Total_Automatic_Outbound_Emails__c From Case Where Id IN :caseIds]);
        
        for(Case theCase : caseIdToCase.values())
        {
            //Total emails
            if(idToNoOfEmails.containsKey(theCase.Id))
            {
                if(theCase.Total_Outbound_Emails__c != null)
                    theCase.Total_Outbound_Emails__c = theCase.Total_Outbound_Emails__c + idToNoOfEmails.get(theCase.Id);
                else
                    theCase.Total_Outbound_Emails__c = idToNoOfEmails.get(theCase.Id);
            }

            //Total Automatic emails
            if(idToNoOfAutoEmails.containsKey(theCase.Id))
            {
                if(theCase.Total_Automatic_Outbound_Emails__c != null)
                    theCase.Total_Automatic_Outbound_Emails__c = theCase.Total_Automatic_Outbound_Emails__c + idToNoOfAutoEmails.get(theCase.Id);
                else
                    theCase.Total_Automatic_Outbound_Emails__c =  idToNoOfAutoEmails.get(theCase.Id);
            }

            casesToUpdate.add(theCase);
        }
        try
        {
            if(!casesToUpdate.isEmpty())
                Update casesToUpdate;
        }
        catch(DmlException exp)
        {
            SendExceptionEmail.sendDMLExceptionEmail(exp, 'Unable to Calculate total no of Outbound Emails on case.');
        }
    }

}