src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/g_ContactContainer.cls
global class g_ContactContainer {

	public Contact contact {get;set;} // contact for this wrapper
	public List<Order__c> order_results {get;set;} // search results
	public List<Order_Item__c> order_item_results {get;set;} // search results
	public List<Case> case_results {get;set;} //search results

	public Integer order_count {get;set;}
	public Integer order_item_count {get;set;}
	public Integer case_count {get;set;}
	
	public g_ContactContainer(Contact contactToWrap)
	{
		contact=contactToWrap;

		order_count=0;
		order_item_count=0;
		case_count=0;
		order_results=new List<Order__c>();
		order_item_results=new List<Order_Item__c>();
		case_results=new List<Case>();
	}
	
	public void updateCounts()
	{
		order_count = order_results.size() > 0 ? order_results.size(): 0;
		order_item_count = order_item_results.size()>0 ? order_item_results.size() : 0;
		case_count = case_results.size()>0 ? case_results.size() : 0;		
	}
}