src/objects/Compliance_Review__c.object
<CustomObject>
    <description>Represents a call listened to and reviewed by the Sales QA &amp; Compliance team</description>
    <fields>
        <fullName>Corrective_Plan_Outbound_Disclaimer__c</fullName>
        <label>Corrective Plan Outbound Disclosure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st Written</fullName>
                </value>
                <value>
                    <fullName>2nd Written</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Corrective_Plan_Start_Date__c</fullName>
        <label>Corrective Plan Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Corrective_Plan_Taxation__c</fullName>
        <label>Corrective Plan Taxation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Verbal</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>1st Written</fullName>
                </value>
                <value>
                    <fullName>2nd Written</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Corrective_Plan_UPL_Coaching__c</fullName>
        <label>Corrective Plan UPL Coaching</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Verbal</fullName>
                </value>
                <value>
                    <fullName>1st Written</fullName>
                </value>
                <value>
                    <fullName>2nd Written</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Corrective_Plan_UPL__c</fullName>
        <label>Corrective Plan UPL</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st Written</fullName>
                </value>
                <value>
                    <fullName>2nd Written</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cp_2nd_Contact_Disclaimer__c</fullName>
        <label>Cp 2nd Contact Disclosure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Verbal</fullName>
                </value>
                <value>
                    <fullName>1st Written</fullName>
                </value>
                <value>
                    <fullName>2nd Written</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LCP_2nd_Contact_Disclaime__c</fullName>
        <label>LCP 2nd Contact Disclosure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Verbal</fullName>
                </value>
                <value>
                    <fullName>1st Written</fullName>
                </value>
                <value>
                    <fullName>2nd Written</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LCP_Outbound_Disclaimer__c</fullName>
        <label>LCP Outbound Disclosure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st Written</fullName>
                </value>
                <value>
                    <fullName>2nd Written</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LCP_Taxation__c</fullName>
        <label>LCP Taxation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Verbal</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>1st Written</fullName>
                </value>
                <value>
                    <fullName>2nd Written</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LCP_UPL_Coaching__c</fullName>
        <label>LCP UPL Coaching</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Verbal</fullName>
                </value>
                <value>
                    <fullName>1st Written</fullName>
                </value>
                <value>
                    <fullName>2nd Written</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LCP_UPL__c</fullName>
        <label>LCP UPL</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st Written</fullName>
                </value>
                <value>
                    <fullName>2nd Written</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recorded_Call_ID__c</fullName>
        <externalId>true</externalId>
        <label>Recorded Call ID#</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Sales Representative that is being reviewed</description>
        <inlineHelpText>The Sales Representative that is being reviewed</inlineHelpText>
        <label>Rep Name</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 OR 2 OR 3) AND 4</booleanFilter>
            <errorMessage>Representative must be part of Sales team.</errorMessage>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Sales Specialist</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Sales Lead</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Sales Manager</value>
            </filterItems>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Compliance_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Compliant</fullName>
                </value>
                <value>
                    <fullName>Need to Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting QA Mgr Approval</fullName>
                </value>
                <value>
                    <fullName>QA Mgr Disputed</fullName>
                </value>
                <value>
                    <fullName>Awaiting Sales Approval</fullName>
                </value>
                <value>
                    <fullName>Sales Mgr Disputed</fullName>
                </value>
                <value>
                    <fullName>Awaiting Rep Coaching</fullName>
                </value>
                <value>
                    <fullName>Rep Coaching Rejection</fullName>
                </value>
                <value>
                    <fullName>Accept Coaching Rejection</fullName>
                </value>
                <value>
                    <fullName>Rep Coaching Completed</fullName>
                </value>
                <value>
                    <fullName>Skipped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UPL_Coaching__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UPL Coaching</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Violation_A1__c</fullName>
        <inlineHelpText>Did the rep recommend, advise, or make any statement that can be deemed UPL (Concern)?</inlineHelpText>
        <label>UPL Concern</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Violation_A2__c</fullName>
        <label>Improper Sales Practice</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Violation_A3__c</fullName>
        <inlineHelpText>Did agent provide the required disclosure?</inlineHelpText>
        <label>Was the disclosure provided?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No (1st Contact)</fullName>
                </value>
                <value>
                    <fullName>No (2nd Contact)</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Violation_A7__c</fullName>
        <inlineHelpText>Did agent provide tax advice or tax form advice?</inlineHelpText>
        <label>Provide tax or tax form advice?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Compliance Review</label>
    <nameField>
        <displayFormat>CReview-{00000}</displayFormat>
        <label>Compliance Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Reviews</pluralLabel>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <label>Training</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Compliance_Review_Last_Corrective_Plan__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>LCP_Status__c</fullName>
        <description>Store Compliance Review Last Corrective Plan Status</description>
        <label>LCP Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Compliance Review Last Corrective Plan</label>
</CustomObject>

src/objects/Compliance_Review_Number_Of_DayMonth__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Compliance Review Number Of DayMonth</label>
</CustomObject>

src/objects/Compliance_Review_Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Store Status of Compliance Review</description>
    <fields>
        <fullName>Compliance_Status__c</fullName>
        <label>Compliance Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Compliance Review Status</label>
</CustomObject>

src/classes/ComplianceReviewServiceTestSales.cls
@isTest
public class ComplianceReviewServiceTestSales
{
  public static User salesRepUser1;
  static User salesRepUser2;
  static Set<String> STATUS_EXCLUDE_VIOLATION_LIST = new Set<String>{'Draft','Compliant','QA Mgr Disputed','Rep Coaching Completed','Skipped'};
  
  public static void setupData()
  {
    // Insert Sales Manager User
        User salesMgrUser1 = TestUtils.SALES_MGR_USER;
        salesMgrUser1.CommunityNickname = 'alkjvxa';
        User salesMgrUser2 = TestUtils.SALES_MGR_USER;
        salesMgrUser2.Username += 'b';
        salesMgrUser2.CommunityNickname = 'alkjvxb';
        System.runAs(TestUtils.ADMIN_USER)
        {
            insert new User[]{salesMgrUser1, salesMgrUser2};
        }
        
        // Insert Sales Rep Users
        salesRepUser1 = TestUtils.SALES_REP_USER;
        salesRepUser1.CommunityNickname = 'alkjvxc';
        salesRepUser1.ManagerId = salesMgrUser1.Id;
        
        salesRepUser2 = TestUtils.SALES_REP_USER;
        salesRepUser1.CommunityNickname = 'alkjvxd';
        salesRepUser2.Username += 'b';
        salesRepUser2.ManagerId = salesMgrUser2.Id;
        System.runAs(TestUtils.ADMIN_USER)
        {
            insert new User[]{salesRepUser1, salesRepUser2};
        }
        
        Compliance_Review_Number_Of_DayMonth__c numberDay1 = new Compliance_Review_Number_Of_DayMonth__c();
        numberDay1.Name = 'Corrective Plan UPL Coaching';
        numberDay1.Number__c = 6;
        
        Compliance_Review_Number_Of_DayMonth__c numberDay2 = new Compliance_Review_Number_Of_DayMonth__c();
        numberDay2.Name = 'Written Warning Period';
        numberDay2.Number__c = 6;
        
        Compliance_Review_Number_Of_DayMonth__c numberDay3 = new Compliance_Review_Number_Of_DayMonth__c();
        numberDay3.Name = 'Day Violations';
        numberDay3.Number__c = 90;
        
        insert new Compliance_Review_Number_Of_DayMonth__c[]{numberDay1,numberDay2,numberDay3};
        
        Compliance_Review_Last_Corrective_Plan__c dayViolationsStatus = new Compliance_Review_Last_Corrective_Plan__c();
        dayViolationsStatus.Name = 'Day Violations';
        dayViolationsStatus.LCP_Status__c = 'Coaching, Verbal, Training';
        
      Compliance_Review_Last_Corrective_Plan__c writtenWarningPeriodStatus = new Compliance_Review_Last_Corrective_Plan__c();
      writtenWarningPeriodStatus.Name = 'Written Warning Period';
        writtenWarningPeriodStatus.LCP_Status__c = '1st Written, 2nd Written';
        
        Compliance_Review_Last_Corrective_Plan__c terminationtStatus = new Compliance_Review_Last_Corrective_Plan__c();
        terminationtStatus.Name = 'Termination';
        terminationtStatus.LCP_Status__c = 'Termination';
        
        insert new Compliance_Review_Last_Corrective_Plan__c[]{dayViolationsStatus,writtenWarningPeriodStatus,terminationtStatus};
        
        Compliance_Review_Status__c repCoachingCompletedStatus = new Compliance_Review_Status__c();
        repCoachingCompletedStatus.Name = 'Rep Coaching Completed';
        repCoachingCompletedStatus.Compliance_Status__c = 'Rep Coaching Completed';
        insert repCoachingCompletedStatus;
  }
  
    public static testmethod void testSalesRepManager()
    {
      setupData();
        // Create Compliance Reviews
        Compliance_Review__c cr1 = new Compliance_Review__c();
        cr1.Representative__c = salesRepUser1.Id;
        Compliance_Review__c cr2 = new Compliance_Review__c();
        cr2.Representative__c = salesRepUser2.Id;
        
        Test.startTest();
        
        insert new Compliance_Review__c[]{cr1, cr2};
    }
    
    public static testmethod void testInitialDisclaimer()
    {
       setupData();
       Compliance_Review__c cr1 = new Compliance_Review__c();
          cr1.Representative__c = salesRepUser1.Id;
          cr1.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr1.Recorded_Call_ID__c = '30001';
          cr1.Violation_A3__c = 'No (1st Contact)';
          cr1.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-5);
          insert cr1;
          
          cr1.status__c = 'Rep Coaching Completed';
          update cr1;

        List<Compliance_Review__c> insertedComReview = [Select Id , Corrective_Plan_Outbound_Disclaimer__c From Compliance_Review__c Where Id =: cr1.Id];
        System.assertEquals('1st Written' , insertedComReview[0].Corrective_Plan_Outbound_Disclaimer__c , '1st Written');

        //LCP 1st Written
        Compliance_Review__c cr2 = new Compliance_Review__c();
                  cr2.Representative__c = salesRepUser1.Id;
                  cr2.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
                  cr2.Recorded_Call_ID__c = '30002';
                  cr2.Violation_A3__c = 'No (1st Contact)';
        insert cr2;

        List<Compliance_Review__c> insertedComReview2 = [Select Id , LCP_Outbound_Disclaimer__c, Corrective_Plan_Outbound_Disclaimer__c From Compliance_Review__c Where Id =: cr2.Id];
        System.assertEquals('1st Written' , insertedComReview2[0].LCP_Outbound_Disclaimer__c , '1st Written');  

        cr2.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-1);
        cr2.status__c = 'Rep Coaching Completed';
        

        Compliance_Review__c cr3 = new Compliance_Review__c();
          cr3.Representative__c = salesRepUser1.Id;
          cr3.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr3.Recorded_Call_ID__c = '30003';
          Test.startTest();
          update cr2;
          insert cr3;
          Test.stopTest();

        List<Compliance_Review__c> insertedComReview3 = [Select Id , LCP_Outbound_Disclaimer__c, Corrective_Plan_Outbound_Disclaimer__c From Compliance_Review__c Where Id =: cr3.Id];
        System.assertEquals('2nd Written' , insertedComReview3[0].LCP_Outbound_Disclaimer__c , '2nd Written'); 
    }

    public static testmethod void testInitialDisclaimer_Under6Month()
    {
       setupData();
       Compliance_Review__c cr1 = new Compliance_Review__c();
          cr1.Representative__c = salesRepUser1.Id;
          cr1.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr1.Recorded_Call_ID__c = '30001';
          cr1.Violation_A3__c = 'No (1st Contact)';
          cr1.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-1);
          insert cr1;
          
          cr1.status__c = 'Rep Coaching Completed';
          update cr1;

        List<Compliance_Review__c> insertedComReview = [Select Id , Corrective_Plan_Outbound_Disclaimer__c From Compliance_Review__c Where Id =: cr1.Id];
        System.assertEquals('1st Written' , insertedComReview[0].Corrective_Plan_Outbound_Disclaimer__c , '1st Written');

        //LCP 1st Written
        Compliance_Review__c cr2 = new Compliance_Review__c();
                  cr2.Representative__c = salesRepUser1.Id;
                  cr2.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
                  cr2.Recorded_Call_ID__c = '30002';
                  cr2.Violation_A3__c = 'No (1st Contact)';
        insert cr2;

        List<Compliance_Review__c> insertedComReview2 = [Select Id , LCP_Outbound_Disclaimer__c, Corrective_Plan_Outbound_Disclaimer__c From Compliance_Review__c Where Id =: cr2.Id];
        System.assertEquals('1st Written' , insertedComReview2[0].LCP_Outbound_Disclaimer__c , '1st Written');  
      }

    public static testmethod void test2ndDisclaimer()
    {
       setupData();
       Compliance_Review__c cr1 = new Compliance_Review__c();
          cr1.Representative__c = salesRepUser1.Id;
          cr1.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr1.Recorded_Call_ID__c = '30001';
          cr1.Violation_A3__c = 'No (2nd Contact)';
          cr1.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-2);
          insert cr1;
          
          cr1.status__c = 'Rep Coaching Completed';
          update cr1;

        List<Compliance_Review__c> insertedComReview = [Select Id , Cp_2nd_Contact_Disclaimer__c From Compliance_Review__c Where Id =: cr1.Id];
        System.assertEquals('Coaching' , insertedComReview[0].Cp_2nd_Contact_Disclaimer__c , 'Coaching');
        system.debug(cr1);
        //LCP 1st Written
        Compliance_Review__c cr2 = new Compliance_Review__c();
                  cr2.Representative__c = salesRepUser1.Id;
                  cr2.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
                  cr2.Recorded_Call_ID__c = '30002';
                  cr2.Violation_A3__c = 'No (2nd Contact)';
        insert cr2;
        system.debug(cr2);
        List<Compliance_Review__c> insertedComReview2 = [Select Id , LCP_2nd_Contact_Disclaime__c , Cp_2nd_Contact_Disclaimer__c From Compliance_Review__c Where Id =: cr2.Id];
        System.assertEquals('Coaching' , insertedComReview2[0].LCP_2nd_Contact_Disclaime__c , 'Coaching');

        cr2.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-2);
        cr2.status__c = 'Rep Coaching Completed';
        

        Compliance_Review__c cr3 = new Compliance_Review__c();
          cr3.Representative__c = salesRepUser1.Id;
          cr3.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr3.Recorded_Call_ID__c = '30003';
          Test.startTest();
          update cr2;
          insert cr3;
          Test.stopTest();

        List<Compliance_Review__c> insertedComReview3 = [Select Id , LCP_2nd_Contact_Disclaime__c , Cp_2nd_Contact_Disclaimer__c From Compliance_Review__c Where Id =: cr3.Id];
        System.assertEquals('Verbal' , insertedComReview3[0].LCP_2nd_Contact_Disclaime__c , 'Verbal');
      }

    public static testmethod void test2ndDisclaimer_Under6Month()
    {
       setupData();
       Compliance_Review__c cr1 = new Compliance_Review__c();
          cr1.Representative__c = salesRepUser1.Id;
          cr1.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr1.Recorded_Call_ID__c = '30001';
          cr1.Violation_A3__c = 'No (2nd Contact)';
          cr1.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-1);
          insert cr1;
          
          cr1.status__c = 'Rep Coaching Completed';
          update cr1;

        List<Compliance_Review__c> insertedComReview = [Select Id , Cp_2nd_Contact_Disclaimer__c From Compliance_Review__c Where Id =: cr1.Id];
        System.assertEquals('Coaching' , insertedComReview[0].Cp_2nd_Contact_Disclaimer__c , 'Coaching');

        //LCP 1st Written
        Compliance_Review__c cr2 = new Compliance_Review__c();
                  cr2.Representative__c = salesRepUser1.Id;
                  cr2.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
                  cr2.Recorded_Call_ID__c = '30002';
                  cr2.Violation_A3__c = 'No (2nd Contact)';
        insert cr2;

        List<Compliance_Review__c> insertedComReview2 = [Select Id , LCP_2nd_Contact_Disclaime__c , Cp_2nd_Contact_Disclaimer__c From Compliance_Review__c Where Id =: cr2.Id];
        System.assertEquals('Coaching' , insertedComReview2[0].LCP_2nd_Contact_Disclaime__c , 'Coaching');
      }

    public static testmethod void testUPL()
    {
       setupData();
       Compliance_Review__c cr1 = new Compliance_Review__c();
          cr1.Representative__c = salesRepUser1.Id;
          cr1.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr1.Recorded_Call_ID__c = '30001';
          cr1.Violation_A1__c = 'Disqualified';
          cr1.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-5);
          insert cr1;
          
          cr1.status__c = 'Rep Coaching Completed';
          update cr1;

        List<Compliance_Review__c> insertedComReview = [Select Id , Corrective_Plan_UPL__c From Compliance_Review__c Where Id =: cr1.Id];
        System.assertEquals('1st Written' , insertedComReview[0].Corrective_Plan_UPL__c , '1st Written');

        //LCP 1st Written
        Compliance_Review__c cr2 = new Compliance_Review__c();
                  cr2.Representative__c = salesRepUser1.Id;
                  cr2.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
                  cr2.Recorded_Call_ID__c = '30002';
                  cr2.Violation_A1__c = 'Disqualified';
        insert cr2;

        List<Compliance_Review__c> insertedComReview2 = [Select Id , LCP_UPL__c  From Compliance_Review__c Where Id =: cr2.Id]; 
        System.assertEquals('1st Written' , insertedComReview2[0].LCP_UPL__c , '1st Written');

        cr2.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-5);
        cr2.status__c = 'Rep Coaching Completed';

        Compliance_Review__c cr3 = new Compliance_Review__c();
          cr3.Representative__c = salesRepUser1.Id;
          cr3.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr3.Recorded_Call_ID__c = '30003';
          Test.startTest();
          update cr2;
          insert cr3;
          Test.stopTest();

        List<Compliance_Review__c> insertedComReview3 = [Select Id , LCP_UPL__c  From Compliance_Review__c Where Id =: cr3.Id]; 
        System.assertEquals('2nd Written' , insertedComReview3[0].LCP_UPL__c , '2nd Written');
      }

      public static testmethod void testUPL_under6month()
    {
       setupData();
       Compliance_Review__c cr1 = new Compliance_Review__c();
          cr1.Representative__c = salesRepUser1.Id;
          cr1.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr1.Recorded_Call_ID__c = '30001';
          cr1.Violation_A1__c = 'Disqualified';
          cr1.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-1);
          insert cr1;
          
          cr1.status__c = 'Rep Coaching Completed';
          update cr1;

        List<Compliance_Review__c> insertedComReview = [Select Id , Corrective_Plan_UPL__c From Compliance_Review__c Where Id =: cr1.Id];
        System.assertEquals('1st Written' , insertedComReview[0].Corrective_Plan_UPL__c , '1st Written');

        //LCP 1st Written
        Compliance_Review__c cr2 = new Compliance_Review__c();
                  cr2.Representative__c = salesRepUser1.Id;
                  cr2.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
                  cr2.Recorded_Call_ID__c = '30002';
                  cr2.Violation_A1__c = 'Disqualified';
        insert cr2;

        List<Compliance_Review__c> insertedComReview2 = [Select Id , LCP_UPL__c  From Compliance_Review__c Where Id =: cr2.Id];
        System.assertEquals('1st Written' , insertedComReview2[0].LCP_UPL__c , '1st Written');
      }

    public static testmethod void testUPL_No2ndViolation()
    {
       setupData();
       Compliance_Review__c cr1 = new Compliance_Review__c();
          cr1.Representative__c = salesRepUser1.Id;
          cr1.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr1.Recorded_Call_ID__c = '30001';
          cr1.Violation_A1__c = 'Disqualified';
          cr1.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-1);
          insert cr1;
          
          cr1.status__c = 'Rep Coaching Completed';
          update cr1;

        List<Compliance_Review__c> insertedComReview = [Select Id , Corrective_Plan_UPL__c From Compliance_Review__c Where Id =: cr1.Id];
        System.assertEquals('1st Written' , insertedComReview[0].Corrective_Plan_UPL__c , '1st Written');

        Compliance_Review__c cr2 = new Compliance_Review__c();
                  cr2.Representative__c = salesRepUser1.Id;
                  cr2.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
                  cr2.Recorded_Call_ID__c = '30002';
        insert cr2;

        List<Compliance_Review__c> insertedComReview2 = [Select Id , LCP_UPL__c  From Compliance_Review__c Where Id =: cr2.Id];
        System.assertEquals('1st Written' , insertedComReview2[0].LCP_UPL__c , '1st Written');

        Compliance_Review__c cr3 = new Compliance_Review__c();
                  cr3.Representative__c = salesRepUser1.Id;
                  cr3.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
                  cr3.Recorded_Call_ID__c = '30003';
                  cr3.Violation_A1__c = 'Disqualified';
        insert cr3;

        List<Compliance_Review__c> insertedComReview3 = [Select Id ,Corrective_Plan_UPL__c, LCP_UPL__c  From Compliance_Review__c Where Id =: cr3.Id];
        System.assertEquals('2nd Written' , insertedComReview3[0].Corrective_Plan_UPL__c , '2nd Written');

      }

    public static testmethod void testUPLCoaching()
    {
       setupData();
       Compliance_Review__c cr1 = new Compliance_Review__c();
          cr1.Representative__c = salesRepUser1.Id;
          cr1.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr1.Recorded_Call_ID__c = '30001';
          cr1.UPL_Coaching__c = True;
          cr1.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-5);
          insert cr1;
          
          cr1.status__c = 'Rep Coaching Completed';
          update cr1;

        List<Compliance_Review__c> insertedComReview = [Select Id , Corrective_Plan_UPL_Coaching__c From Compliance_Review__c Where Id =: cr1.Id];
        System.assertEquals('Coaching' , insertedComReview[0].Corrective_Plan_UPL_Coaching__c , 'Coaching');

        //LCP 1st Written
        Compliance_Review__c cr2 = new Compliance_Review__c();
                  cr2.Representative__c = salesRepUser1.Id;
                  cr2.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
                  cr2.Recorded_Call_ID__c = '30002';
                  cr2.UPL_Coaching__c = True;
        insert cr2;

        List<Compliance_Review__c> insertedComReview2 = [Select Id , LCP_UPL_Coaching__c  From Compliance_Review__c Where Id =: cr2.Id];
        System.assertEquals('Coaching' , insertedComReview2[0].LCP_UPL_Coaching__c , 'Coaching');

        cr2.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-5);
        cr2.status__c = 'Rep Coaching Completed';
        update cr2;

        Compliance_Review__c cr3 = new Compliance_Review__c();
          cr3.Representative__c = salesRepUser1.Id;
          cr3.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr3.Recorded_Call_ID__c = '30003';
          Test.startTest();
          insert cr3;
          Test.stopTest();

        List<Compliance_Review__c> insertedComReview3 = [Select Id , LCP_UPL_Coaching__c  From Compliance_Review__c Where Id =: cr3.Id];
        System.assertEquals('Verbal' , insertedComReview3[0].LCP_UPL_Coaching__c , 'Verbal');
      }

    public static testmethod void testUPLCoaching_under6month()
    {
       setupData();
       Compliance_Review__c cr1 = new Compliance_Review__c();
          cr1.Representative__c = salesRepUser1.Id;
          cr1.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr1.Recorded_Call_ID__c = '30001';
          cr1.UPL_Coaching__c = True;
          cr1.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-1);
          insert cr1;
          
          cr1.status__c = 'Rep Coaching Completed';
          update cr1;

        List<Compliance_Review__c> insertedComReview = [Select Id , Corrective_Plan_UPL_Coaching__c From Compliance_Review__c Where Id =: cr1.Id];
        System.assertEquals('Coaching' , insertedComReview[0].Corrective_Plan_UPL_Coaching__c , 'Coaching');

        //LCP 1st Written
        Compliance_Review__c cr2 = new Compliance_Review__c();
                  cr2.Representative__c = salesRepUser1.Id;
                  cr2.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
                  cr2.Recorded_Call_ID__c = '30002';
                  cr2.UPL_Coaching__c = True;
        insert cr2;

        List<Compliance_Review__c> insertedComReview2 = [Select Id , LCP_UPL_Coaching__c  From Compliance_Review__c Where Id =: cr2.Id];
        System.assertEquals('Coaching' , insertedComReview2[0].LCP_UPL_Coaching__c , 'Coaching');
      }

    public static testmethod void testTaxViolation_90Day()
    {
       setupData();
       Compliance_Review__c cr1 = new Compliance_Review__c();
          cr1.Representative__c = salesRepUser1.Id;
          cr1.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr1.Recorded_Call_ID__c = '30001';
          cr1.Violation_A7__c = 'Yes';
          cr1.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-1);
          insert cr1;
          
          cr1.status__c = 'Rep Coaching Completed';
          update cr1;

        List<Compliance_Review__c> insertedComReview = [Select Id , Corrective_Plan_Taxation__c From Compliance_Review__c Where Id =: cr1.Id];
        System.assertEquals('Coaching' , insertedComReview[0].Corrective_Plan_Taxation__c , 'Coaching');

        //LCP 1st Written
        Compliance_Review__c cr2 = new Compliance_Review__c();
                  cr2.Representative__c = salesRepUser1.Id;
                  cr2.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
                  cr2.Recorded_Call_ID__c = '30002';
                  cr2.Violation_A7__c = 'Yes';
        insert cr2;

        List<Compliance_Review__c> insertedComReview2 = [Select Id , LCP_Taxation__c  From Compliance_Review__c Where Id =: cr2.Id];
        System.assertEquals('Coaching' , insertedComReview2[0].LCP_Taxation__c , 'Coaching');

        cr2.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-1);
        cr2.status__c = 'Rep Coaching Completed';
        update cr2;

        Compliance_Review__c cr3 = new Compliance_Review__c();
          cr3.Representative__c = salesRepUser1.Id;
          cr3.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr3.Recorded_Call_ID__c = '30003';
          Test.startTest();
          insert cr3;
          Test.stopTest();
      }
     
    public static testmethod void testImproperSales()
    {
       setupData();
       Compliance_Review__c cr1 = new Compliance_Review__c();
          cr1.Representative__c = salesRepUser1.Id;
          cr1.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr1.Recorded_Call_ID__c = '30001';
          cr1.Violation_A2__c = 'Disqualified';
          cr1.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-5);
          insert cr1;
          
          cr1.status__c = 'Rep Coaching Completed';
          update cr1;

        List<Compliance_Review__c> insertedComReview = [Select Id , CP_Unethical_Business_Practice__c From Compliance_Review__c Where Id =: cr1.Id];
        System.assertEquals('1st Written' , insertedComReview[0].CP_Unethical_Business_Practice__c , '1st Written');

        //LCP 1st Written
        Compliance_Review__c cr2 = new Compliance_Review__c();
                  cr2.Representative__c = salesRepUser1.Id;
                  cr2.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
                  cr2.Recorded_Call_ID__c = '30002';
                  cr2.Violation_A2__c = 'Disqualified';
        insert cr2;

        List<Compliance_Review__c> insertedComReview2 = [Select Id , LCP_Unethical_Business_Practice__c  From Compliance_Review__c Where Id =: cr2.Id];
        System.assertEquals('1st Written' , insertedComReview2[0].LCP_Unethical_Business_Practice__c , '1st Written');

        cr2.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-5);
        cr2.status__c = 'Rep Coaching Completed';

        Compliance_Review__c cr3 = new Compliance_Review__c();
          cr3.Representative__c = salesRepUser1.Id;
          cr3.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr3.Recorded_Call_ID__c = '30003';
          Test.startTest();
          update cr2;
          insert cr3;
          Test.stopTest();
      }  

      public static testmethod void testImproperSales_under6month()
    {
       setupData();
       Compliance_Review__c cr1 = new Compliance_Review__c();
          cr1.Representative__c = salesRepUser1.Id;
          cr1.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr1.Recorded_Call_ID__c = '30001';
          cr1.Violation_A2__c = 'Disqualified';
          cr1.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-1);
          insert cr1;
          
          cr1.status__c = 'Rep Coaching Completed';
          update cr1;

        List<Compliance_Review__c> insertedComReview = [Select Id , CP_Unethical_Business_Practice__c From Compliance_Review__c Where Id =: cr1.Id];
        System.assertEquals('1st Written' , insertedComReview[0].CP_Unethical_Business_Practice__c , '1st Written');

        //LCP 1st Written
        Compliance_Review__c cr2 = new Compliance_Review__c();
                  cr2.Representative__c = salesRepUser1.Id;
                  cr2.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
                  cr2.Recorded_Call_ID__c = '30002';
                  cr2.Violation_A2__c = 'Disqualified';
        insert cr2;

        List<Compliance_Review__c> insertedComReview2 = [Select Id , LCP_Unethical_Business_Practice__c  From Compliance_Review__c Where Id =: cr2.Id]; 
        System.assertEquals('1st Written' , insertedComReview2[0].LCP_Unethical_Business_Practice__c , '1st Written');
      }

      public static testmethod void testSecurity()
    {
       setupData();
       Compliance_Review__c cr1 = new Compliance_Review__c();
          cr1.Representative__c = salesRepUser1.Id;
          cr1.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr1.Recorded_Call_ID__c = '30001';
          cr1.Violation_A5__c = 'No';
          cr1.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-1);
          insert cr1;
          
          cr1.status__c = 'Rep Coaching Completed';
          update cr1;

        List<Compliance_Review__c> insertedComReview = [Select Id , Corrective_Plan_Security__c From Compliance_Review__c Where Id =: cr1.Id];
        System.assertEquals('Coaching' , insertedComReview[0].Corrective_Plan_Security__c , 'Coaching');

        //LCP 1st Written
        Compliance_Review__c cr2 = new Compliance_Review__c();
                  cr2.Representative__c = salesRepUser1.Id;
                  cr2.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
                  cr2.Recorded_Call_ID__c = '30002';
                  cr2.Violation_A5__c = 'No';
        insert cr2;

        List<Compliance_Review__c> insertedComReview2 = [Select Id , LCP_Security__c  From Compliance_Review__c Where Id =: cr2.Id];
        System.assertEquals('Coaching' , insertedComReview2[0].LCP_Security__c , 'Coaching');

        cr2.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-1);
        cr2.status__c = 'Rep Coaching Completed';

        Compliance_Review__c cr3 = new Compliance_Review__c();
          cr3.Representative__c = salesRepUser1.Id;
          cr3.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr3.Recorded_Call_ID__c = '30003';
          Test.startTest();
          update cr2;
          insert cr3;
          Test.stopTest();
      }  

      public static testmethod void testFeeViolation()
    {
       setupData();
       Compliance_Review__c cr1 = new Compliance_Review__c();
          cr1.Representative__c = salesRepUser1.Id;
          cr1.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr1.Recorded_Call_ID__c = '30001';
          cr1.Violation_A8__c = 'No';
          cr1.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-2);
          insert cr1;
          
          cr1.status__c = 'Rep Coaching Completed';
          update cr1;

        List<Compliance_Review__c> insertedComReview = [Select Id , Corrective_Plan_Fee__c From Compliance_Review__c Where Id =: cr1.Id];
        System.assertEquals('Coaching' , insertedComReview[0].Corrective_Plan_Fee__c , 'Coaching');

        //LCP 1st Written
        Compliance_Review__c cr2 = new Compliance_Review__c();
                  cr2.Representative__c = salesRepUser1.Id;
                  cr2.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
                  cr2.Recorded_Call_ID__c = '30002';
                  cr2.Violation_A8__c = 'No';
        insert cr2;

        List<Compliance_Review__c> insertedComReview2 = [Select Id , LCP_Fee__c  From Compliance_Review__c Where Id =: cr2.Id];
        System.assertEquals('Coaching' , insertedComReview2[0].LCP_Fee__c , 'Coaching');

        cr2.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-2);
        cr2.status__c = 'Rep Coaching Completed';
        update cr2;

        Compliance_Review__c cr3 = new Compliance_Review__c();
          cr3.Representative__c = salesRepUser1.Id;
          cr3.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
          cr3.Recorded_Call_ID__c = '30003';
          Test.startTest();
          insert cr3;
          Test.stopTest();

        List<Compliance_Review__c> insertedComReview3 = [Select Id , LCP_Fee__c  From Compliance_Review__c Where Id =: cr3.Id]; 
        System.assertEquals('Verbal' ,insertedComReview3[0].LCP_Fee__c , 'Verbal');
      } 

       public static testmethod void testFeeViolation_under6Month()
      {
         setupData();
         Compliance_Review__c cr1 = new Compliance_Review__c();
            cr1.Representative__c = salesRepUser1.Id;
            cr1.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
            cr1.Recorded_Call_ID__c = '30001';
            cr1.Violation_A8__c = 'No';
            cr1.Corrective_Plan_Start_Date__c = DateTime.now().addMonths(-1);
            insert cr1;
            
            cr1.status__c = 'Rep Coaching Completed';
            update cr1;

          List<Compliance_Review__c> insertedComReview = [Select Id , Corrective_Plan_Fee__c From Compliance_Review__c Where Id =: cr1.Id];
          System.assertEquals('Coaching' , insertedComReview[0].Corrective_Plan_Fee__c , 'Coaching');

          //LCP 1st Written
          Compliance_Review__c cr2 = new Compliance_Review__c();
                    cr2.Representative__c = salesRepUser1.Id;
                    cr2.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
                    cr2.Recorded_Call_ID__c = '30002';
                    cr2.Violation_A8__c = 'No';
          insert cr2;

          List<Compliance_Review__c> insertedComReview2 = [Select Id , LCP_Fee__c  From Compliance_Review__c Where Id =: cr2.Id];
          System.assertEquals('Coaching' , insertedComReview2[0].LCP_Fee__c );
        }
}