src/objects/Compliance_Review__c.object
<CustomObject>
    <description>Represents a call listened to and reviewed by the Sales QA &amp; Compliance team</description>
    <fields>
        <fullName>Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Sales Representative that is being reviewed</description>
        <inlineHelpText>The Sales Representative that is being reviewed</inlineHelpText>
        <label>Rep Name</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 OR 2 OR 3) AND 4</booleanFilter>
            <errorMessage>Representative must be part of Sales team.</errorMessage>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Sales Specialist</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Sales Lead</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Sales Manager</value>
            </filterItems>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Compliance_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Compliant</fullName>
                </value>
                <value>
                    <fullName>Need to Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting QA Mgr Approval</fullName>
                </value>
                <value>
                    <fullName>QA Mgr Disputed</fullName>
                </value>
                <value>
                    <fullName>Awaiting Sales Approval</fullName>
                </value>
                <value>
                    <fullName>Sales Mgr Disputed</fullName>
                </value>
                <value>
                    <fullName>Awaiting Rep Coaching</fullName>
                </value>
                <value>
                    <fullName>Rep Coaching Rejection</fullName>
                </value>
                <value>
                    <fullName>Accept Coaching Rejection</fullName>
                </value>
                <value>
                    <fullName>Rep Coaching Completed</fullName>
                </value>
                <value>
                    <fullName>Skipped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Compliance Review</label>
    <nameField>
        <displayFormat>CReview-{00000}</displayFormat>
        <label>Compliance Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Compliance_Review_Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Store Status of Compliance Review</description>
    <fields>
        <fullName>Compliance_Status__c</fullName>
        <label>Compliance Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Compliance Review Status</label>
</CustomObject>

src/classes/ComplianceReviewManualSharing.cls
public with sharing class ComplianceReviewManualSharing 
{
    static final String COMPLIANCE_STATUS = 'Compliant';
    static final String REP_COACHING_COMPLETED_STATUS = 'Rep Coaching Completed';
    static final String EXCLUDE_COMPLETE_STATUS = 'Exclude Complete Status';
    
    public static void complianceReviewManualSharingSalesRep(List<Compliance_Review__c> newComp)
    {
        try
        { 
            List<Compliance_Review__Share> compShare = new List<Compliance_Review__Share>();
            Compliance_Review_Status__c compStatus = Compliance_Review_Status__c.getInstance(EXCLUDE_COMPLETE_STATUS);
            for(Compliance_Review__c comp : newComp)
            {
                if(compStatus.Compliance_Status__c.contains(comp.Status__c))
                {
                    // Create new sharing object for the custom object Job.
                    Compliance_Review__Share complianceShare  = new Compliance_Review__Share();
                    
                    // Set the ID of record being shared.
                    complianceShare.ParentId = comp.Id;
                
                    // Set the ID of user or group being granted access.
                    complianceShare.UserOrGroupId = comp.Representative__c;
                    
                    // Set the access level.
                    complianceShare.AccessLevel = 'Read';
                    
                    // Set rowCause to 'manual' for manual sharing.
                    // This line can be omitted as 'manual' is the default value for sharing objects.
                    complianceShare.RowCause = Schema.Compliance_Review__Share.RowCause.Manual;
                    compShare.add(complianceShare);
                    system.debug(complianceShare);
                }
            }
            // Insert the sharing record and capture the save result. 
            // The false parameter allows for partial processing if multiple records passed 
            // into the operation.
            Database.SaveResult[] srList;
            if(!compShare.isEmpty())
                 srList = Database.insert(compShare,false);
            for(Database.SaveResult sr : srList)
            {
                // Process the save results.
                if(sr.isSuccess())
                {
                    // Indicates success
                    System.debug('Successfully inserted Compliance Review Shared. Compliance Review ID: ' + sr.getId());
                }
                else 
                {
                    // Operation failed, so get all errors                
                    for(Database.Error err : sr.getErrors())
                    {
                        System.debug('The following error has occurred.');                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('Compliance Review fields that affected this error: ' + err.getFields());
                    }
                }
            }
        }
        catch(Exception ex)
        {
            System.debug('>>>>> Compliance Review Manual Sharing : '+ex.getMessage());
        }
    }
    
    public void complianceReviewManualSharingBatch()
    {
        Compliance_Review_Status__c compStatus = Compliance_Review_Status__c.getInstance(EXCLUDE_COMPLETE_STATUS);
        List<String> excludeCompleteStatusList = compStatus.Compliance_Status__c.split(', ');
        List<Compliance_Review__c> compListBatch = [SELECT Id,Status__c, Representative__c 
                                                    FROM Compliance_Review__c 
                                                    WHERE Status__c IN: excludeCompleteStatusList];
        complianceReviewManualSharingSalesRep(compListBatch);
    }
}