src/objects/Compliance_Review__c.object
<CustomObject>
    <description>Represents a call listened to and reviewed by the Sales QA &amp; Compliance team</description>
    <fields>
        <fullName>Length_of_Call__c</fullName>
        <label>Length of Call (Minute)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recorded_Call_ID__c</fullName>
        <externalId>true</externalId>
        <label>Recorded Call ID#</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Sales Representative that is being reviewed</description>
        <inlineHelpText>The Sales Representative that is being reviewed</inlineHelpText>
        <label>Rep Name</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 OR 2 OR 3) AND 4</booleanFilter>
            <errorMessage>Representative must be part of Sales team.</errorMessage>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Sales Specialist</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Sales Lead</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Sales Manager</value>
            </filterItems>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Compliance_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Compliant</fullName>
                </value>
                <value>
                    <fullName>Need to Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting QA Mgr Approval</fullName>
                </value>
                <value>
                    <fullName>QA Mgr Disputed</fullName>
                </value>
                <value>
                    <fullName>Awaiting Sales Approval</fullName>
                </value>
                <value>
                    <fullName>Sales Mgr Disputed</fullName>
                </value>
                <value>
                    <fullName>Awaiting Rep Coaching</fullName>
                </value>
                <value>
                    <fullName>Rep Coaching Rejection</fullName>
                </value>
                <value>
                    <fullName>Accept Coaching Rejection</fullName>
                </value>
                <value>
                    <fullName>Rep Coaching Completed</fullName>
                </value>
                <value>
                    <fullName>Skipped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Compliance Review</label>
    <nameField>
        <displayFormat>CReview-{00000}</displayFormat>
        <label>Compliance Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Reviews</pluralLabel>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <label>Training</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Compliance_Review_Last_Corrective_Plan__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>LCP_Status__c</fullName>
        <description>Store Compliance Review Last Corrective Plan Status</description>
        <label>LCP Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Compliance Review Last Corrective Plan</label>
</CustomObject>

src/objects/Compliance_Review_Number_Of_DayMonth__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Compliance Review Number Of DayMonth</label>
</CustomObject>

src/objects/Compliance_Review_Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Store Status of Compliance Review</description>
    <fields>
        <fullName>Compliance_Status__c</fullName>
        <label>Compliance Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Compliance Review Status</label>
</CustomObject>

src/objects/SalesQA__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ExcludeFromCycle__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Exclude this User from the Sales QA &amp; Compliance Round Robin cycle.</description>
        <inlineHelpText>Exclude this User from the Sales QA &amp; Compliance Round Robin cycle.</inlineHelpText>
        <label>ExcludeFromCycle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pulled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pulled</label>
        <type>Checkbox</type>
    </fields>
    <label>SalesQA</label>
</CustomObject>

src/objects/SalesQARepRoles__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of Roles that indicate Sales Reps for QA to listen to</description>
    <label>Sales QA Rep Roles</label>
</CustomObject>

src/classes/ComplianceReviewChangeCallIDTest.cls
@isTest
private class ComplianceReviewChangeCallIDTest 
{
    public static Compliance_Review__c complianceReview;
    public static SalesQA__c salesQAObj1;
    public static SalesQARepRoles__c salesQARepRoleObj = new SalesQARepRoles__c();
    public static User userTest;
    
    static void setup()
    {
        salesQARepRoleObj.Name = 'Sales Lead';
        insert salesQARepRoleObj;
        
        Set<String> repRoles = SalesQARepRoles__c.getAll().keySet();
        ID userRoleID = [SELECT ID FROM UserRole WHERE Name = 'Sales Specialist'][0].Id;
        ID salesManager = [SELECT Id FROM User WHERE UserRole.Name = 'Sales Management'][0].Id;

        userTest = new User(FirstName='Testttt', LastName='SalesRep', UserName='test54321@test.test', Email='test91@test.com', Alias='tester91',
                LocaleSidKey='en_US', LanguageLocaleKey='en_US', EmailEncodingKey='ISO-8859-1', CommunityNickname='test91',
                ProfileId = TestUtils.salesAgentProfileId, UserRoleId = userRoleID, TimeZoneSidKey='America/New_York',isActive = true, ManagerId = salesManager);
        
        System.runAs(TestUtils.ADMIN_USER)
        {
            insert userTest;
        }
        
        salesQAObj1 = new SalesQA__c();
        salesQAObj1.SetupOwnerId = userTest.Id;
        salesQAObj1.ExcludeFromCycle__c = false;
        salesQAObj1.Pulled__c = false;
        insert salesQAObj1;
        
        Compliance_Review_Number_Of_DayMonth__c numberDay1 = new Compliance_Review_Number_Of_DayMonth__c();
        numberDay1.Name = 'Corrective Plan UPL Coaching';
        numberDay1.Number__c = 6;
        
        Compliance_Review_Number_Of_DayMonth__c numberDay2 = new Compliance_Review_Number_Of_DayMonth__c();
        numberDay2.Name = 'Written Warning Period';
        numberDay2.Number__c = 6;
        
        Compliance_Review_Number_Of_DayMonth__c numberDay3 = new Compliance_Review_Number_Of_DayMonth__c();
        numberDay3.Name = 'Day Violations';
        numberDay3.Number__c = 90;
        
        insert new Compliance_Review_Number_Of_DayMonth__c[]{numberDay1,numberDay2,numberDay3};
        
        Compliance_Review_Last_Corrective_Plan__c dayViolationsStatus = new Compliance_Review_Last_Corrective_Plan__c();
        dayViolationsStatus.Name = 'Day Violations';
        dayViolationsStatus.LCP_Status__c = 'Coaching, Verbal, Training';
        
        Compliance_Review_Last_Corrective_Plan__c writtenWarningPeriodStatus = new Compliance_Review_Last_Corrective_Plan__c();
        writtenWarningPeriodStatus.Name = 'Written Warning Period';
        writtenWarningPeriodStatus.LCP_Status__c = '1st Written, 2nd Written';
        
        Compliance_Review_Last_Corrective_Plan__c terminationtStatus = new Compliance_Review_Last_Corrective_Plan__c();
        terminationtStatus.Name = 'Termination';
        terminationtStatus.LCP_Status__c = 'Termination';
        
        insert new Compliance_Review_Last_Corrective_Plan__c[]{dayViolationsStatus,writtenWarningPeriodStatus,terminationtStatus};
        
        Compliance_Review_Status__c repCoachingCompletedStatus = new Compliance_Review_Status__c();
        repCoachingCompletedStatus.Name = 'Rep Coaching Completed';
        repCoachingCompletedStatus.Compliance_Status__c = 'Rep Coaching Completed';
        insert repCoachingCompletedStatus;
        
        //create Compliance
        complianceReview = new Compliance_Review__c();
        complianceReview.RecordTypeId = NewComplianceReviewController.SCOREDBASED_RECORDTYPE;
        complianceReview.Representative__c = userTest.Id;
        complianceReview.Recorded_Call_ID__c = 'qwer1';
        complianceReview.Status__c = 'Draft';
        complianceReview.Length_of_Call__c = 2.30;
                
        insert complianceReview;
    }   
    
    static testMethod void complianceChangeCallIDTest_Positive() 
    {
        setup();
     
        PageReference pageRef = Page.ComplianceReviewChangeCallID;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('ComplianceID', complianceReview.Id);
        ComplianceReviewChangeCallIDController controller = new ComplianceReviewChangeCallIDController();
        controller.recordCallId = 'qwer2';
        controller.save();
    }
    
    static testMethod void complianceChangeCallIDTest_Duplicated_Negative() 
    {
        setup();
     
        PageReference pageRef = Page.ComplianceReviewChangeCallID;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('ComplianceID', complianceReview.Id);
        ComplianceReviewChangeCallIDController controller = new ComplianceReviewChangeCallIDController();
        controller.recordCallId = 'qwer1';
        controller.save();
    }
    
    static testMethod void complianceChangeCallIDTest_NoCallID_Negative() 
    {
        setup();
     
        PageReference pageRef = Page.ComplianceReviewChangeCallID;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('ComplianceID', complianceReview.Id);
        ComplianceReviewChangeCallIDController controller = new ComplianceReviewChangeCallIDController();
        controller.save();
    }
}