src/objects/Component_Type__c.object
<CustomObject>
    <description>matching ComponentType table in LZData</description>
    <fields>
        <fullName>Component_Type_ID__c</fullName>
        <externalId>true</externalId>
        <label>Component Type ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Component Type</label>
    <nameField>
        <label>Component Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Component Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <description>matching Process table in LZData</description>
    <fields>
        <fullName>Process_ID__c</fullName>
        <description>From iProcess field in pkProcess table of LZData database</description>
        <externalId>true</externalId>
        <label>Process ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Component_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Component Type</label>
        <referenceTo>Component_Type__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LZ_Component_Type_ID__c</fullName>
        <description>fkComponentType column in ProductComponent of LZData</description>
        <label>LZ Component Type ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LZ_Parent_Product_ID__c</fullName>
        <description>From pkProductConfiguration column in ProductConfiguration table of LZData</description>
        <label>LZ Parent Product ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LZ_Process_ID__c</fullName>
        <description>iProcess from Process in LZData</description>
        <label>LZ Process ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LZ_Product_ID__c</fullName>
        <description>matching pkProductConfiguration column of ProductConfiguation table in LZData</description>
        <externalId>true</externalId>
        <label>LZ Product ID</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LZ_Product_Line_ID__c</fullName>
        <description>fkProductLine in Process from LZData</description>
        <label>LZ Product Line ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Line</label>
        <referenceTo>Product_Line__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product_Line__c.object
<CustomObject>
    <description>matching ProductLine lookup table in LZData</description>
    <fields>
        <fullName>Product_Line_ID__c</fullName>
        <description>match pkProductLine column of ProductLine table in LZData</description>
        <externalId>true</externalId>
        <label>Product Line ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Relationship_Type__c.object
<CustomObject>
    <description>matching RelationshipType table in LZData</description>
    <label>Relationship Type</label>
    <nameField>
        <label>Relationship Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Product2ServiceTest.cls
@isTest
private class Product2ServiceTest {

    final static String NAME = 'test';
    final static Integer PRODUCT_SIZE = 50;
    static List<Component_Type__c> testComponentTypes;
    static List<Process__c> testProcesses;
    static List<Product_Line__c> testProductLines;
    static List<Product2> testProducts;
    static Id relationshipTypeId;
    
    public static List<Product2> createProducts (Integer size , String nameValue, Boolean doInsert)
    {
        List<Product2> productsToCreate = new List<Product2>();
        relationshipTypeId = TestUtils.createRelationshipTypesTypes(1 , 'Process', true)[0].Id;
        for(Integer i = 0 ;i<size ;++i)
        {
            Product2 theProduct = new Product2();
            theProduct.Name = nameValue + i;
            theProduct.LZ_Product_ID__c = i;
            theProduct.LZ_Component_Type_ID__c = 0;
            theProduct.LZ_Process_ID__c = 0;
            theProduct.LZ_Product_Line_ID__c = 0;
            theProduct.LZ_Parent_Product_ID__c = i-1;
            theProduct.Relationship_Type__c = relationshipTypeId;
            productsToCreate.add(theProduct);
        }
        
        if(doInsert)
            insert productsToCreate;
        
        return productsToCreate;
    }
    
    static void setupData()
    {
        testProductLines = TestUtils.createProductLines(10, NAME, true);
        testComponentTypes = TestUtils.createComponentTypes(10, NAME, true);
        testProcesses = TestUtils.createProcesses(150, NAME, true);
        testProducts = createProducts(PRODUCT_SIZE, NAME, false);
    }
    
    static testMethod void testMatchingComponentTypeProcessProductLine()
    {
        setupData();

        Test.startTest();
        upsert testProducts;
        Test.stopTest();
        
        List<Product2> updatedProducts = [SELECT Id , Component_Type__c, Process__c, Product_Line__c FROM Product2];
        List<Component_Type__c> componentTypes = [SELECT Id FROM Component_Type__c WHERE Component_Type_ID__c = 0];
        List<Process__c> processes = [SELECT Id FROM Process__c WHERE Process_ID__c = 0];
        List<Product_Line__c> productLines = [SELECT Id FROM Product_Line__c WHERE Product_Line_ID__c = 0];

        System.assertEquals(updatedProducts.size(), PRODUCT_SIZE, 'There should be ' + PRODUCT_SIZE + ' products.');
        System.assertEquals(updatedProducts[0].Component_Type__c, componentTypes[0].Id, '');
        System.assertEquals(updatedProducts[0].Process__c, processes[0].Id, '');
        System.assertEquals(updatedProducts[0].Product_Line__c, productLines[0].Id, '');
    }
    
    static testMethod void testMatchingParentProduct()
    {
        setupData();

        upsert testProducts;
        
        Test.startTest();
        upsert testProducts;
        Test.stopTest();
        
        List<Product2> productsWithParent = [SELECT Id, Parent__c FROM Product2 WHERE Parent__c <> NULL];
        List<Product2> productsWithoutParent = [SELECT Id, Parent__c FROM Product2 WHERE Parent__c = NULL];
        
        Integer productsWithParentCount = PRODUCT_SIZE - 1;
        
        System.assertEquals(productsWithParent.size(), productsWithParentCount, 'There should be ' + productsWithParentCount + ' products.');
        System.assertEquals(productsWithoutParent.size(), 1, 'There should be 1 product.');
    }
}