src/objects/Compliance_Review__c.object
<CustomObject>
    <description>Represents a call listened to and reviewed by the Sales QA &amp; Compliance team</description>
    <fields>
        <fullName>Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Sales Representative that is being reviewed</description>
        <inlineHelpText>The Sales Representative that is being reviewed</inlineHelpText>
        <label>Rep Name</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 OR 2 OR 3) AND 4</booleanFilter>
            <errorMessage>Representative must be part of Sales team.</errorMessage>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Sales Specialist</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Sales Lead</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Sales Manager</value>
            </filterItems>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Compliance_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Compliant</fullName>
                </value>
                <value>
                    <fullName>Need to Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting QA Mgr Approval</fullName>
                </value>
                <value>
                    <fullName>QA Mgr Disputed</fullName>
                </value>
                <value>
                    <fullName>Awaiting Sales Approval</fullName>
                </value>
                <value>
                    <fullName>Sales Mgr Disputed</fullName>
                </value>
                <value>
                    <fullName>Awaiting Rep Coaching</fullName>
                </value>
                <value>
                    <fullName>Rep Coaching Rejection</fullName>
                </value>
                <value>
                    <fullName>Accept Coaching Rejection</fullName>
                </value>
                <value>
                    <fullName>Rep Coaching Completed</fullName>
                </value>
                <value>
                    <fullName>Skipped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Violation_A1__c</fullName>
        <inlineHelpText>Did the rep recommend, advise, or make any statement that can be deemed UPL (Concern)?</inlineHelpText>
        <label>UPL Concern</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Violation_A2__c</fullName>
        <label>Improper Sales Practice</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Violation_A3__c</fullName>
        <inlineHelpText>Did agent provide the required disclosure?</inlineHelpText>
        <label>Was the disclosure provided?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No (1st Contact)</fullName>
                </value>
                <value>
                    <fullName>No (2nd Contact)</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Violation_A4__c</fullName>
        <inlineHelpText>Did agent provide an unauthorized discount(s)?</inlineHelpText>
        <label>Unauthorized discount provided?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Violation_A5__c</fullName>
        <label>Did rep fully verify the customer?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Violation_A6__c</fullName>
        <inlineHelpText>Did rep misrepresent LZ products and services or provide inaccurate information?</inlineHelpText>
        <label>Did rep misrepresent</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Violation_A7__c</fullName>
        <inlineHelpText>Did agent provide tax advice or tax form advice?</inlineHelpText>
        <label>Provide tax or tax form advice?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Violation_A8__c</fullName>
        <inlineHelpText>Recurring Fees, Trial, 3 Pay</inlineHelpText>
        <label>Did rep discuss fees?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Compliance Review</label>
    <nameField>
        <displayFormat>CReview-{00000}</displayFormat>
        <label>Compliance Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CompliancePreventUpdateViolationFields.cls
public with sharing class CompliancePreventUpdateViolationFields 
{
    public static final String COMPLIANCE_STATUS = 'Compliant';
    public static final String COMPLIANCE_ERROR_MESSAGE = 'Violation-related fields cannot be modified if it is not the latest record.';
    
    public static void PreventUpdateViolationFields_CompliantStatus(List<Compliance_Review__c> newComp)
    {
        Set<Id> compRepID = new Set<Id>();
        if(Userinfo.getProfileId() != ADMIN_PROFILE_ID)
        {
            for(Compliance_Review__c comp : newComp)
            {
                compRepID.add(comp.Representative__c);
            }
            List<Compliance_Review__c> compOldList = [  SELECT Id, Status__c, CreatedDate, Violation_A1__c, Violation_A2__c, Violation_A3__c, Violation_A4__c, Violation_A5__c, Violation_A6__c, Violation_A7__c, Violation_A8__c
                                                        FROM Compliance_Review__c 
                                                        WHERE Compliance_Review__c.Representative__c IN: compRepID 
                                                        AND Compliance_Review__c.RecordTypeId =: NewComplianceReviewController.SCOREDBASED_RECORDTYPE
                                                        ORDER BY CreatedDate DESC
                                                     ];

            for(Compliance_Review__c compNew : newComp)
            {
                if(compNew.Status__c == COMPLIANCE_STATUS)
                {
                    if(compOldList.size() > 1)
                    {
                        if(compNew.CreatedDate != compOldList[0].CreatedDate)
                        {
                            for(Compliance_Review__c compOld : compOldList)
                            {
                                if(compNew.Id == compOld.Id)
                                {
                                    if(
                                        compNew.Violation_A1__c != compOld.Violation_A1__c ||
                                        compNew.Violation_A2__c != compOld.Violation_A2__c ||
                                        compNew.Violation_A3__c != compOld.Violation_A3__c ||
                                        compNew.Violation_A4__c != compOld.Violation_A4__c ||
                                        compNew.Violation_A5__c != compOld.Violation_A5__c ||
                                        compNew.Violation_A6__c != compOld.Violation_A6__c ||
                                        compNew.Violation_A7__c != compOld.Violation_A7__c ||
                                        compNew.Violation_A8__c != compOld.Violation_A8__c
                                      )
                                    {
                                        compNew.addError(COMPLIANCE_ERROR_MESSAGE);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    
    public static Id ADMIN_PROFILE_ID 
    {
        get
        {
            if(ADMIN_PROFILE_ID == null)
            {
                List<Profile> adminProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
                if(!adminProfile.isEmpty())
                {
                    ADMIN_PROFILE_ID = adminProfile[0].Id;
                }
            }
            
            return ADMIN_PROFILE_ID ;
        }
    }
}