src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>FkUser__c</fullName>
        <externalId>true</externalId>
        <label>FkUser</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LZ_Order_Contact_ID__c</fullName>
        <externalId>true</externalId>
        <label>LZ Order Contact ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LegalZoom_Contact_ID__c</fullName>
        <externalId>true</externalId>
        <label>LegalZoom Contact ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <label>User Order ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderID__c</fullName>
        <externalId>true</externalId>
        <label>OrderID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order_Date_Time_Created__c</fullName>
        <description>Store the created date time of the order created in LZ Data</description>
        <label>Order Date/Time Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order_Date_Time_Modified__c</fullName>
        <description>DateTime when the Order gets modified.</description>
        <label>Order Date/Time Modified</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>State_of_Formation__c</fullName>
        <label>State of Formation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/IADStoreCreditPanelController_LtngTest.cls
@isTest
private class IADStoreCreditPanelController_LtngTest {
	static Contact con;
    static Order__c order;

    public static void setupData() 
    {
        con = new Contact(FirstName = 'John', LastName = 'Doer', Phone = '4444', MobilePhone = '123456789', FKUser__c='1234', LegalZoom_Contact_ID__c='1234', LZ_Order_Contact_ID__c = '1234');
        insert con;
        
        order = new Order__c(Name = '1000', OrderID__c = '1000', Contact__c = con.Id, State_of_Formation__c = '11', Entity_Name__c = '12', Order_Date_Time_Created__c = DateTime.newInstance(2015, 12, 07, 12, 12, 01), Order_Date_Time_Modified__c = DateTime.newInstance(2015, 12, 08, 12, 12, 01), User_Order_ID__c='123');
        insert order;
    }   
    
    static testMethod void testPopulateStoreCreditsPositive()
    {
        setupData();
        Test.startTest();
        IADStoreCreditPanelController_Ltng theController = new IADStoreCreditPanelController_Ltng();
        IADTestMockGenerator mock = new IADTestMockGenerator();
        mock.testBody = IADTestDataUtil_ltng.getStoreCreditsByCustomerId();
        mock.statusCode = 200;
        Test.setMock(HttpCalloutMock.class, mock);
		IADStoreCreditPanelController_Ltng.populateStoreCredits(String.valueOf(order.Id));
        Test.stopTest();
	}
    
    static testMethod void testPopulateStoreCreditsNegative()
    {
        setupData() ;
        Test.startTest();
        IADStoreCreditPanelController_Ltng theController = new IADStoreCreditPanelController_Ltng();
        IADTestMockGenerator mock = new IADTestMockGenerator();
        mock.testBody = IADTestDataUtil_ltng.getStoreCreditsByCustomerId();
        mock.statusCode = 404;
        Test.setMock(HttpCalloutMock.class, mock);
		IADStoreCreditPanelController_Ltng.populateStoreCredits(String.valueOf(order.Id));
        Test.stopTest();
	}
    static testMethod void testPopulateStoreCreditsNegativenull()
    {
        setupData() ;
        Test.startTest();
        IADStoreCreditPanelController_Ltng theController = new IADStoreCreditPanelController_Ltng();
        IADTestMockGenerator mock = new IADTestMockGenerator();
        mock.testBody = '';
        mock.statusCode = 200;
        Test.setMock(HttpCalloutMock.class, mock);
		IADStoreCreditPanelController_Ltng.populateStoreCredits(String.valueOf(order.Id));
        Test.stopTest();
	}
}