src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>FkUser__c</fullName>
        <externalId>true</externalId>
        <label>FkUser</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderID__c</fullName>
        <externalId>true</externalId>
        <label>OrderID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/IADStoreCreditPanelController_Ltng.cls
public class IADStoreCreditPanelController_Ltng
{
    @AuraEnabled public static String customerId {get;set;}
    @AuraEnabled public static IADInstallmentPaymentService_ltng storeCreditPanelService{get;set;}
    @AuraEnabled public static String orderId{get;set;}
    
    public static void onload(String orderRecordId) 
    {
        storeCreditPanelService = new IADInstallmentPaymentService_ltng();     
        for(Order__c theOrder : [SELECT Id , OrderID__c, Contact__r.FkUser__c FROM Order__c WHERE Id = :orderRecordId])
        {
            customerId = theOrder.Contact__r.FkUser__c;
            orderId = theOrder.OrderID__c;
        }
    }
    
    @AuraEnabled
    public static IADInstallmentPaymentService_ltng populateStoreCredits(String orderRecordId)
    {
        try
        {
            onload(orderRecordId);
            if(customerId != null && customerId != '')
            {
                IADServiceBase_ltng.initWrapper(IADStoreCreditPanelService.GETSTORECREDITSBYCUSTOMERID);//, 'processStoreCredits'
                IADInstallmentPaymentService_ltng.getStoreCreditsByCustomerId(customerId); 
                IADInstallmentPaymentService_ltng.populateStoreCredits();
                IADInstallmentPaymentService_ltng.orderId = orderId;
                IADInstallmentPaymentService_ltng.customerId=customerId;
            }
        }
        catch(Exception theException)
        {
            IADServiceBase_ltng.populateErrorMessage(theException);
        }
        return storeCreditPanelService;
    }
}