src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VM Attempt 1</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 2</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 3</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 4</fullName>
                </value>
                <value>
                    <fullName>VM Final Attempt</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Commission Eligible</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Ineligible</fullName>
                </value>
                <value>
                    <fullName>Call Transferred</fullName>
                </value>
                <value>
                    <fullName>Service Unavailable</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Genesys_Interaction_Id__c</fullName>
        <description>Genesys Interaction Id</description>
        <externalId>true</externalId>
        <label>Genesys Interaction Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <label>Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hard SNE</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress (Assigned)</fullName>
                </value>
                <value>
                    <fullName>Qualified (Interested)</fullName>
                </value>
                <value>
                    <fullName>Closed/Lost - No Interest</fullName>
                </value>
                <value>
                    <fullName>Closed/Lost - No Descision / Activity</fullName>
                </value>
                <value>
                    <fullName>Closed/Lost - Bad Info</fullName>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Genesys_Interaction_Id__c</fullName>
        <description>Genesys Interaction Id</description>
        <externalId>true</externalId>
        <label>Genesys Interaction Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order360__c.object
<CustomObject>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipName>Order360</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Order360</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Active Revenue (Parent Order Item)</relationshipLabel>
        <relationshipName>Active_Revenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_cancellation__c</fullName>
        <label>Reason for cancellation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unaware of service</fullName>
                </value>
                <value>
                    <fullName>(Free Trial) Used service during Free Trial and is no longer needed</fullName>
                </value>
                <value>
                    <fullName>Did not understand service value</fullName>
                </value>
                <value>
                    <fullName>(Paid) No longer needed</fullName>
                </value>
                <value>
                    <fullName>Price too expensive</fullName>
                </value>
                <value>
                    <fullName>Previously retained but still wants to cancel</fullName>
                </value>
                <value>
                    <fullName>Already has an Attorney</fullName>
                </value>
                <value>
                    <fullName>Poor Consultation with an Attorney</fullName>
                </value>
                <value>
                    <fullName>Attorney referred customer elsewhere</fullName>
                </value>
                <value>
                    <fullName>Has not started business</fullName>
                </value>
                <value>
                    <fullName>Business has closed</fullName>
                </value>
                <value>
                    <fullName>Upset and unwilling to listen</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Order Saved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Active Revenue</label>
    <nameField>
        <displayFormat>Ord360-{0000}</displayFormat>
        <label>Order360 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Active Revenue</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Active Won&apos;t Renew</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Not Yet Started</fullName>
                </value>
                <value>
                    <fullName>Payment Due</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LogCallContactControllerTest.cls
@isTest
public class LogCallContactControllerTest 
{
        static final String CONTACT_STATUS = 'Contacted/Spoke';
        static final String LEAD_STATUS = 'Order Placed';
        static final String COMMISSION_CONTACT_STATUS = 'Contacted/Spoke - Commission Eligible';
        static final String QUALIFIED_INTERESTED = 'Qualified (Interested)';
    
    static testMethod void testCreateTask_ContactStatus()
    {
            Account testAccount = TestUtils.createAccounts(1 , 'Test Account' , true)[0];
            Contact testContact = TestUtils.createContacts(1 , 'Test Contact' , testAccount.Id , false)[0];
            testContact.Genesys_Interaction_Id__c = '998899';
            insert testContact;


            ApexPages.StandardController sc = new ApexPages.StandardController(testContact);
                LogCallContactController theController = new LogCallContactController(sc);
                PageReference pageRef = Page.LogCallContact;
                pageRef.getParameters().put('id', String.valueOf(testContact.Id));
                Test.setCurrentPage(pageRef);

                Test.startTest(); 
                    theController.theTask.Contact_Status__c = CONTACT_STATUS;
                    theController.theTask.Lead_Status__c = LEAD_STATUS;
                    theController.createEmailTask();
                Test.stopTest();

                List<Task> createdTasks = [SELECT Id , Subject FROM Task WHERE WhoId =:testContact.Id];
                System.assertEquals(1 , createdTasks.size() , '1 task should have been created');
                List<Contact> contacts = [SELECT Id , Contact_Status__c FROM Contact Where Id = :testContact.Id];
            System.assertEquals(1 , contacts.size() , '1 Contact should have been returned');
            System.assertEquals(CONTACT_STATUS , contacts[0].Contact_Status__c , 'Right Call status should have been populated');
    }

        static testMethod void testCreateTask_LeadStatus()
        {

                Account testAccount = TestUtils.createAccounts(1 , 'Test Account' , true)[0];
                Contact testContact = TestUtils.createContacts(1 , 'Test Contact' , testAccount.Id , false)[0];
                User theUser = TestUtils.createUser('TestUser', TestUtils.salesAgentProfileId , false);
                System.runAs(theUser)
                {
                    testContact.Genesys_Interaction_Id__c = '998899';
                    insert testContact;

                    Task theTask = new Task();
                    theTask.WhoId = testContact.Id;
                    theTask.Description = 'Test Description';
                    theTask.CallObject = '998899';
                    insert theTask;

                    ApexPages.StandardController sc = new ApexPages.StandardController(testContact);
                    LogCallContactController theController = new LogCallContactController(sc);
                    PageReference pageRef = Page.LogCallContact;
                    pageRef.getParameters().put('id', String.valueOf(testContact.Id));
                    Test.setCurrentPage(pageRef);
                
                    Test.startTest(); 
                         theController.theTask.Contact_Status__c = CONTACT_STATUS;
                         theController.theTask.Lead_Status__c = LEAD_STATUS;
                         theController.createTask();
                    Test.stopTest();
                }        
                List<Task> createdTasks = [SELECT Id , Subject FROM Task WHERE WhoId =:testContact.Id];
                System.assertEquals(1 , createdTasks.size() , '1 task should have been created');
                List<Contact> contacts = [SELECT Id , Lead_Status__c , ownerId FROM Contact Where Id = :testContact.Id];
                System.assertEquals(1 , contacts.size() , '1 Contact should have been returned');
                System.assertEquals(LEAD_STATUS , contacts[0].Lead_Status__c , 'Right Call status should have been populated');
                System.assertEquals(theUser.Id , contacts[0].ownerId , 'Right owner Id should have been populated');
        
        }

        static testMethod void testCreateCommissionTask()
        {
                
                Account testAccount = TestUtils.createAccounts(1 , 'Test Account' , true)[0];
                Contact testContact = TestUtils.createContacts(1 , 'Test Contact' , testAccount.Id , false)[0];
                User theUser = TestUtils.createUser('TestUser', TestUtils.salesAgentProfileId , false);
                System.runAs(theUser)
                {
                    testContact.Genesys_Interaction_Id__c = '998899';
                    insert testContact;

                    Task theTask = new Task();
                    theTask.WhoId = testContact.Id;
                    theTask.Description = 'Test Description';
                    theTask.CallObject = '998899';
                    insert theTask;
                    
                    ApexPages.StandardController sc = new ApexPages.StandardController(testContact);
                    LogCallContactController theController = new LogCallContactController(sc);
                    PageReference pageRef = Page.LogCallContact;
                    pageRef.getParameters().put('id', String.valueOf(testContact.Id));
                    Test.setCurrentPage(pageRef);
                
                    Test.startTest(); 
                            theController.theTask.Lead_Status__c = LEAD_STATUS;
                            theController.theTask.Contact_Status__c = COMMISSION_CONTACT_STATUS;
                            theController.createTask();
                    Test.stopTest();
                }
                List<Task> createdTasks = [SELECT Id , Subject FROM Task WHERE WhoId =:testContact.Id];
                System.assertEquals(1 , createdTasks.size() , '1 task should have been created');
                List<Contact> contacts = [SELECT Id , Lead_Status__c , ownerId ,Contact_Status__c  FROM Contact Where Id = :testContact.Id];
                System.assertEquals(1 , contacts.size() , '1 Contact should have been returned');
                System.assertEquals(QUALIFIED_INTERESTED , contacts[0].Lead_Status__c , 'Right Lead status should have been populated');
                System.assertEquals( COMMISSION_CONTACT_STATUS , contacts[0].Contact_Status__c , 'Right Lead status should have been populated');
                System.assertEquals(theUser.Id , contacts[0].ownerId , 'Right owner Id should have been populated.Lead should have been assigned to User');
        }
        
        static testMethod void testCreateSubscriptionSaveTask()
        {
            Account testAccount = TestUtils.createAccounts(1 , 'Test Account' , true)[0];
            Contact testContact = TestUtils.createContacts(1 , 'Test Contact' , testAccount.Id , true)[0];
          
            
            Order__c testOrder = TestUtils.createOrders(1, null , false)[0];
            testOrder.Contact__c = testContact.Id;
            insert testOrder;
            
            Order_Item__c testOrderItem = TestUtils.createOrderItems(1, testOrder.Id ,  false)[0];
            testOrderItem.Subscription_Status__c = 'Active';
            insert testOrderItem;


            User theUser = TestUtils.createUser('TestUser', TestUtils.salesAgentProfileId , false);
            
            System.runAs(theUser)
            {
                testContact.Genesys_Interaction_Id__c = '998899';
                testContact.ownerId = theUser.Id;
                update testContact;

                Task theTask = new Task();
                theTask.WhoId = testContact.Id;
                theTask.Description = 'Test Description';
                theTask.CallObject = '998899';
                insert theTask;
                
                ApexPages.StandardController sc = new ApexPages.StandardController(testContact);
                LogCallContactController theController = new LogCallContactController(sc);
                PageReference pageRef = Page.LogCallContact;
                pageRef.getParameters().put('id', String.valueOf(testContact.Id));
                Test.setCurrentPage(pageRef);
                
                Test.startTest();
                        
                        List<SelectOption> selectOptions = theController.getCancellationReasons();
                        System.assert(!selectOptions.isEmpty() , 'Cancellation Reason should not be empty');
                        theController.SubscriptionItems = theController.SubscriptionItems; 
                        
                        theController.theTask.Lead_Status__c = LEAD_STATUS;
                        theController.theTask.Contact_Status__c = COMMISSION_CONTACT_STATUS;
                        theController.theTask.Is_Subscription_Activity__c  = true;
                        theController.subscriptionItems[0].isSelected = true;
                        theController.subsCriptionItems[0].cancellationReason = 'Didn\'t like';
                       
                        theController.createTask();
                Test.stopTest();
            }
            List<Task> createdTasks = [SELECT Id , Subject FROM Task WHERE WhoId =:testContact.Id];
            System.assertEquals(1 , createdTasks.size() , '1 task should have been created');
            List<Contact> contacts = [SELECT Id , Lead_Status__c , ownerId ,Contact_Status__c  FROM Contact Where Id = :testContact.Id];
            System.assertEquals(1 , contacts.size() , '1 Contact should have been returned');
            System.assertEquals(QUALIFIED_INTERESTED , contacts[0].Lead_Status__c , 'Right Lead status should have been populated');
            System.assertEquals( COMMISSION_CONTACT_STATUS , contacts[0].Contact_Status__c , 'Right Lead status should have been populated');
            System.assertEquals(theUser.Id , contacts[0].ownerId , 'Right owner Id should have been populated.Lead should have been assigned to User');

            List<Order360__c> order360sCreated = [SELECT Id , Reason_for_cancellation__c  FROM Order360__c WHERE Parent_Order_Item__c = :testOrderItem.Id];

            System.assertEquals(1 , order360sCreated.size() , '1 Order 360 record should have been created');
            System.assertEquals('Didn\'t like' , order360sCreated[0].Reason_for_cancellation__c , 'Right reason for cancellation should have been populated');
        }
        
        static testMethod void testCreateSubscriptionSaveTask_WithEmail()
        {
            Account testAccount = TestUtils.createAccounts(1 , 'Test Account' , true)[0];
            Contact testContact = TestUtils.createContacts(1 , 'Test Contact' , testAccount.Id , true)[0];
          
            
            Order__c testOrder = TestUtils.createOrders(1, null , false)[0];
            testOrder.Contact__c = testContact.Id;
            insert testOrder;
            
            Order_Item__c testOrderItem = TestUtils.createOrderItems(1, testOrder.Id ,  false)[0];
            testOrderItem.Subscription_Status__c = 'Active';
            insert testOrderItem;


            User theUser = TestUtils.createUser('TestUser', TestUtils.salesAgentProfileId , false);
            
            System.runAs(theUser)
            {
                
                
                ApexPages.StandardController sc = new ApexPages.StandardController(testContact);
                LogCallContactController theController = new LogCallContactController(sc);
                PageReference pageRef = Page.LogCallContact;
                pageRef.getParameters().put('id', String.valueOf(testContact.Id));
                Test.setCurrentPage(pageRef);
                
                Test.startTest();
                        
                        
                        theController.SubscriptionItems = theController.SubscriptionItems; 
                        theController.theTask.Lead_Status__c = LEAD_STATUS;
                        theController.theTask.Contact_Status__c = COMMISSION_CONTACT_STATUS;
                        theController.theTask.Is_Subscription_Activity__c  = true;
                        theController.subscriptionItems[0].isSelected = true;
                        theController.createEmailTask();
                Test.stopTest();
            }
            List<Task> createdTasks = [SELECT Id , Subject FROM Task WHERE WhoId =:testContact.Id];
            System.assertEquals(1 , createdTasks.size() , '1 task should have been created');
            List<Contact> contacts = [SELECT Id , Lead_Status__c , ownerId ,Contact_Status__c  FROM Contact Where Id = :testContact.Id];
            System.assertEquals(1 , contacts.size() , '1 Contact should have been returned');
            System.assertEquals(QUALIFIED_INTERESTED , contacts[0].Lead_Status__c , 'Right Lead status should have been populated');
            System.assertEquals( COMMISSION_CONTACT_STATUS , contacts[0].Contact_Status__c , 'Right Lead status should have been populated');
            System.assertEquals(theUser.Id , contacts[0].ownerId , 'Right owner Id should have been populated.Lead should have been assigned to User');

            List<Order360__c> order360sCreated = [SELECT Id FROM Order360__c WHERE Parent_Order_Item__c = :testOrderItem.Id];

            System.assertEquals(1 , order360sCreated.size() , '1 Order 360 record should have been created');
        }
}