src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <label>User Order ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderID__c</fullName>
        <externalId>true</externalId>
        <label>OrderID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order_Date_Time_Created__c</fullName>
        <description>Store the created date time of the order created in LZ Data</description>
        <label>Order Date/Time Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order_Date_Time_Modified__c</fullName>
        <description>DateTime when the Order gets modified.</description>
        <label>Order Date/Time Modified</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>State_of_Formation__c</fullName>
        <label>State of Formation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/IADRefundInstallmentTest_ltng.cls
@istest private class IADRefundInstallmentTest_ltng
{
static Contact con;
    static Order__c order;

    public static void setupData() 


  {
        con = new Contact(FirstName = 'John', LastName = 'Doer', Phone = '4444', MobilePhone = '123456789');
        insert con;
        
        order = new Order__c(Name = '1000', OrderID__c = '1000', Contact__c = con.Id, State_of_Formation__c = '11', Entity_Name__c = '12', Order_Date_Time_Created__c = DateTime.newInstance(2015, 12, 07, 12, 12, 01), Order_Date_Time_Modified__c = DateTime.newInstance(2015, 12, 08, 12, 12, 01), User_Order_ID__c='123');
        insert order;
    }


 static testMethod void testGetOrderBalanceByOrderIdPositive(){
        IADOrderWithOrderItemsService_ltng orderService = new IADOrderWithOrderItemsService_ltng();
        IADServiceBase_ltng.APItoAsync.put(IADOrderWithOrderItemsService_ltng.GETORDERBALANCESBYORDERID, true);
        IADTestMockGenerator mock = new IADTestMockGenerator();
        mock.testBody = IADTestDataUtil_ltng.getOrderBalanceResponse();
        mock.statusCode=200;
        Test.setMock(HttpCalloutMock.class, mock);        
        IADrefundInstallment_ltng.populateInstallments( '32546240');
    }
    
  static testMethod void testManualPostRefundPositiveCase()
    {
      setupData();
        IADTestMockGenerator mock = new IADTestMockGenerator();
        mock.testBody = IADTestDataUtil_ltng.postRefundResponse();
        mock.statusCode = 200;
        Test.setMock(HttpCalloutMock.class, mock);
        Test.starttest();
        IADrefundInstallment_ltng.processRefund(order.id,'10');
        test.stoptest();
    }
    static testMethod void testGetOrderBalanceByOrderIdNegative(){
        IADOrderWithOrderItemsService_ltng orderService = new IADOrderWithOrderItemsService_ltng();
        IADServiceBase_ltng.APItoAsync.put(IADOrderWithOrderItemsService_ltng.GETORDERBALANCESBYORDERID, true);
        IADTestMockGenerator mock = new IADTestMockGenerator();
        mock.testBody = IADTestDataUtil_ltng.getOrderBalanceResponse();
        mock.statusCode=400;
        Test.setMock(HttpCalloutMock.class, mock);        
        IADrefundInstallment_ltng.populateInstallments( '32546240');
    }
    
  static testMethod void testManualPostRefundNegativeCase()
    {
      setupData();
        IADTestMockGenerator mock = new IADTestMockGenerator();
        mock.testBody = IADTestDataUtil_ltng.postRefundResponse();
        mock.statusCode = 200;
        Test.setMock(HttpCalloutMock.class, mock);
        Test.starttest();
        IADrefundInstallment_ltng.processRefund(order.id,'10');
        test.stoptest();
    }

}