src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>FkUser__c</fullName>
        <externalId>true</externalId>
        <label>FkUser</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <label>User Order ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Date_Time_Created__c</fullName>
        <description>Store the created date time of the order created in LZ Data</description>
        <label>Order Date/Time Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order_Date_Time_Modified__c</fullName>
        <description>DateTime when the Order gets modified.</description>
        <label>Order Date/Time Modified</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>State_of_Formation__c</fullName>
        <label>State of Formation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/IADSubscriptionsPanelControllerTest.cls
@isTest
private class IADSubscriptionsPanelControllerTest {
    
    static Contact con1;
    static Order__c order1;
    static void setupData()
    {
            User u = [select id, profileid from User where name = 'Integration User' limit 1];

            system.runAs(u)
            {
                con1 = new Contact(FirstName = 'John', LastName = 'Doer', Phone = '4444', MobilePhone = '123456789', fkUser__c='1234');
                insert con1;

                order1 = new Order__c( Name = '1000', Contact__c = con1.Id, State_of_Formation__c = '11', Entity_Name__c = '12', Order_Date_Time_Created__c = DateTime.newInstance(2015, 12, 07, 12, 12, 01), Order_Date_Time_Modified__c = DateTime.newInstance(2015, 12, 08, 12, 12, 01), User_Order_ID__c='123');
                insert order1;
           }
    }

    static testMethod void testPopulateSubscriptionByorderId()
    {
        setupData();
        PageReference pageRef = Page.IADSubscriptionsPanelPage;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', order1.Id);
       
        IADSubscriptionsPanelController theController = new IADSubscriptionsPanelController();
        
        theController.subscriptionService.APItoAsync.put(IADSubscriptionPanelService.GETSUBSCRIPTIONSBYORDERID, true);

        //Async
        Continuation conti;

        theController.orderId = null;
        conti = (continuation)theController.populateSubscriptions(); //Exception Occurs

        theController.orderId = order1.Name;
        conti = (continuation)theController.populateSubscriptions(); 

        Map<String, HttpRequest> requests = conti.getRequests();
        System.assert(requests.size() == 1);
        APIRequestResponseWrapper apiresponse = theController.subscriptionService.APItoWrapper.get(IADSubscriptionPanelService.GETSUBSCRIPTIONSBYORDERID);
        System.assert(apiresponse != null);
        system.debug('response ' + apiresponse);

        HttpResponse response = new HttpResponse();
        String responseBody = IADTestDataUtil.getSubscriptionByOrderIdResponse();
        response.setBody(responseBody);
        response.setStatusCode(200);
        system.debug('responseBody-----'+responseBody);
        // Set the fake response for the continuation
        Test.setContinuationResponse(apiresponse.requestLabelContinuation , response);
        Object result = Test.invokeContinuationMethod(theController , conti);
        System.assertEquals(null, result);

        //For payment Profile API

        conti = (continuation)theController.populatePaymentProfiles();

        requests = conti.getRequests();
        System.assert(requests.size() == 1);
        apiresponse = theController.paymentProfileService.APItoWrapper.get(IADPaymentProfilesService.GETPROFILESBYUSERID);
        System.assert(apiresponse != null);
        system.debug('response ' + apiresponse);

        // Perform mock callout
        // (i.e. skip the callout and call the callback method)

        response = new HttpResponse();
        responseBody = IADTestDataUtil.getPaymentProfileResponse();
        response.setBody(responseBody);
        response.setStatusCode(200);
        system.debug('responseBody-----'+responseBody);
        // Set the fake response for the continuation
        Test.setContinuationResponse(apiresponse.requestLabelContinuation , response);
        result = Test.invokeContinuationMethod(theController , conti);
        System.assertEquals(null, result);
    

    }


    
}