src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>FkUser__c</fullName>
        <externalId>true</externalId>
        <label>FkUser</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <label>User Order ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Date_Time_Created__c</fullName>
        <description>Store the created date time of the order created in LZ Data</description>
        <label>Order Date/Time Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order_Date_Time_Modified__c</fullName>
        <description>DateTime when the Order gets modified.</description>
        <label>Order Date/Time Modified</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>State_of_Formation__c</fullName>
        <label>State of Formation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/IADRelatedorders_test.cls
@istest
private class IADRelatedorders_test
{

@isTest static void setupData()
    {
        User u = [select id, profileid from User where name = 'Integration User' limit 1];
        Order__c order1 ;
        system.runAs(u)
        {

            Contact con1 = new Contact(FirstName = 'John', LastName = 'Doer', Phone = '4444', MobilePhone = '123456789', fkUser__c='1234');
            insert con1;

           order1 = new Order__c( Name = '1234', Contact__c = con1.Id, State_of_Formation__c = '11', Entity_Name__c = '12', Order_Date_Time_Created__c = DateTime.newInstance(2015, 12, 07, 12, 12, 01), Order_Date_Time_Modified__c = DateTime.newInstance(2015, 12, 08, 12, 12, 01), User_Order_ID__c='1234');
            insert order1;
        }
        
    }
    
    
      
      @isTest static void testRelatedOrdersorderresponse()
    {
        User u = [select id, profileid from User where name = 'Integration User' limit 1];
        Order__c order1 ;
        system.runAs(u)
        {

            Contact con1 = new Contact(FirstName = 'John', LastName = 'Doer', Phone = '4444', MobilePhone = '123456789', fkUser__c='1234');
            insert con1;

           order1 = new Order__c( Name = '1234', Contact__c = con1.Id, State_of_Formation__c = '11', Entity_Name__c = '12', Order_Date_Time_Created__c = DateTime.newInstance(2015, 12, 07, 12, 12, 01), Order_Date_Time_Modified__c = DateTime.newInstance(2015, 12, 08, 12, 12, 01), User_Order_ID__c='1234');
            insert order1;
        }
        
        RelatedOrdersController_ltng   inst = new   RelatedOrdersController_ltng  ();
        IADTestMockGenerator mock = new IADTestMockGenerator();
      mock.testBody =   IADTestDataUtil_ltng.getOrderResponse();
      mock.statusCode=200;
        Test.startTest();
         Test.setMock(HttpCalloutMock.class, mock);
         RelatedOrdersController_ltng.getOrderByOrderId(order1.id);
        Test.stopTest();

    }

  @isTest static void testRelatedOrdersresponse()
    {
       
        
        RelatedOrdersController_ltng   inst = new   RelatedOrdersController_ltng  ();
        IADTestMockGenerator mock = new IADTestMockGenerator();
      mock.testBody =IADTestDataUtil_ltng.getRelatedOrdersResponse();
      mock.statusCode=200;
        Test.startTest();
         Test.setMock(HttpCalloutMock.class, mock);
         RelatedOrdersController_ltng.getRelatedOrders('1234');
        Test.stopTest();

    }
    
      @isTest static void testRelatedOrdersorderresponsenegative()
    {
        User u = [select id, profileid from User where name = 'Integration User' limit 1];
        Order__c order1 ;
        system.runAs(u)
        {

            Contact con1 = new Contact(FirstName = 'John', LastName = 'Doer', Phone = '4444', MobilePhone = '123456789', fkUser__c='1234');
            insert con1;

           order1 = new Order__c( Name = '1234', Contact__c = con1.Id, State_of_Formation__c = '11', Entity_Name__c = '12', Order_Date_Time_Created__c = DateTime.newInstance(2015, 12, 07, 12, 12, 01), Order_Date_Time_Modified__c = DateTime.newInstance(2015, 12, 08, 12, 12, 01), User_Order_ID__c='1234');
            insert order1;
        }
        
        RelatedOrdersController_ltng   inst = new   RelatedOrdersController_ltng  ();
        IADTestMockGenerator mock = new IADTestMockGenerator();
      mock.testBody =   IADTestDataUtil_ltng.getOrderResponse();
      mock.statusCode=500;
        Test.startTest();
         Test.setMock(HttpCalloutMock.class, mock);
         RelatedOrdersController_ltng.getOrderByOrderId(order1.id);
        Test.stopTest();

    }

  @isTest static void testRelatedOrdersresponsenegative()
    {
       
        
        RelatedOrdersController_ltng   inst = new   RelatedOrdersController_ltng  ();
        IADTestMockGenerator mock = new IADTestMockGenerator();
      mock.testBody =IADTestDataUtil_ltng.getRelatedOrdersResponse();
      mock.statusCode=500;
        Test.startTest();
         Test.setMock(HttpCalloutMock.class, mock);
         RelatedOrdersController_ltng.getRelatedOrders('1234');
        Test.stopTest();

    }

   @isTest static void testRelatedOrdersorderresponsenegative1()
    {
        User u = [select id, profileid from User where name = 'Integration User' limit 1];
        Order__c order1 ;
        system.runAs(u)
        {

            Contact con1 = new Contact(FirstName = 'John', LastName = 'Doer', Phone = '4444', MobilePhone = '123456789', fkUser__c='1234');
            insert con1;

           order1 = new Order__c( Name = '1234', Contact__c = con1.Id, State_of_Formation__c = '11', Entity_Name__c = '12', Order_Date_Time_Created__c = DateTime.newInstance(2015, 12, 07, 12, 12, 01), Order_Date_Time_Modified__c = DateTime.newInstance(2015, 12, 08, 12, 12, 01), User_Order_ID__c='1234');
            insert order1;
        }
        
        RelatedOrdersController_ltng   inst = new   RelatedOrdersController_ltng  ();
        IADTestMockGenerator mock = new IADTestMockGenerator();
      mock.testBody =   IADTestDataUtil_ltng.getOrderResponse();
      mock.statusCode=500;
        Test.startTest();
         Test.setMock(HttpCalloutMock.class, mock);
         RelatedOrdersController_ltng.getOrderByOrderId('');
        Test.stopTest();

    }

  @isTest static void testRelatedOrdersresponsenegative1()
    {
       
        
        RelatedOrdersController_ltng   inst = new   RelatedOrdersController_ltng  ();
        IADTestMockGenerator mock = new IADTestMockGenerator();
      mock.testBody =IADTestDataUtil_ltng.getRelatedOrdersResponse();
      mock.statusCode=500;
        Test.startTest();
         Test.setMock(HttpCalloutMock.class, mock);
         RelatedOrdersController_ltng.getRelatedOrders('');
        Test.stopTest();

    }


}