src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>FkUser__c</fullName>
        <externalId>true</externalId>
        <label>FkUser</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <label>User Order ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Date_Time_Created__c</fullName>
        <description>Store the created date time of the order created in LZ Data</description>
        <label>Order Date/Time Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order_Date_Time_Modified__c</fullName>
        <description>DateTime when the Order gets modified.</description>
        <label>Order Date/Time Modified</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>State_of_Formation__c</fullName>
        <label>State of Formation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/IADPaymentProfileLabelControllerTest.cls
/**
 * Created by jboles on 11/30/2016.
 */
@isTest
private class IADPaymentProfileLabelControllerTest 
{
    @isTest static void setupData()
    {
        User u = [select id, profileid from User where name = 'Integration User' limit 1];

        system.runAs(u)
        {

            Contact con1 = new Contact(FirstName = 'John', LastName = 'Doer', Phone = '4444', MobilePhone = '123456789', fkUser__c='1234');
            insert con1;

            Order__c order1 = new Order__c( Name = '1000', Contact__c = con1.Id, State_of_Formation__c = '11', Entity_Name__c = '12', Order_Date_Time_Created__c = DateTime.newInstance(2015, 12, 07, 12, 12, 01), Order_Date_Time_Modified__c = DateTime.newInstance(2015, 12, 08, 12, 12, 01), User_Order_ID__c='123');
            insert order1;
        }

    }
    @isTest static void testGetPayment()
    {
        setupData();

        PageReference pageRef = Page.IADEditPaymentPage;
        Test.setCurrentPage(pageRef);



        IADPaymentProfileLabelController theController = new IADPaymentProfileLabelController();
        theController.paymentProfileId = '1234';
        //Async
        Continuation conti = (continuation)theController.populatePaymentProfile();

        Map<String, HttpRequest> requests = conti.getRequests();
        System.assert(requests.size() == 1);
        APIRequestResponseWrapper apiresponse = theController.dataService.APItoWrapper.get(IADEditPaymentService.GETPROFILEBYID);
        System.assert(apiresponse != null);
        system.debug('response ' + apiresponse);

        // Perform mock callout
        // (i.e. skip the callout and call the callback method)

        HttpResponse response = new HttpResponse();
        String responseBody = IADTestDataUtil.getPaymentProfileResponse();
        response.setBody(responseBody);
        response.setStatusCode(200);
        system.debug('responseBody-----'+responseBody);
        // Set the fake response for the continuation
        Test.setContinuationResponse(apiresponse.requestLabelContinuation , response);
        Object result = Test.invokeContinuationMethod(theController , conti);
        System.assertEquals(null, result);

        //errors

        response = new HttpResponse();
        responseBody = '';
        response.setBody(responseBody);
        response.setStatusCode(200);
        system.debug('responseBody-----'+responseBody);
        // Set the fake response for the continuation
        Test.setContinuationResponse(apiresponse.requestLabelContinuation , response);
        result = Test.invokeContinuationMethod(theController , conti);
        System.assertEquals(null, result);

        response = new HttpResponse();
        responseBody = '';
        response.setBody(responseBody);
        response.setStatusCode(500);
        system.debug('responseBody-----'+responseBody);
        // Set the fake response for the continuation
        Test.setContinuationResponse(apiresponse.requestLabelContinuation , response);
        result = Test.invokeContinuationMethod(theController , conti);
        System.assertEquals(null, result);


    }
    @isTest static void testErrors()
    {
        setupData();

        PageReference pageRef = Page.IADEditPaymentPage;
        Test.setCurrentPage(pageRef);

        Test.startTest();
        IADPaymentProfileLabelController theController = new IADPaymentProfileLabelController();
        theController.paymentProfileId = '1234';

        try{
            theController.dataService = null;
            theController.populatePaymentProfile();
        }
        catch(exception e){}
        try{
            theController.dataService = null;
            theController.processProfile();
        }
        catch(exception e){}

        Test.stopTest();

    }
}