src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VM Attempt 1</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 2</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 3</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 4</fullName>
                </value>
                <value>
                    <fullName>VM Final Attempt</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Commission Eligible</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Ineligible</fullName>
                </value>
                <value>
                    <fullName>Call Transferred</fullName>
                </value>
                <value>
                    <fullName>Service Unavailable</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Authorized Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>--None--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FkUser__c</fullName>
        <externalId>true</externalId>
        <label>FkUser</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Authorized Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FkUser__c</fullName>
        <externalId>true</externalId>
        <label>FkUser</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Call_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Voicemail</fullName>
                </value>
                <value>
                    <fullName>No Message</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Spoke</fullName>
                </value>
                <value>
                    <fullName>VM Attempt 1</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 2</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 3</fullName>
                </value>
                <value>
                    <fullName>NM Attempt 4</fullName>
                </value>
                <value>
                    <fullName>VM Final Attempt</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Commission Eligible</fullName>
                </value>
                <value>
                    <fullName>Contacted/Spoke - Ineligible</fullName>
                </value>
                <value>
                    <fullName>Call Transferred</fullName>
                </value>
                <value>
                    <fullName>Service Unavailable</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <label>Lead Source Detail</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Services</fullName>
                </value>
                <value>
                    <fullName>Attorney Services</fullName>
                </value>
                <value>
                    <fullName>Quick Start</fullName>
                </value>
                <value>
                    <fullName>ADP</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Sam&apos;s Club</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MobileCampaignTest.cls
@isTest
public with sharing class MobileCampaignTest 
{
    static List<Lead> testLeads;
    static Integer SIZE = 200;
    public final static String BUSINESS_SERVICES = 'Business Services';
    static void setupData()
    {
        testLeads = TestUtils.createLeads(SIZE , 'Test Lead', false);
        for(Integer i = 0 ; i<SIZE ; ++i)
        {
            testLeads[i].Company = 'testEmail@test.test'+i;
            testLeads[i].LeadSource = 'Mobile';
            testLeads[i].Lead_Source_Detail__c = BUSINESS_SERVICES;
        }

    }
    
    static testMethod void testMobileCampaignWithLead_NoMatchWithContact_Entry()
    {
        CampaignRulesSetup.setupCampaignWithRules();
        setupData();
        Test.startTest();
             insert testLeads;   
        Test.stopTest();
        List<CampaignMember> campaignMembers = [SELECT Id FROM CampaignMember WHERE LeadId IN :testLeads];
        System.assertEquals(SIZE , campaignMembers.size() , '200 CampaignMembers should have been created');
        
    }
    
    
    static testMethod void testMobileCampaignWithLead_MatchWithContact_Entry()
    {
        CampaignRulesSetup.setupCampaignWithRules();
        setupData();
        List<Contact> testContacts = TestUtils.createContacts(SIZE/2 , 'Test Contact', null , false);
        for(Integer i = 0 ; i<SIZE/2; ++i)
        {
            testContacts[i].FkUser__c = i+'';
            testContacts[i].Email = 'testEmail@test.test'+i;
            testContacts[i].Contact_Type__c = 'Primary Contact'; 
           
        }
        insert testContacts;

        Test.startTest();
             insert testLeads;   
        Test.stopTest();
        List<CampaignMember> campaignMembers = [SELECT Id FROM CampaignMember WHERE ContactId IN :testContacts];
        System.assertEquals(SIZE/2 , campaignMembers.size() , '100 CampaignMembers should have been created');
        
    }
    
    static testMethod void testMobileCampaignWithLead_Exit()
    {
        CampaignRulesSetup.setupCampaignWithRules();
        setupData();
        insert testLeads;

        for(Lead theLead : testLeads)
        {
            theLead.Lead_Call_Status__c = CampaignConstants.VM_FINAL;
        }

        Test.startTest();
            update testLeads;           
        Test.stopTest();
        List<CampaignMember> campaignMembers = [SELECT Id FROM CampaignMember WHERE Status = :CampaignConstants.REMOVED AND LeadId IN :testLeads];
        System.assertEquals(SIZE , campaignMembers.size() , '200 CampaignMembers should have been removed');
        
    }
    
    static testMethod void testMobileCampaignWithContact_Exit()
    {
        CampaignRulesSetup.setupCampaignWithRules();
        setupData();
        List<Contact> testContacts = TestUtils.createContacts(SIZE , 'Test Contact', null , false);
        for(Integer i = 0 ; i<SIZE; ++i)
        {
            testContacts[i].FkUser__c = i+'';
            testContacts[i].Email = 'testEmail@test.test'+i;
            testContacts[i].Contact_Type__c = 'Primary Contact'; 
        }
        insert testContacts;
        insert testLeads;   

        for(Contact theContact : testContacts)
        {
            theContact.Contact_Status__c = CampaignConstants.VM_FINAL;
        }

        Test.startTest();
             update testContacts;
        Test.stopTest();
        List<CampaignMember> campaignMembers = [SELECT Id FROM CampaignMember WHERE Status =  :CampaignConstants.REMOVED AND ContactId IN :testContacts];
        System.assertEquals(SIZE , campaignMembers.size() , '200 CampaignMembers should have been removed');
        
    }
    
    static testMethod void testMobileCampaignWithContact_WithOrderPlaced_Exit()
    {
        CampaignRulesSetup.setupCampaignWithRules();
        setupData();
        List<Contact> testContacts = TestUtils.createContacts(SIZE , 'Test Contact', null , false);
        for(Integer i = 0 ; i<SIZE; ++i)
        {
            testContacts[i].FkUser__c = i+'';
            testContacts[i].Email = 'testEmail@test.test'+i;
            testContacts[i].Contact_Type__c = 'Primary Contact'; 
        }
        insert testContacts;
        insert testLeads;
        List<Order__c> testOrders = new List<Order__c>();


        for(Contact theContact : testContacts)
        {
            Order__c theOrder = TestUtils.createOrders(1 , null , false)[0];
            theOrder.Contact__c = theContact.Id; 
            testOrders.add(theOrder);           
        }

        Test.startTest();
             insert testOrders;
        Test.stopTest();
        List<CampaignMember> campaignMembers = [SELECT Id FROM CampaignMember WHERE Status =  :CampaignConstants.ORDER_PLACED AND ContactId IN :testContacts];
        System.assertEquals(SIZE , campaignMembers.size() , '200 CampaignMembers should have been removed');
        
    }
    
    
}