src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Authorized Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>--None--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <label>User Order ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Authorized Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line (Obsolete)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Intellectual Property</fullName>
                </value>
                <value>
                    <fullName>Personal Services</fullName>
                </value>
                <value>
                    <fullName>Attorney Services</fullName>
                </value>
                <value>
                    <fullName>Business Formations</fullName>
                </value>
                <value>
                    <fullName>Legal Forms</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DBA</fullName>
                </value>
                <value>
                    <fullName>LLC</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Attorney Consultation Requests</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Business Advantage Pro Standalone</fullName>
                </value>
                <value>
                    <fullName>Consultation Subscription</fullName>
                </value>
                <value>
                    <fullName>Consultation Subscription Renewal</fullName>
                </value>
                <value>
                    <fullName>Forms Subscription</fullName>
                </value>
                <value>
                    <fullName>Forms Subscription Renewal</fullName>
                </value>
                <value>
                    <fullName>Legal Advantage Plus Standalone</fullName>
                </value>
                <value>
                    <fullName>Legal Form</fullName>
                </value>
                <value>
                    <fullName>OCAA Plans</fullName>
                </value>
                <value>
                    <fullName>501(c)3 Preparation</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Annual Reports</fullName>
                </value>
                <value>
                    <fullName>Bylaws &amp; Resolutions</fullName>
                </value>
                <value>
                    <fullName>Certificate of Good Standing</fullName>
                </value>
                <value>
                    <fullName>Certified Copies</fullName>
                </value>
                <value>
                    <fullName>Compliance Calendar</fullName>
                </value>
                <value>
                    <fullName>Compliance Calendar Renewal</fullName>
                </value>
                <value>
                    <fullName>Conversion</fullName>
                </value>
                <value>
                    <fullName>Corporate Dissolution</fullName>
                </value>
                <value>
                    <fullName>Corporate Minutes</fullName>
                </value>
                <value>
                    <fullName>EIN Obtainment</fullName>
                </value>
                <value>
                    <fullName>Entity Name Availability Check</fullName>
                </value>
                <value>
                    <fullName>Entity Name Reservation</fullName>
                </value>
                <value>
                    <fullName>Foreign Qualification</fullName>
                </value>
                <value>
                    <fullName>General Partnership Agreement</fullName>
                </value>
                <value>
                    <fullName>Registered Agent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>User Order ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order360__c.object
<CustomObject>
    <fields>
        <fullName>Order_Date_Time_Created__c</fullName>
        <formula>Order__r.Date_Time_Created__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order Date/Time Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipName>Order360</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Matching_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Matching Activity</label>
        <referenceTo>Order_Matching_Activity__c</referenceTo>
        <relationshipName>Order360</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Order360</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Active Revenue</label>
    <nameField>
        <displayFormat>Ord360-{0000}</displayFormat>
        <label>Order360 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Active Revenue</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LZ_Product_ID__c</fullName>
        <formula>Text(Order_Item__r.Product__r.LZ_Product_ID__c)</formula>
        <label>LZ Product ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderID__c</fullName>
        <externalId>true</externalId>
        <label>OrderID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order_Date_Time_Created__c</fullName>
        <description>Store the created date time of the order created in LZ Data</description>
        <label>Order Date/Time Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <formula>Base_Product__r.Product_Line__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Base_Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>LZ_Product_ID__c</fullName>
        <formula>Text( Product__r.LZ_Product_ID__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LZ Product ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <description>Product Name at the time of the order item is created.</description>
        <inlineHelpText>Product Name at the time of the order item is created.</inlineHelpText>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <description>matching the fkUserOrder field of OrderItem table in lzdata</description>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order_Matching_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Order Matching Activities</relationshipLabel>
        <relationshipName>Order_Matching_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>OrderLeadOpportunitys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Matching Activity</label>
    <nameField>
        <displayFormat>Match-{0000}</displayFormat>
        <label>Order Matching Activity  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Matching Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LZ_Product_ID__c</fullName>
        <description>matching pkProductConfiguration column of ProductConfiguation table in LZData</description>
        <externalId>true</externalId>
        <label>LZ Product ID</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Line</label>
        <referenceTo>Product_Line__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/RA_Renewal_Product_Name__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List all the RA Renewal Product that should be considered for RA commission matching</description>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RA Renewal Product Name</label>
</CustomObject>

src/classes/OrderItemMatchingRenewalTest.cls
@isTest
public class OrderItemMatchingRenewalTest 
{
    static List<Order__c> parentOrders;
    static List<Order__c> renewalOrders;

    static List<Lead> testLeads;
    
    static List<Account> testAccounts;
    static List<Order_Matching_Activity__c> testOrderMatchingActivities;
    static List<Task> tasksToCreate;
    
    static final String ABANDONER = 'Abandoner';
    static Id abandonerRecordTypeId;
    static User testUser;
    static Product2 testProduct;
    final static String PRODUCT_LINE = 'Test ProductLine';
    static Id relationshipTypeId;
    static Id renewalRelationshipTypeId;
    static Id packageRelationshipTypeId;
    
    
    static Product2 renewalProduct;
    static Product2 registerAgentProduct;
    static final String REGISTERED_AGENT = 'Registered Agent';
    static final String THEPACKAGE = 'Package';
    static final String CROSS_SELL = 'Cross-Sell';
    
    
    static List<RA_Renewal_Product_Name__c> RARenewalProducts;
    static Relationship_Type__c packageRelationshipType;
    static Relationship_Type__c crossSellRelationshipType;
    static List<Contact> testContacts;
    final static String PRIMARY_CONTACT = 'Primary Contact';

    
    static
    {
        OrderService.hasOrderMatchingTriggerRun = true;
        testUser = TestUtils.createUser( 'Austin', TestUtils.STANDARD_PROFILE_ID , true);
        User firstCommissionUser = TestUtils.createUser( 'Bonjovi', TestUtils.STANDARD_PROFILE_ID , true);

        RARenewalProducts = new List<RA_Renewal_Product_Name__c>();
        RA_Renewal_Product_Name__c theRARenewalProduct = new RA_Renewal_Product_Name__c();
        theRARenewalProduct.Name = '1';
        theRARenewalProduct.Product_Name__c = 'RA Renewal - 1 year';
        RARenewalProducts.add(theRARenewalProduct);
        
        insert RARenewalProducts;
        
        abandonerRecordTypeId = OrderService.developerNameToRecordTypeIds.get(ABANDONER); 
        tasksToCreate= new List<Task>();
        
        testProduct = TestUtils.createProducts(1 , 'Test Product', false)[0];
        testProduct.Name = '1';
        testProduct.LZ_Product_ID__c = 1;
        Product_Line__c testProductLine = TestUtils.createProductLines(1 , PRODUCT_LINE , false)[0];
        testProductLine.Name = PRODUCT_LINE;
        insert testProductLine;
        
        relationshipTypeId = TestUtils.createRelationshipTypesTypes(1 , 'Process', true)[0].Id;
        testProduct.Product_Line__c = testProductLine.Id;
        testProduct.Relationship_Type__c = relationshipTypeId;
        
        renewalProduct = TestUtils.createProducts(1 , 'Renewal Product', false)[0];
        renewalProduct.Name = 'RA Renewal - 1 year';
        renewalProduct.LZ_Product_ID__c = 2;
        
        Relationship_Type__c renewalRelationshipType = TestUtils.createRelationshipTypesTypes(1 , 'Renewal', false)[0];
        renewalRelationshipType.Name = 'Renewal';
        
        insert renewalRelationshipType;
        
        renewalProduct.Product_Line__c = testProductLine.Id;
        renewalProduct.Relationship_Type__c = renewalRelationshipType.Id;
        
        
        registerAgentProduct = TestUtils.createProducts(1 , REGISTERED_AGENT, false)[0];
        registerAgentProduct.Name = REGISTERED_AGENT;
        registerAgentProduct.LZ_Product_ID__c = 3;
        
        packageRelationshipType = TestUtils.createRelationshipTypesTypes(1 , THEPACKAGE, false)[0];
        packageRelationshipType.Name = THEPACKAGE;
        
        insert packageRelationshipType;
        
        registerAgentProduct.Product_Line__c = testProductLine.Id;
        registerAgentProduct.Relationship_Type__c = packageRelationshipType.Id;
        
        
        insert new List<Product2>{registerAgentProduct , renewalProduct , testProduct};
  
    }
    


    static testMethod void testRARenewalOrdersForStandAloneOrders()
    {
        Account anotherAccount = TestUtils.createAccounts(1 , 'Test Account', false)[0];
        anotherAccount.Name = 'Test0@test.com';
        insert anotherAccount;
        
        testContacts = new List<Contact>();
        Contact firstContact = TestUtils.createContacts(1 , 'Test Contact', anotherAccount.Id, false)[0];
        firstContact.HomePhone = '7777777777';
        firstContact.Contact_Type__c = PRIMARY_CONTACT;
        testContacts.add(firstContact);
        insert testContacts;

        parentOrders = TestUtils.createOrders(50 , testProduct.Id ,  false);
        for(Integer i =0 ; i<50; ++i) 
        {
            parentOrders[i].OrderID__c = String.valueOf(i);
            parentOrders[i].Name = String.valueOf(i);
            parentOrders[i].User_Order_ID__c = String.valueOf(i);
            parentOrders[i].Order_Date_Time_Created__c = DateTime.now().addHours(5);
            parentOrders[i].Contact__c = testContacts[0].Id;            
        }
        insert parentOrders;
        
        List<Order_Item__c> orderItemsToCreate = new List<Order_Item__c>();
        for(Order__c theOrder : parentOrders)
        {
            Order_Item__c theItem = TestUtils.createOrderItems(1 , theOrder.Id , false)[0];
            theItem.Product__c = registerAgentProduct.Id;
            theItem.Relationship_Type__c = packageRelationshipType.Id;
            orderItemsToCreate.add(theItem);
        }
        insert orderItemsToCreate;
        
        
        renewalOrders = TestUtils.createOrders(50 , renewalProduct.Id ,  false);
        for(Integer i =0 ; i<50 ;++i)
        {
            renewalOrders[i].OrderID__c = String.valueOf(i)+'renewal';
            renewalOrders[i].Name = String.valueOf(i)+'renewal';
            renewalOrders[i].Base_Product__c =  renewalProduct.Id;
            renewalOrders[i].LZ_Parent_Order__c = String.valueOf(i);
            renewalOrders[i].Account__c = anotherAccount.Id;
            renewalOrders[i].Contact_Email__c = anotherAccount.Name;
            renewalOrders[i].Order_Date_Time_Created__c = DateTime.now().addHours(8);
            renewalOrders[i].Order_Created_By__c = 'abc';
            renewalOrders[i].Contact__c = testContacts[0].Id; 
        }
        insert renewalOrders;
        List<Order_Item__c> renewalorderItemsToCreate = new List<Order_Item__c>();
        for(Order__c theOrder : renewalOrders)
        {
            Order_Item__c theItem = TestUtils.createOrderItems(1 , theOrder.Id , false)[0];
            theItem.Product__c = registerAgentProduct.Id;
            theItem.Relationship_Type__c = packageRelationshipType.Id;
            renewalorderItemsToCreate.add(theItem);
        }
        
        System.runAs(testUser)
        {
            for(Contact theContact : testContacts)
            {
                Task theTask = TestUtils.createTasks(1 , null, false)[0];
                theTask.WhoId = theContact.Id;
                theTask.Commission_Eligible__c = true;
                tasksToCreate.add(theTask);
            }
            insert tasksToCreate;
        }
                    
        Test.startTest();
            insert renewalorderItemsToCreate;
        Test.stopTest();
        List<Order_Matching_Activity__c> createdOMAs = [SELECT Id , Agent__c FROM Order_Matching_Activity__c WHERE Contact__c IN :testContacts];
        system.assertEquals(testContacts.size(), createdOMAs.size() , 'Right number of OMAs should have been created.1 for each Contact');

        List<Order360__c> newOrder360 = [Select Id, Agent__c , New_Logic__c FROM Order360__c Where Order_Item__c IN: renewalorderItemsToCreate];
        system.assertEquals(renewalorderItemsToCreate.size()*testContacts.size(), newOrder360.size() , 'Right number of Active revenue records should have been created');

        for(Order360__c theOrder360 : newOrder360)
        {
            system.assertEquals(true , theOrder360.New_Logic__c , 'Checkbox should be true since its new logic');
        }
    }
    
   
    static testMethod void testRARenewalOrdersForCrossSellOrders()
    {
        crossSellRelationshipType = TestUtils.createRelationshipTypesTypes(1 , CROSS_SELL, false)[0];
        crossSellRelationshipType.Name = CROSS_SELL;
        insert crossSellRelationshipType;
        
        registerAgentProduct.Relationship_Type__c = crossSellRelationshipType.Id;
        
        Account anotherAccount = TestUtils.createAccounts(1 , 'Test Account', false)[0];
        anotherAccount.Name = 'Test0@test.com';
        insert anotherAccount;

        testContacts = new List<Contact>();
        Contact firstContact = TestUtils.createContacts(1 , 'Test Contact', anotherAccount.Id, false)[0];
        firstContact.HomePhone = '7777777777';
        firstContact.Contact_Type__c = PRIMARY_CONTACT;
        testContacts.add(firstContact);
        insert testContacts;

        
        parentOrders = TestUtils.createOrders(50 , testProduct.Id ,  false);
        for(Integer i =0 ; i<50; ++i) 
        {
            parentOrders[i].OrderID__c = String.valueOf(i);
            parentOrders[i].Name = String.valueOf(i);
            parentOrders[i].User_Order_ID__c = String.valueOf(i);
            parentOrders[i].Order_Date_Time_Created__c = DateTime.now().addHours(5);
            parentOrders[i].Contact__c = testContacts[0].Id;                
        }
        insert parentOrders;
        
        List<Order_Item__c> orderItemsToCreate = new List<Order_Item__c>();
        for(Order__c theOrder : parentOrders)
        {
            Order_Item__c theItem = TestUtils.createOrderItems(1 , theOrder.Id , false)[0];
            theItem.Product__c = registerAgentProduct.Id;
            theItem.Relationship_Type__c = crossSellRelationshipType.Id;
            orderItemsToCreate.add(theItem);
        }

        System.runAs(testUser)
        {
            for(Contact theContact : testContacts)
            {
                Task theTask = TestUtils.createTasks(1 , null, false)[0];
                theTask.WhoId = theContact.Id;
                theTask.Commission_Eligible__c = true;
                tasksToCreate.add(theTask);
            }
            insert tasksToCreate;
        }
        
        insert orderItemsToCreate;
        List<Order360__c> oldOrder360 = [Select Id, Agent__c, Order__c, Order_Matching_Activity__c FROM Order360__c Where Order_Item__c IN: orderItemsToCreate];
        Map<Id,Id> parentorderIdtoOMAId = new Map<Id,Id>();
        for(Order360__c theOrder360 : oldOrder360)
        {
            parentorderIdtoOMAId.put(theorder360.Order__c,theorder360.Order_Matching_Activity__c);
        }
        
        renewalOrders = TestUtils.createOrders(50 , renewalProduct.Id ,  false);
        for(Integer i =0 ; i<50 ;++i)
        {
            renewalOrders[i].OrderID__c = String.valueOf(i)+'renewal';
            renewalOrders[i].Name = String.valueOf(i)+'renewal';
            renewalOrders[i].Base_Product__c =  renewalProduct.Id;
            renewalOrders[i].LZ_Parent_Order__c = String.valueOf(i);
            renewalOrders[i].Order_Created_By__c = 'abc';
            renewalOrders[i].Order_Date_Time_Created__c = DateTime.now().addHours(8);
            renewalOrders[i].Account__c = anotherAccount.Id;
            renewalOrders[i].Contact_Email__c = anotherAccount.Name;
            renewalOrders[i].Contact__c = testContacts[0].Id;
        }
        insert renewalOrders;

        List<Order_Item__c> renewalorderItemsToCreate = new List<Order_Item__c>();
        for(Order__c theOrder : renewalOrders)
        {
            Order_Item__c theItem = TestUtils.createOrderItems(1 , theOrder.Id , false)[0];
            theItem.Product__c = registerAgentProduct.Id;
            theItem.Relationship_Type__c = packageRelationshipType.Id;
            renewalorderItemsToCreate.add(theItem);
        }
            
        Test.startTest();
            insert renewalorderItemsToCreate;
        Test.stopTest();

        List<Order_Matching_Activity__c> createdOMAs = [SELECT Id , Agent__c FROM Order_Matching_Activity__c WHERE Contact__c IN :testContacts];
        System.assertEquals(testContacts.size(), createdOMAs.size() , 'Right number of OMAs should have been created.1 for each Contact');

         List<Order360__c> newOrder360 = [Select Id, Agent__c, Order__r.Parent_Order__c,Order_Matching_Activity__c,Order__c,Order_Item__c , New_Logic__c FROM Order360__c Where Order_Item__c IN: renewalorderItemsToCreate];
        System.assertEquals(renewalorderItemsToCreate.size()*testContacts.size(), newOrder360.size() , 'Right number of Active revenue records should have been created');
        
        for(Order360__c theOrder360 : newOrder360)
        {
            system.assertEquals(theorder360.Order_Matching_Activity__c , parentorderIdtoOMAId.get(theOrder360.Order__r.Parent_Order__c), 'Rhight Parent order OMA should have been matched');
            system.assertEquals(theorder360.Agent__c , 'Agent 1' , 'Agent field should have been populated to Agent 1');
            system.assertEquals(true , theOrder360.New_Logic__c , 'Checkbox should be true since its new logic');
        }       
    }


    static testMethod void testRARenewalOrdersForFirstCrossSellOrders()
    {
        crossSellRelationshipType = TestUtils.createRelationshipTypesTypes(1 , CROSS_SELL, false)[0];
        crossSellRelationshipType.Name = CROSS_SELL;
        insert crossSellRelationshipType;
        
        registerAgentProduct.Relationship_Type__c = crossSellRelationshipType.Id;
        
        Account anotherAccount = TestUtils.createAccounts(1 , 'Test Account', false)[0];
        anotherAccount.Name = 'Test0@test.com';
        insert anotherAccount;

        testContacts = new List<Contact>();
        Contact firstContact = TestUtils.createContacts(1 , 'Test Contact', anotherAccount.Id, false)[0];
        firstContact.HomePhone = '7777777777';
        firstContact.Contact_Type__c = PRIMARY_CONTACT;
        testContacts.add(firstContact);
        insert testContacts;

        
        parentOrders = TestUtils.createOrders(50 , testProduct.Id ,  false);
        for(Integer i =0 ; i<50; ++i) 
        {
            parentOrders[i].OrderID__c = String.valueOf(i);
            parentOrders[i].Name = String.valueOf(i);
            parentOrders[i].User_Order_ID__c = String.valueOf(i);
            parentOrders[i].Order_Date_Time_Created__c = DateTime.now().addHours(5);
            parentOrders[i].Contact__c = testContacts[0].Id;                
        }
        insert parentOrders;
        
        List<Order_Item__c> orderItemsToCreate = new List<Order_Item__c>();
        for(Order__c theOrder : parentOrders)
        {
            Order_Item__c theItem = TestUtils.createOrderItems(1 , theOrder.Id , false)[0];
            theItem.Product__c = registerAgentProduct.Id;
            theItem.Relationship_Type__c = crossSellRelationshipType.Id;
            orderItemsToCreate.add(theItem);
        }

        System.runAs(testUser)
        {
            for(Contact theContact : testContacts)
            {
                Task theTask = TestUtils.createTasks(1 , null, false)[0];
                theTask.WhoId = theContact.Id;
                theTask.Commission_Eligible__c = true;
                tasksToCreate.add(theTask);
            }
            insert tasksToCreate;
        }
        
        insert orderItemsToCreate;

        List<Order360__c> oldOrder360 = [Select Id, Agent__c, Order__c, Order_Matching_Activity__c FROM Order360__c Where Order_Item__c IN: orderItemsToCreate];
        Map<Id,Id> parentorderIdtoOMAId = new Map<Id,Id>();
        for(Order360__c theOrder360 : oldOrder360)
        {
            parentorderIdtoOMAId.put(theorder360.Order__c,theorder360.Order_Matching_Activity__c);
        }

        renewalOrders = TestUtils.createOrders(50 , renewalProduct.Id ,  false);
        for(Integer i =0 ; i<50 ;++i)
        {
            renewalOrders[i].OrderID__c = String.valueOf(i)+'renewal';
            renewalOrders[i].Name = String.valueOf(i)+'renewal';
            renewalOrders[i].Base_Product__c =  renewalProduct.Id;
            renewalOrders[i].LZ_Parent_Order__c = String.valueOf(i);
            renewalOrders[i].Order_Created_By__c = 'abc';
            renewalOrders[i].Order_Date_Time_Created__c = DateTime.now().addHours(8);
            renewalOrders[i].Account__c = anotherAccount.Id;
            renewalOrders[i].Contact_Email__c = anotherAccount.Name;
            renewalOrders[i].Contact__c = testContacts[0].Id; 
            renewalOrders[i].Parent_Order__c = parentOrders[i].Id; 
            renewalOrders[i].Is_First_RA_Renewal__c = true; 
        }
        insert renewalOrders;
        List<Order_Item__c> renewalorderItemsToCreate = new List<Order_Item__c>();
        for(Order__c theOrder : renewalOrders)
        {
            Order_Item__c theItem = TestUtils.createOrderItems(1 , theOrder.Id , false)[0];
            theItem.Product__c = registerAgentProduct.Id;
            theItem.Relationship_Type__c = packageRelationshipType.Id;
            renewalorderItemsToCreate.add(theItem);
        }
            
        Test.startTest();
            insert renewalorderItemsToCreate;
        Test.stopTest();

        List<Order_Matching_Activity__c> createdOMAs = [SELECT Id , Agent__c FROM Order_Matching_Activity__c WHERE Contact__c IN :testContacts];
        System.assertEquals(testContacts.size(), createdOMAs.size() , 'Right number of OMAs should have been created.1 for each Contact');

        List<Order360__c> newOrder360 = [Select Id, Agent__c, Order__r.Parent_Order__c,Order_Matching_Activity__c,Order__c,Order_Item__c , New_Logic__c FROM Order360__c Where Order_Item__c IN: renewalorderItemsToCreate];
        System.assertEquals(renewalorderItemsToCreate.size()*testContacts.size(), newOrder360.size() , 'Right number of Active revenue records should have been created');

        for(Order360__c theOrder360 : newOrder360)
        {
            system.assertEquals(theorder360.Order_Matching_Activity__c , parentorderIdtoOMAId.get(theOrder360.Order__r.Parent_Order__c), 'Rhight Parent order OMA should have been matched');
            system.assertEquals(theorder360.Agent__c , 'Agent 1' , 'Agent field should have been populated to Agent 1');
            system.assertEquals(true , theOrder360.New_Logic__c , 'Checkbox should be true since its new logic');
        }        
    }
    

}