src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <label>User Order ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IADApiGeeEndPoint__mdt.object
<CustomObject>
    <fields>
        <fullName>Is_Async__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this if the API call needs to be Asynchronous.Uses Continuation.</description>
        <label>Is Async?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GET</fullName>
                    <default>true</default>
                    <label>GET</label>
                </value>
                <value>
                    <fullName>PUT</fullName>
                </value>
                <value>
                    <fullName>POST</fullName>
                </value>
                <value>
                    <fullName>PATCH</fullName>
                </value>
                <value>
                    <fullName>DELETE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>link__c</fullName>
        <label>link</label>
        <type>Url</type>
    </fields>
    <label>IADApiGeeEndPoint</label>
    <pluralLabel>IADApiGeeEndPoints</pluralLabel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderID__c</fullName>
        <externalId>true</externalId>
        <label>OrderID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order_Date_Time_Created__c</fullName>
        <description>Store the created date time of the order created in LZ Data</description>
        <label>Order Date/Time Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order_Date_Time_Modified__c</fullName>
        <description>DateTime when the Order gets modified.</description>
        <label>Order Date/Time Modified</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>State_of_Formation__c</fullName>
        <label>State of Formation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/IADOrderStatusControllerTest.cls
/*Author : Padma S
 * Story : @B-22215 Kollaborate
 * Date  : 3/22/2018
 * Description: This is a test class for IADOrderStatusController
 */

@isTest
public class IADOrderStatusControllerTest {
     static Contact con1;
    static Order__c order1;
    
    public static void setupData() 
    {
        con1 = new Contact(FirstName = 'John', LastName = 'Doer', Phone = '4444', MobilePhone = '123456789');
        insert con1;
        
        order1 = new Order__c(Name = '1000', OrderID__c = '1000', Contact__c = con1.Id, State_of_Formation__c = '11', Entity_Name__c = '12', Order_Date_Time_Created__c = DateTime.newInstance(2015, 12, 07, 12, 12, 01), Order_Date_Time_Modified__c = DateTime.newInstance(2015, 12, 08, 12, 12, 01), User_Order_ID__c='123');
        insert order1;
    }
    
  
    static testMethod void IADorderStatusController1TEST(){
       
        
         //IADApiGeeEndPoint__mdt cmdt = [select label, Request_Type__c, link__c ,Is_Async__c from IADApiGeeEndPoint__mdt where label ='GetStatusPlan'];
         IADTestMockGenerator mock = new IADTestMockGenerator();    
        mock.testBody =IADTestDataUtil.getOrdersResponse();
        mock.statusCode=200;
        Test.setMock(HttpCalloutMock.class, mock);
       Map<string, Object> responseobj= IADOrderStatuscontroller.IADorderStatuscontroller1('123');
        
        
    }

}