src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Score__c</fullName>
        <formula>If(( Lead_score_time_sensitive_bucket_percent__c != 0 &amp;&amp; Lead_score_time_sensitive_bucket_total__c != 0 ),
(((( Lead_Score_Last_time_on_DBA_Q_Score__c + Lead_Score_Last_time_on_INC_Q_score__c + Lead_Score_Last_time_on_LLC_Q_score__c + Lead_Score_Last_time_on_NP_Q_score__c + Lead_score_last_time_on_website_score__c+Lead_Score_last_called_in_time_score__c+Lead_Score_last_emailed_in_time_score__c)/ Lead_score_time_sensitive_bucket_total__c )* Lead_score_time_sensitive_bucket_percent__c ) + Lead_Score_Non_Time_Sensitive__c + EP_Upsell_Score__c+Lead_Score_Mobile_time_since_creation__c),Lead_Score_Non_Time_Sensitive__c + EP_Upsell_Score__c + Lead_Score_Mobile_time_since_creation__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Authorized Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>--None--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FkUser__c</fullName>
        <externalId>true</externalId>
        <label>FkUser</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Authorized Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FkUser__c</fullName>
        <externalId>true</externalId>
        <label>FkUser</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Score__c</fullName>
        <formula>Lead_Score2__c+ If(( Lead_score_time_sensitive_bucket_percent__c != 0  &amp;&amp;  Lead_score_time_sensitive_bucket_total__c != 0 ),
(((( Lead_Score_Last_time_on_DBA_Q_Score__c +  Lead_Score_Last_time_on_INC_Q_score__c + Lead_Score_Last_time_on_LLC_Q_score__c + Lead_Score_Last_time_on_NP_Q_score__c + Lead_score_last_time_on_website_score__c+Lead_Score_last_called_in_time_score__c+Lead_Score_last_emailed_in_time_score__c)/ Lead_score_time_sensitive_bucket_total__c )* Lead_score_time_sensitive_bucket_percent__c ) + Lead_Score_Non_Time_Sensitive__c - Mobile_negitive_Score__c + Lead_Score_Mobile_time_since_creation__c +Created_Today_Score__c),Lead_Score_Non_Time_Sensitive__c + Lead_Score_Mobile_time_since_creation__c+Created_Today_Score__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lead Score x</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead_Attribute__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Lead_Scoring_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Criteria__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Criteria</label>
        <referenceTo>Lead_Scoring_Bucket_Criteria__c</referenceTo>
        <relationshipLabel>Lead Attributes</relationshipLabel>
        <relationshipName>Lead_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Scoring_Bucket__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Scoring Bucket</label>
        <referenceTo>Lead_Scoring_Bucket__c</referenceTo>
        <relationshipName>Lead_Scoring_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Lead Attribute</label>
    <nameField>
        <label>Lead Scoring Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead_Scoring_Bucket__c.object
<CustomObject>
    <fields>
        <fullName>Bucket_Percentage__c</fullName>
        <label>Bucket Percentage</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Lead Scoring Bucket</label>
    <nameField>
        <label>Lead Scoring Bucket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Scoring Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead_Scoring_Bucket_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lead_Scoring_Bucket__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Scoring Bucket</label>
        <referenceTo>Lead_Scoring_Bucket__c</referenceTo>
        <relationshipName>Lead_Scoring_Data_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Lead Scoring Bucket Criteria</label>
    <nameField>
        <label>Lead Scoring Bucket Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Scoring Bucket Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tealium_Request__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tealium Requests</relationshipLabel>
        <relationshipName>Tealium_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Matched_Field__c</fullName>
        <label>Matched Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Body__c</fullName>
        <label>Request Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Tealium Request</label>
    <nameField>
        <displayFormat>Request-{00000}</displayFormat>
        <label>Tealium Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tealium Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProcessScoringPointsTest.cls
@isTest
private class ProcessScoringPointsTest
{
    public static List<String> criteriaNames;
    public static void setupDate()
    {
        criteriaNames = new List<String> {'viewed_inc_pricing' , 'viewed_inc_overview' , 'viewed_llc_pricing' , 'viewed_llc_overview'};

        Lead_Scoring_Bucket__c bucket = new Lead_Scoring_Bucket__c();
        bucket.Name = 'Bucket1';
        bucket.Bucket_Percentage__c = 100;
        insert bucket;

        List<Lead_Scoring_Bucket_Criteria__c> criteriaToInsert = new List<Lead_Scoring_Bucket_Criteria__c>();
        for(integer i=0; i<criteriaNames.size(); i++)
        {
            Lead_Scoring_Bucket_Criteria__c  criteria = new Lead_Scoring_Bucket_Criteria__c();
            criteria.Name = criteriaNames[i]; 
            criteria.Active__c = True;
            criteria.Criteria__c = 'Test Criteria';
            criteria.Lead_Scoring_Bucket__c = bucket.Id; 
            criteria.Value__c = 'True,Test';
            criteria.points__c = 1;
            criteriaToInsert.add(criteria);
        }
        insert criteriaToInsert;
  
    }
    static testMethod void postScoringInformationLead()
    {
        setupDate();
        PageReference pageRef = Page.ScoringPoints;
        pageRef.getParameters().put('user_lname','testHttp');
        pageRef.getParameters().put('company','testCompany');
        pageRef.getParameters().put('user_email','testhttpPost@testHttpPost.com');
        pageRef.getParameters().put('user_id',' ');
        pageRef.getParameters().put('business_name','Test bussiness');
        pageRef.getParameters().put('formation_state','California');
        pageRef.getParameters().put('tealium_id',' ');
        pageRef.getParameters().put('business_phone','9909909999');
        pageRef.getParameters().put(criteriaNames[0],'true');
        pageRef.getParameters().put(criteriaNames[1],'true');
        pageRef.getParameters().put(criteriaNames[2],'true');
        pageRef.getParameters().put(criteriaNames[3],'true');

        Test.setCurrentPage(pageRef);
        Test.startTest();
              ProcessScoringPoints pointsProcessor = new ProcessScoringPoints();
              pointsProcessor.processUrlParameters();
        Test.stopTest();
        //Lead Score becomes 100+30 = 130.Any leads that are created today gets flat score of 30 on top od existing score.If that is changed
        //this assertion has to be adjusted
        List<Lead> insertedLead = [Select Id , Lead_Score__c , Email From Lead Where Email = 'testhttpPost@testHttpPost.com' Limit 1];
        system.assertEquals(130,insertedLead[0].Lead_Score__c);

        List<Lead_Attribute__c> insertedPoints = [Select Id From Lead_Attribute__c];
        system.assertEquals(4,insertedPoints.size());
    }

    static testMethod void postScoringInformationContact()
    {
        setupDate();
        Account theAccount =  TestUtils.createAccounts(1, 'Test Accoubt', true)[0];
        Contact theContact = TestUtils.createContacts(1, 'LeadScorinTest', theAccount.Id, true)[0];
        theContact.Email = 'contactEmial@leadScore.test';
        theContact.Phone = '9909909999';
        theContact.FkUser__c = '9966554';
        theContact.Contact_Type__c = 'Primary Contact';
        update theContact;
        PageReference pageRef = Page.ScoringPoints;
        pageRef.getParameters().put('user_lname','testHttp');
        pageRef.getParameters().put('company','testCompany');
        pageRef.getParameters().put('user_email','contactEmial@leadScore.test');
        pageRef.getParameters().put('user_id','9966554');
        pageRef.getParameters().put('business_name','Test bussiness');
        pageRef.getParameters().put('formation_state','California');
        pageRef.getParameters().put('tealium_id',' ');
        pageRef.getParameters().put('business_phone','9909909999');
        pageRef.getParameters().put(criteriaNames[0],'true');
        pageRef.getParameters().put(criteriaNames[1],'true');
        pageRef.getParameters().put(criteriaNames[2],'true');
        pageRef.getParameters().put(criteriaNames[3],'true');

        Test.setCurrentPage(pageRef);
        Test.startTest();
              ProcessScoringPoints pointsProcessor = new ProcessScoringPoints();
              pointsProcessor.processUrlParameters();
        Test.stopTest();

        List<Contact> insertedContact = [Select Id , Contact_Score__c , Email From Contact Where Email = 'contactEmial@leadScore.test' Limit 1];
        system.assertEquals(100,insertedContact[0].Contact_Score__c);

        List<Lead_Attribute__c> insertedPoints = [Select Id,points__c, Contact__c From Lead_Attribute__c];
        system.assertEquals(4,insertedPoints.size());
        system.debug(insertedPoints);
    }

    static testMethod void postScoringInformationContact_Log()
    {
        setupDate();
        Account theAccount =  TestUtils.createAccounts(1, 'Test Accoubt', true)[0];
        Contact theContact = TestUtils.createContacts(1, 'LeadScorinTest', theAccount.Id, true)[0];
        theContact.Email = 'contactEmial@leadScore.test';
        theContact.Phone = '9909909999';
        theContact.FkUser__c = '9966554';
        theContact.Contact_Type__c = 'Primary Contact';
        update theContact;
        PageReference pageRef = Page.ScoringPoints;
        pageRef.getParameters().put('user_lname','testHttp');
        pageRef.getParameters().put('company','testCompany');
        pageRef.getParameters().put('user_email','contactEmial@leadScore.test');
        pageRef.getParameters().put('user_id','99661554');
        pageRef.getParameters().put('business_name','Test bussiness');
        pageRef.getParameters().put('formation_state','California');
        pageRef.getParameters().put('tealium_id',' ');
        pageRef.getParameters().put('business_phone','9909909999');
        pageRef.getParameters().put(criteriaNames[0],'true');
        pageRef.getParameters().put(criteriaNames[1],'true');
       

        Test.setCurrentPage(pageRef);
        Test.startTest();
              ProcessScoringPoints pointsProcessor = new ProcessScoringPoints();
              pointsProcessor.processUrlParameters();
        Test.stopTest();

      
        List<Tealium_Request__c> tealiumRequests = [SELECT Id , Contact__c , Request_Body__c , Matched_Field__c FROM Tealium_Request__c];
        System.assert(!tealiumRequests.isEmpty() , 'Should not be empty');
        System.assertEquals(theContact.Id ,tealiumRequests[0].Contact__c  , 'Right Contact Id should have been populated');
        System.assert(tealiumRequests[0].Request_Body__c.contains('user_lname') , 'user_lname should have been present');
        System.assertEquals('Email' , tealiumRequests[0].Matched_Field__c , 'Should have Matched on Email');
    }

}