src/objects/HVCR_Email_New__c.object
<CustomObject>
    <fields>
        <fullName>BCCAddressesLong__c</fullName>
        <label>BCC</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BCCAddresses__c</fullName>
        <label>BCC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCAddressesLong__c</fullName>
        <label>CC</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCAddresses__c</fullName>
        <label>CC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>HVCR_Case_New</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>HVCR Contacts</relationshipLabel>
        <relationshipName>HVCR_Contact_New</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FromAddressLong__c</fullName>
        <label>From</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FromAddress__c</fullName>
        <label>From</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IsDraft__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDraft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsInbound__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsInbound</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsRead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsRead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsRepliable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this email repliable?</inlineHelpText>
        <label>Repliable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsSent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsSent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReplyToAddressLong__c</fullName>
        <label>ReplyToAddress</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReplyToAddress__c</fullName>
        <label>ReplyToAddress</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SentDate__c</fullName>
        <label>Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Case Pending</fullName>
                </value>
                <value>
                    <fullName>Case Resolved</fullName>
                </value>
                <value>
                    <fullName>Case Unresolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ToAddressesLong__c</fullName>
        <label>To</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ToAddresses__c</fullName>
        <label>To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>HVCR Email New</label>
    <nameField>
        <label>HVCR_Email_New_Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HVCR Emails New</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AttachmentsQuery.cls
public with sharing class AttachmentsQuery
{
	public static List<EmailMessage> getEmailMessages(Boolean isLimit , Id theCaseId)
	{
		if(isLimit)
			return [SELECT Id, Subject,status,toaddress,MessageDate,fromaddress,ccaddress,bccaddress, (SELECT Id, Name, CreatedDate,ContentType FROM Attachments LIMIT 1) FROM EmailMessage WHERE ParentId = :theCaseId order by CreatedDate DESC LIMIT 5];
		else
			return [SELECT Id, Subject,status,toaddress,MessageDate,fromaddress,ccaddress,bccaddress, (SELECT Id, Name, CreatedDate,ContentType FROM Attachments LIMIT 1) FROM EmailMessage WHERE ParentId = :theCaseId order by CreatedDate DESC];
	}
	
	public static List<HVCR_Email_New__c> getHVCREmail(Boolean isLimit ,  Id theCaseId)
	{
		if(isLimit)
			return [SELECT Id,SystemModstamp, isDraft__c, ToAddresses__c, Subject__c, Status__c,
                                                                                            ToAddressesLong__c,CCAddressesLong__c,BCCAddressesLong__c,ReplyToAddressLong__c,FromAddressLong__c,
                                                                                            SentDate__c, ReplyToAddress__c, IsSent__c, IsRepliable__c, IsRead__c,
                                                                                            IsInbound__c, FromAddress__c, Contact__c, Case__c, CCAddresses__c, 
                                                                                            BCCAddresses__c, Name, LastModifiedDate, LastModifiedById,
                                                                                            IsDeleted, CreatedDate,CreatedById, (SELECT Id, Name, CreatedDate,ContentType FROM Attachments LIMIT 1) FROM HVCR_Email_New__c WHERE Case__c = :theCaseId order by createddate desc LIMIT 5];
		else
			return [SELECT Id,SystemModstamp, isDraft__c, ToAddresses__c, Subject__c, Status__c,
                                                                                            ToAddressesLong__c,CCAddressesLong__c,BCCAddressesLong__c,ReplyToAddressLong__c,FromAddressLong__c,
                                                                                            SentDate__c, ReplyToAddress__c, IsSent__c, IsRepliable__c, IsRead__c,
                                                                                            IsInbound__c, FromAddress__c, Contact__c, Case__c, CCAddresses__c, 
                                                                                            BCCAddresses__c, Name, LastModifiedDate, LastModifiedById,
                                                                                            IsDeleted, CreatedDate,CreatedById, (SELECT Id, Name, CreatedDate,ContentType FROM Attachments LIMIT 1) FROM HVCR_Email_New__c WHERE Case__c = :theCaseId order by createddate desc];
	}
	
	
	public static List<Task> getTasks(Boolean isLimit ,  Id theCaseId)
	{
		if(isLimit)
			return [Select Subject, Status, Legacy_CC_Email__c, Id, CreatedDate,legacy_id__c, (Select Id, name,ContentType, CreatedDate From Attachments limit 1) From Task  WHERE WhatId =: theCaseId and isdeleted=false order by createdDate desc LIMIT 5 ALL ROWS];
			
		else
			return [Select Subject, Status, Legacy_CC_Email__c, Id, CreatedDate,legacy_id__c, (Select Id, name,ContentType, CreatedDate From Attachments limit 1) From Task  WHERE WhatId =: theCaseId and isdeleted=false order by createdDate desc ALL ROWS];	
	}
}