src/objects/IADApiGeeEndPoint__mdt.object
<CustomObject>
    <fields>
        <fullName>link__c</fullName>
        <label>link</label>
        <type>Url</type>
    </fields>
    <label>IADApiGeeEndPoint</label>
    <pluralLabel>IADApiGeeEndPoints</pluralLabel>
</CustomObject>

src/classes/PCI_LocalhostController.cls
public class PCI_LocalhostController {
    
    public string PCIbaseURL{get; set;}
    public string SFbaseURL{get; set;}

    public PCI_LocalhostController(){
        
         IADApiGeeEndPoint__mdt baseUrl= [Select Id, Link__c from IADApiGeeEndPoint__mdt where label='PCILocalhost' limit 1]; 
         PCIbaseURL=baseUrl.Link__c;
         SFbaseURL=Url.getSalesforceBaseUrl().toExternalForm();
    }
    
    
}