src/objects/Lead_Attribute__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Lead_Scoring_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lead_Scoring_Bucket__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Scoring Bucket</label>
        <referenceTo>Lead_Scoring_Bucket__c</referenceTo>
        <relationshipName>Lead_Scoring_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Lead_Scoring_Points_del1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Attribute_Id__c</fullName>
        <label>Original Attribute Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_ID__c</fullName>
        <formula>IF(ISBLANK(Lead__c),Contact__r.Id, Lead__r.Id )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Lead Attribute</label>
    <nameField>
        <label>Lead Scoring Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead_Scoring_Bucket__c.object
<CustomObject>
    <fields>
        <fullName>Bucket_Percentage__c</fullName>
        <label>Bucket Percentage</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Total_Bucket_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Bucket Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lead Scoring Bucket</label>
    <nameField>
        <label>Lead Scoring Bucket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Scoring Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead_Scoring_Bucket_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Scoring_Bucket__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Scoring Bucket</label>
        <referenceTo>Lead_Scoring_Bucket__c</referenceTo>
        <relationshipName>Lead_Scoring_Data_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Lead Scoring Bucket Criteria</label>
    <nameField>
        <label>Lead Scoring Bucket Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Scoring Bucket Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScoringServiceHelper.cls
public with sharing class ScoringServiceHelper {
	
	//Method to update total bucket score when a new criteria is added, updated or deleted.
	 public static void updateTotalBucketScore(Set<Id> bucketIds)
	 {
	 	List<Lead_Scoring_Bucket_Criteria__c> allActiveBucketCriteria = [Select Id, 										
																		Name, 
																		Lead_Scoring_Bucket__r.Id,
																		Lead_Scoring_Bucket__r.Bucket_Percentage__c, 
																		Points__c, 
																		Value__c,
																		Active__c From  
																		Lead_Scoring_Bucket_Criteria__c];
		
		Map<Id,Decimal> bucketIdToScore = calculateTotalBUcketScore(allActiveBucketCriteria);
		
		List<Lead_Scoring_Bucket__c> bucketsToUpdate = new List<Lead_Scoring_Bucket__c>();														
		for(Id bucketId: bucketIdToScore.keySet())
		{
			Lead_Scoring_Bucket__c bucket = new Lead_Scoring_Bucket__c(Id = bucketID);
			bucket.Total_Bucket_Score__c = bucketIdToScore.get(bucketId);
			bucketsToUpdate.add(bucket);
		}
		if(!bucketsToUpdate.isEmpty())
		{
			try
			{
				update bucketsToUpdate;
			}
			catch(System.DmlException e)
			{
				for(Integer i = 0 ;i <e.getNumDml(); ++i)
				{
					bucketsToUpdate[e.getDmlIndex(i)].addError('Failed to update the total bucket score'+ e.getDmlMessage(i)+', ID: '+ e.getDmlId(i));
				}
			}
		}
	 }
	 
	 public static List<Lead_Attribute__c> getExistingScoringPoints(Set<ID> leadIds, Set<ID> contactIds)
		{
			List<Lead_Attribute__c> existingPoints = new List<Lead_Attribute__c>();
			if(!leadIds.isEmpty())
			existingPoints = [Select ID,
	 							    Lead__c,
		 						    Name,
		 						    Lead_Scoring_Bucket__c,
	 							    Points__c,
	 							    Value__c,
	 							    Start_Time__c,
	 							    Parent_id__c,
	 							    Activity__c,
	 							    End_Time__c FROM
	 							    Lead_Attribute__c WHERE
	 							    Lead__c In :leadIds];
 		if(!contactIds.isEmpty())
 		existingPoints.addAll([Select ID,
		 							    Contact__c,
			 						    Name,
			 						    Activity__c,
			 						    Lead_Scoring_Bucket__c,
		 							    Points__c,
		 							    Value__c,
		 							    Start_Time__c,
		 							    Parent_id__c,
		 							    End_Time__c FROM
		 							    Lead_Attribute__c WHERE
		 							    contact__c In :contactIds]);
 			return existingPoints;
		} 	
		
		public static List<Lead_Attribute__c> identifyDuplicatePoints(List<Lead_Attribute__c> existingPoints, Map<ID,Map<String,Lead_Attribute__c>> recordIdToPointNameToPoint)
		{
			List<Lead_Attribute__c> pointsToReturn = new List<Lead_Attribute__c>();
	 		for(Lead_Attribute__c point : existingPoints)
	 		{
	 			if(recordIdToPointNameToPoint.containsKey(point.Parent_id__c))
	 			{
	 				system.debug(recordIdToPointNameToPoint.get(point.Parent_id__c));
	 				if(recordIdToPointNameToPoint.get(point.Parent_id__c).containsKey(point.Name))
	 				{
	 					recordIdToPointNameToPoint.get(point.Parent_id__c).get(point.Name).Original_Attribute_Id__c = point.Id;
	 				}
	 				else
	 				pointsToReturn.add(point);
	 			}
	 		}	
			return pointsToReturn;
		}

		public static void deleteDuplicateAttributs(List<Lead_Attribute__c> newAttributes)
		{
			system.debug(newAttributes);
			List<Id> originalIds = new List<Id>();
			List<Lead_Attribute__c> attributesToDelete = new List<Lead_Attribute__c>();
			Map<Id,Lead_Attribute__c> idToAttributeValue = new Map<Id,Lead_Attribute__c>();
			List<Lead_Attribute__c> qeriednewAttributes = [Select Id, Value__c, Original_Attribute_Id__c,Points__c From Lead_Attribute__c Where Id in: newAttributes];
			for(Lead_Attribute__c attribute : qeriednewAttributes)
			{
				if(attribute.Original_Attribute_Id__c != null && attribute.Original_Attribute_Id__c != '')
				{
					attributesToDelete.add(attribute);
					idToAttributeValue.put(attribute.Original_Attribute_Id__c, attribute);
				}
			}

			List<Lead_Attribute__c> queriedAttributes = [Select Id, Value__c From Lead_Attribute__c Where Id in: idToAttributeValue.keySet()];
			for(Lead_Attribute__c attribute : queriedAttributes)
			{
				attribute.Value__c = idToAttributeValue.get(attribute.Id).Value__c;
				attribute.Points__c = idToAttributeValue.get(attribute.Id).Points__c;
			}
			update queriedAttributes;
			delete attributesToDelete;
		}
		
	 
	 public static decimal getTotalScore(Id recordId,Map<Id,Map<Id,Decimal>> recordToBucketToBucketScore, Map<Id,Decimal> bucketIdToTotalScore,Map<Id,Decimal> bucketIdToPercentage)
		{
			Decimal totalScore=0;
			for(Id bucketId : recordToBucketToBucketScore.get(recordId).keySet())
				{
					totalScore = (totalScore + (((recordToBucketToBucketScore.get(recordId).get(bucketId)/bucketIdToTotalScore.get(bucketID)) * bucketIdToPercentage.get(bucketId))));
				} 
			return totalScore; 
		}

	
	//method to create a map of bucket id to bucket total score
	public static Map<Id,Decimal> calculateTotalBUcketScore(List<Lead_Scoring_Bucket_Criteria__c> allActiveBucketCriteria)
	{
		Map<Id,Decimal> bucketScore = new Map<Id,Decimal>();
		for(Lead_Scoring_Bucket_Criteria__c criteria : allActiveBucketCriteria)
		{
			decimal points;
			if(criteria.Active__c == true)
				points = criteria.Points__c;
			else
				points = 0;
			if(bucketScore.containsKey(criteria.Lead_Scoring_Bucket__r.Id))
			{
				bucketScore.put(criteria.Lead_Scoring_Bucket__r.Id,(bucketScore.get(criteria.Lead_Scoring_Bucket__r.Id) + points));
			}
			else
			{
				bucketScore.put(criteria.Lead_Scoring_Bucket__r.Id,points);
			}
		}
		return bucketScore;	
	}
	
	
	//methos to check if the datapoint value is contained in the criteria value
	public static Boolean checkScoreingPointValue(Lead_Attribute__c leadPoint,Lead_Scoring_Bucket_Criteria__c criteria)
	{
		system.debug(leadPoint+',,'+criteria);
		boolean contains = false;
		if(leadPoint.Activity__c == false)
		{
			If(criteria.Value__c == null && leadPoint.Value__c != null && leadPoint.Value__c != ' ')
			{
				contains = true;
				return contains;
			}
			else
			{
				system.debug(criteria.Value__c);
				List<String> criteriaValues = criteria.value__c.split(',');
				for(String value : criteriaValues)
				{
					if(value.trim() == leadPoint.Value__c)
					{
						contains = true;
						break;
					}
				}return contains;
			}
		}
		else
		{
			return true;
		}
	}
	
	public static Set<Id> getBucketIdsForRecalcuationForUpdate(Map<Id , Lead_Scoring_Bucket_Criteria__c> oldBucketCriteria , Map<Id, Lead_Scoring_Bucket_Criteria__c> newBucketCriteria)
	{
		Set<Id> bucketIdsToConsider = new Set<Id>();
		for(Lead_Scoring_Bucket_Criteria__c oldCriteria : oldBucketCriteria.values())
		{
			Lead_Scoring_Bucket_Criteria__c newCriteria = newBucketCriteria.get(oldCriteria.Id);
			if(newCriteria.Lead_Scoring_Bucket__c != oldCriteria.Lead_Scoring_Bucket__c)
			{
				if(!bucketIdsToConsider.contains(newCriteria.Lead_Scoring_Bucket__c))
					bucketIdsToConsider.add(newCriteria.Lead_Scoring_Bucket__c);
				
				if(!bucketIdsToConsider.contains(oldCriteria.Lead_Scoring_Bucket__c))
					bucketIdsToConsider.add(oldCriteria.Lead_Scoring_Bucket__c);
			}
			if(newCriteria.Active__c != oldCriteria.Active__c || newCriteria.Points__c != oldCriteria.Points__c)
			{
				if(!bucketIdsToConsider.contains(newCriteria.Lead_Scoring_Bucket__c))
					bucketIdsToConsider.add(newCriteria.Lead_Scoring_Bucket__c);	
			}
		}	
		
		return bucketIdsToConsider;
	}

	public static Set<Id> getBucketIdsForRecalcuation(List<Lead_Scoring_Bucket_Criteria__c>  bucketCriteria)
	{
		Set<Id> bucketIdsToConsider = new Set<Id>();
		for(Lead_Scoring_Bucket_Criteria__c theCriteria : bucketCriteria)
		{
			if(theCriteria.Lead_Scoring_Bucket__c != null)
			{
				bucketIdsToConsider.add(theCriteria.Lead_Scoring_Bucket__c);
			}
		}	
		
		return bucketIdsToConsider;
	}
		
}