src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>FkUser__c</fullName>
        <externalId>true</externalId>
        <label>FkUser</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_of_Formation__c</fullName>
        <label>State of Formation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tealium_Id__c</fullName>
        <description>Tealium Id</description>
        <externalId>true</externalId>
        <label>Tealium Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>User Order ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead_Attribute__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Lead_Scoring_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Lead_Scoring_Points_del1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Lead Attribute</label>
    <nameField>
        <label>Lead Scoring Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead_Scoring_Bucket_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Lead Scoring Bucket Criteria</label>
    <nameField>
        <label>Lead Scoring Bucket Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Scoring Bucket Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tealium_Request__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tealium Requests</relationshipLabel>
        <relationshipName>Tealium_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Tealium Requests</relationshipLabel>
        <relationshipName>Tealium_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Matched_Field__c</fullName>
        <label>Matched Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Body__c</fullName>
        <label>Request Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>User_Order_Id__c</fullName>
        <label>User Order Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Tealium Request</label>
    <nameField>
        <displayFormat>Request-{00000}</displayFormat>
        <label>Tealium Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tealium Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProcessScoringPoints.cls
public without sharing class ProcessScoringPoints{
    public MAP<string, string> pageParameters;
     public static final string EMAIL = 'unknown@unknown.com';
    public PageReference processUrlParameters()
     {
        pageParameters = ApexPages.currentPage().getParameters();
        system.debug(pageParameters);
        PageReference pageToSend = Page.ScoringPointsResult;
          Id recordId;
          DuplicateChecker.MessageInfo theMessage = new DuplicateChecker.MessageInfo();
        if(pageParameters != null)
        {
            try
            {
                    Lead theLead = new Lead();
                    if(pageParameters.containsKey('user_fname'))
                        theLead.FirstName = pageParameters.get('user_fname');
                    if(pageParameters.containsKey('user_lname'))
                         theLead.LastName = pageParameters.get('user_lname'); 
                    if(pageParameters.containsKey('user_email')  && !String.isBlank(pageParameters.get('user_email')) && pageParameters.get('user_email')!= null)
                         theLead.Email = pageParameters.get('user_email');
                    if(pageParameters.containsKey('formation_state'))
                         theLead.State_of_Formation__c = pageParameters.get('formation_state');
                    if(pageParameters.containsKey('business_phone') && !String.isBlank(pageParameters.get('business_phone')) && pageParameters.get('business_phone')!= null)
                         theLead.Phone = pageParameters.get('business_phone');
                    if(pageParameters.containsKey('tealium_id') && !String.isBlank(pageParameters.get('tealium_id')) && pageParameters.get('tealium_id')!= null)
                         theLead.Tealium_Id__c = pageParameters.get('tealium_id');
                    if(pageParameters.containsKey('user_id') && !String.isBlank(pageParameters.get('user_id')) && pageParameters.get('user_id') != null)
                         theLead.FkUser__c = pageParameters.get('user_id');
                    system.debug(theLead);
                    if(pageParameters.containsKey('active_processing_id'))
                        theMessage.userOrderId = pageParameters.get('active_processing_id');//store active proceesing id
                    recordId = DuplicateChecker.getLeadOrContact(theLead , theMessage);
                    system.debug(recordId);
                    insert createScoringPoints(recordId);
                  
                    pageToSend.getParameters().put('Result','Success');
            }
            catch(DmlException exp)
            {
                

                system.debug(exp);
                pageToSend.getParameters().put('Result','Failed');
                pageToSend.getParameters().put('error',exp.getMessage());
                SendExceptionEmail.sendDMLExceptionEmail(exp, 'Error In creating Lead Scoring Points from Tealium');
        
            }   
        }
        
        logRequest(recordId , theMessage);                                                                                             
        return pageToSend;
     }

     public void logRequest(Id recordId , DuplicateChecker.MessageInfo theMessage)
     {
        
        String theId = recordId;
        Tealium_Request__c theRequest = new Tealium_Request__c();
        if(recordId != null)
        {
            if(theId.startsWith('003'))
            {
                theRequest.Contact__c = recordId;

            }
            else
            {
                theRequest.Lead__c = recordId;
            }
        }
        String keyValuePairs = '';
        for(String theKey : pageParameters.keySet())
        {
            keyValuePairs += theKey +'='+pageParameters.get(theKey)+',';
        }
        theRequest.Request_Body__c = keyValuePairs;
        theRequest.Matched_Field__c = theMessage.matchedField;
        theRequest.User_Order_Id__c = theMessage.userOrderId;
        insert theRequest;
            
     }

     public List<Lead_Attribute__c> createScoringPoints(ID objectId)
     {
        List<Lead_Attribute__c> scoringPointsToInsert = new List<Lead_Attribute__c>();
        for(Lead_Scoring_Bucket_Criteria__c bucketCriteria : [Select Name, Active__c From Lead_Scoring_Bucket_Criteria__c Where Active__c = True And Name In : pageParameters.keySet()]) // include pageParameter
        {
               system.debug(bucketCriteria+'point :'+pageParameters.get(bucketCriteria.Name));
            if(pageParameters.containsKey(bucketCriteria.Name))
               {
                    if(pageParameters.get(bucketCriteria.Name) != null && !String.isBlank(pageParameters.get(bucketCriteria.Name)))
                     {
                         Lead_Attribute__c scoringPoint = new Lead_Attribute__c();
                         scoringPoint.Name = bucketCriteria.Name;
                         scoringPoint.Value__c = pageParameters.get(bucketCriteria.Name);
                         if(SendToCustomEmailController.findObjectName(objectId) == SendToCustomEmailController.LEAD)
                             scoringPoint.Lead__c = objectId;
                         else
                             scoringPoint.Contact__c = objectId;
                         scoringPointsToInsert.add(scoringPoint);
                         system.debug(scoringPointsToInsert+'ScoringPoints');
                     }
               }
        }
        return scoringPointsToInsert;

     }
}