src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <description>matching the fkUserOrder field of OrderItem table in lzdata</description>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Profile_Map_App_ID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Profile map with application ID (tsid)</description>
    <fields>
        <fullName>TSID__c</fullName>
        <label>TSID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Profile Map App ID</label>
</CustomObject>

src/objects/Salesforce_Host_URL__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of internal SF urls</description>
    <fields>
        <fullName>Host_URL__c</fullName>
        <label>Host URL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Salesforce Host URL</label>
</CustomObject>

src/classes/ShowDetailController.cls
global without sharing class ShowDetailController {

    public String contactId {get;set;}
    public String orderId {get;set;}

    public String TSID {get;set;}
    public String hostURL {get;set;}
    public static final String SALESFORCE_BASED_URL = 'Salesforce Based URL'; 
    
    public ShowDetailController()
    {
        getContactRecordID();
        TSID = getTSID();
        hostURL = getHostURL();
    }
    
    public void getContactRecordID()
    {
        String userOrderID = ApexPages.currentPage().getParameters().get('UserOrder');
       
        try
        {
            List<Order_Item__c> orderItemList = [SELECT Order__r.Contact__c , Order__c FROM Order_Item__c WHERE User_Order_ID__c =: userOrderID order by LastModifiedDate desc LIMIT 1];
            if(!orderItemList.isEmpty())
            {
                for(Order_Item__c theItem : orderItemList)
                {
                    contactId = theItem.Order__r.Contact__c;
                    orderId = theItem.Order__c;
                }
            }

        }catch(System.DmlException ex){
            System.debug(ex.getMessage());
        }
        
    }
    
    public String getTSID()
    {
        String userProfile = [SELECT Name FROM Profile WHERE Id =: UserInfo.getProfileId()].Name;
        String tsid;
        try
        {           
            Profile_Map_App_ID__c profileMapAppId = Profile_Map_App_ID__c.getInstance(userProfile);
            
            if(profileMapAppId != null)
            {
                tsid = profileMapAppId.TSID__c;
            }
            
        }catch(System.DmlException ex){
            System.debug(ex.getMessage());
        }
        return tsid;
    }
    
    public String getHostURL()
    {
        String hostURL;
        if(URL.getSalesforceBaseUrl().getHost().contains('cs'))
        {
            hostURL = 'https://'+URL.getSalesforceBaseUrl().getHost();
        }
        else
        {
            Salesforce_Host_URL__c host = Salesforce_Host_URL__c.getInstance(SALESFORCE_BASED_URL);
            hostURL = host.Host_URL__c;
        }    
        return hostURL;
    }
}