src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Base_Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Matching_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Commission_Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activity Commission Eligible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Activity_Contacted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activity Contacted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Activity_Created_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Date time when the activity was created.</description>
        <label>Activity Created By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OrderLeadOpportunitys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activity_Created_DateTime__c</fullName>
        <description>Date time when the activity was created.</description>
        <label>Activity Created DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Activity_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OrderLeadOpportunitys1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activity_SFDC_Id__c</fullName>
        <description>SFDC Id of Activity</description>
        <externalId>true</externalId>
        <label>Activity SFDC Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agent__c</fullName>
        <label>Agent</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agent 1</fullName>
                </value>
                <value>
                    <fullName>Agent 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assistant_Manager__c</fullName>
        <label>Assistant Manager</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Call_Type__c</fullName>
        <label>Call Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unique Queue</fullName>
                </value>
                <value>
                    <fullName>Unique Outbound</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Outbound Follow Up</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Order Matching Activities</relationshipLabel>
        <relationshipName>Order_Matching_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inbound_Outbound__c</fullName>
        <label>Inbound/Outbound</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Score__c</fullName>
        <label>Lead Score</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <label>Lead Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Supervisor__c</fullName>
        <label>Lead Supervisor</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>OrderLeadOpportunitys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <label>Manager</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>OrderLeadOpportunitys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pilot_Group_Contact__c</fullName>
        <label>Contact (Pilot Group Use Only)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Call 1 - Contacted</fullName>
                </value>
                <value>
                    <fullName>Call 1 - VM / Email</fullName>
                </value>
                <value>
                    <fullName>Call 1 - No Answer / Email</fullName>
                </value>
                <value>
                    <fullName>Call 2 - Contacted</fullName>
                </value>
                <value>
                    <fullName>Call 2 - Not Contacted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <label>Queue</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abandoner</fullName>
                </value>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>RA Renewal</fullName>
                </value>
                <value>
                    <fullName>Decline</fullName>
                </value>
                <value>
                    <fullName>Retention</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Activities__c</fullName>
        <label>Total Activities</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Matching Activity</label>
    <nameField>
        <displayFormat>Match-{0000}</displayFormat>
        <label>Order Matching Activity  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Matching Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RA_Renewal_Product_Name__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List all the RA Renewal Product that should be considered for RA commission matching</description>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RA Renewal Product Name</label>
</CustomObject>

src/classes/OrderMatcherHelper.cls
public with sharing class OrderMatcherHelper 
{
	
    
    public static Set<String> RAProductNames
	{
		get
		{
			if(RAProductNames == null)
			{
				 RAProductNames = new Set<String>();
				 List<RA_Renewal_Product_Name__c> rAproducts = RA_Renewal_Product_Name__c.getall().values();
				 for(RA_Renewal_Product_Name__c theProduct : rAproducts)
				 {
						RAProductNames.add(theProduct.Product_Name__c);
				 }
			}
		
			return RAProductNames;
		}
		set;
	}
	
	public static Set<Id> RAProductIds
	{
		get
		{
			if(RAProductIds == null)
			{
				
				 RAProductIds = new Set<Id>();
				 for(Product2 theProduct : [SELECT Id FROM Product2 WHERE Name IN :RAProductNames])
				 {
				 	 RAProductIds.add(theProduct.Id);
				 }
			}
		
			return RAProductIds;
		}
		set;
	}

	
	public static Map<String,Order_Matching_Activity__c> getMatchingActivitiesToUpsert(Map<Id,Map<Id,String>> orderIdToTaskIdAgent , Set<Id> allActivityIds)
	{
		
		Map<String,Order_Matching_Activity__c> matchingActivitiesToUpsert = new Map<String,Order_Matching_Activity__c>(); 
		for(Order_Matching_Activity__c previouslyMatchedActivity : [SELECT Id , Agent__c ,Lead__c, Order__c, Activity_SFDC_Id__c  FROM Order_Matching_Activity__c WHERE Order__c IN :orderIdToTaskIdAgent.keySet()])
		{
			Order_Matching_Activity__c theMatchingActivity = new Order_Matching_Activity__c(Id = previouslyMatchedActivity.Id);
			theMatchingActivity.Agent__c = null;
			matchingActivitiesToUpsert.put(previouslyMatchedActivity.Order__c+'-'+previouslyMatchedActivity.Activity_SFDC_Id__c , theMatchingActivity);
		}
		System.debug('Matched Orders '+orderIdToTaskIdAgent.size());
		Set<Id> usedUpKeys = new Set<Id>();
		for(Order_Matching_Activity__c matchingActivity : [SELECT Id ,Contact__c , Activity_Created_By__c,Activity_Created_DateTime__c,Activity_Owner__c,Activity_Type__c,Activity_Contacted__c, 
														 Activity_Commission_Eligible__c, Activity_SFDC_Id__c , Lead__c , Order__c,Call_Type__c,Queue__c, Total_Activities__C,
														 Assistant_Manager__c,Manager__c, Lead_Supervisor__c , Inbound_Outbound__c , Pilot_Group_Contact__c,Lead_Score__c , Lead_Status__c , Contact_Status__c 
														  FROM Order_Matching_Activity__c WHERE Activity_SFDC_Id__c IN :allActivityIds])
		{
			for(Id theOrderId : orderIdToTaskIdAgent.keySet())
			{
				Map<Id,String> taskIdToAgent =  orderIdToTaskIdAgent.get(theOrderId);
				for(Id theTaskId : taskIdToAgent.keySet())
				{
					Order_Matching_Activity__c theMatch;
					String theUniqueKey = theOrderId+'-'+theTaskId;
					if(theTaskId == matchingActivity.Activity_SFDC_Id__c)  
					{
						if(matchingActivitiesToUpsert.containsKey(theUniqueKey))
						{
							theMatch = matchingActivitiesToUpsert.get(theUniqueKey);
							theMatch.Agent__c = taskIdToAgent.get(theTaskId);
						}
						else if(matchingActivity.Order__c == null && !usedUpKeys.contains(matchingActivity.Id))
						{
							theMatch = new Order_Matching_Activity__c(Id = matchingActivity.Id);
							theMatch.Order__c = theOrderId;
							usedUpKeys.add(matchingActivity.Id);
							theMatch.Agent__c = taskIdToAgent.get(theTaskId);
						}
						else
						{
							theMatch = new Order_Matching_Activity__c(
							Contact__c =  matchingActivity.Contact__c ,
							Activity_Created_DateTime__c = matchingActivity.Activity_Created_DateTime__c ,
							Activity_Created_By__c = matchingActivity.Activity_Created_By__c , Activity_Type__c = matchingActivity.Activity_Type__c,
							Activity_SFDC_Id__c = matchingActivity.Activity_SFDC_Id__c , Activity_Contacted__c = matchingActivity.Activity_Contacted__c,
							Activity_Owner__c = matchingActivity.Activity_Owner__c, ownerId =  matchingActivity.Activity_Created_By__c ,Activity_Commission_Eligible__c = matchingActivity.Activity_Commission_Eligible__c,
							Order__c = theOrderId ,Call_Type__c = matchingActivity.Call_Type__c , Queue__c = matchingActivity.Queue__c,Assistant_Manager__c = matchingActivity.Assistant_Manager__c ,Manager__c = matchingActivity.Manager__c , 
							Lead_Supervisor__c = matchingActivity.Lead_Supervisor__c , Inbound_Outbound__c = matchingActivity.Inbound_Outbound__c , 
							Pilot_Group_Contact__c = matchingActivity.Pilot_Group_Contact__c , Lead_Score__c = matchingActivity.Lead_Score__c,  
							Lead_Status__c = matchingActivity.Lead_Status__c , Contact_Status__c = matchingActivity.Contact_Status__c , Agent__c = taskIdToAgent.get(theTaskId),
							Total_Activities__C = matchingActivity.Total_Activities__C);
						}   	
						matchingActivitiesToUpsert.put(theUniqueKey , theMatch);
					}
					
				}
			}
		}
		
		return matchingActivitiesToUpsert;
	}
	
}