src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <description>matching the fkUserOrder field of OrderItem table in lzdata</description>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Note</fullName>
        <active>true</active>
        <description>Order Note from Notepad</description>
        <label>Note</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateNoteFromOrderItemTest.cls
@isTest
public with sharing class CreateNoteFromOrderItemTest
{

	static void setupData()
	{

	}
	
	static testMethod void testCreateTask()
	{
		
		Order__c testOrder = TestUtils.createOrders(1 , null , true)[0];
		List<Order_Item__c> theItems = TestUtils.createOrderItems(1 , testOrder.Id , false);
		theItems[0].User_Order_ID__c = '12345';
		insert theItems;

		ApexPages.StandardController sc = new ApexPages.StandardController(theItems[0]);
        CreateOrderNoteFromOrderItemController theController = new CreateOrderNoteFromOrderItemController(sc);
        PageReference pageRef = Page.CreateOrderNoteFromOrderItem;
        pageRef.getParameters().put('id', String.valueOf(theItems[0].Id));
        Test.setCurrentPage(pageRef);

        Test.startTest();
        	theController.createTask();
        Test.stopTest();

        List<Task> createdTasks = [SELECT Id , Subject , User_Order_ID__c FROM Task WHERE WhatId =:testOrder.Id];
        System.assertEquals(1 , createdTasks.size() , '1 task should have been created');
        System.assertEquals('Order Note' , createdTasks[0].Subject , 'Right subject should have been populated');
        System.assertEquals('12345' , createdTasks[0].User_Order_ID__c , 'Right Processing Number should have been populated');
     }  
	 	
}