src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>Is_First_Subscription_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Marks true if the order item is first subscription renewal for any subscriptions</description>
        <label>Is First Subscription Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LZ_Order_Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>LZ Order Item ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Parent_Commission_Ignore__c</fullName>
        <description>Parent Commission Ignore</description>
        <formula>Parent__r.Commission_Ignore__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Commission Ignore</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship field to the parent record within Order Item object.</description>
        <label>Parent</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order_Matching_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Commission_Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activity Commission Eligible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Activity_Created_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Date time when the activity was created.</description>
        <label>Activity Created By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OrderLeadOpportunitys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activity_Created_DateTime__c</fullName>
        <description>Date time when the activity was created.</description>
        <label>Activity Created DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agent__c</fullName>
        <label>Agent</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agent 1</fullName>
                </value>
                <value>
                    <fullName>Agent 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Order Matching Activities</relationshipLabel>
        <relationshipName>Order_Matching_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>OrderLeadOpportunitys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Replaced_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field points to the newly adjusted commission matching record from the original commission matching record</description>
        <label>Replaced By</label>
        <referenceTo>Order_Matching_Activity__c</referenceTo>
        <relationshipLabel>Commission Matching Replaced</relationshipLabel>
        <relationshipName>Order_Matching_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Matching Activity</label>
    <nameField>
        <displayFormat>Match-{0000}</displayFormat>
        <label>Order Matching Activity  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Matching Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OrderItemMatchingBatch.cls
global class OrderItemMatchingBatch implements Database.Batchable<sObject>
{ 
   String Query;
   
   global OrderItemMatchingBatch(String timeFrame)
   {
      String theQuery;
      Set<Id> conIdSet = new Set<Id>();
      //List<Contact> contList = [select id,name,(SELECT ID, Agent__c , Activity_Created_By__c , Activity_Created_DateTime__c ,Order__c, Contact__c FROM Order_Matching_Activities__r Where Activity_Commission_Eligible__c = true and createdDate >= last_90_days) from contact where id in (select contact__c from Order__c where createdDate >= last_90_days)];
      List<Order_matching_activity__c> omList = [SELECT ID, Agent__c , Activity_Created_By__c , Activity_Created_DateTime__c ,Order__c, Contact__c,Contact__r.name FROM Order_Matching_Activity__c Where Activity_Commission_Eligible__c = true and contact__c != null and createdDate >= this_month];
      //if(!conIdSet.isEmpty()){
        // theQuery = 'select id,Is_First_Subscription_Renewal__c,Parent_Commission_Ignore__c,Parent__c,Order__c,LZ_Order_Item_Id__c from Order_Item__c where Order__r.Contact__c in :conIdSet';
      //}
      theQuery = 'SELECT ID, Agent__c , Activity_Created_By__c , Activity_Created_DateTime__c ,Order__c, Contact__c,Contact__r.name FROM Order_Matching_Activity__c Where Activity_Commission_Eligible__c = true and contact__c != null and createdDate >= '+timeFrame;
      System.debug('query #### '+theQuery);
       Query= theQuery;
   }
   global Database.QueryLocator start(Database.BatchableContext BC)
   {
      return Database.getQueryLocator(query);
   }
        
   global void execute(Database.BatchableContext info, List<sObject> scope)
   {
      List<Order_matching_activity__c> orderMatchAct = new List<Order_matching_activity__C>((List<Order_matching_activity__C>)scope);
      Set<Id> conIdSet = new Set<Id>();
      for(Order_Matching_Activity__c oma : orderMatchAct){
         conIdSet.add(oma.contact__c);
      }
      List<Id> conIdList = new List<Id>(conIdSet);
      System.debug('conidset size ### '+conIdSet.size());
      List<Order_Item__c> orderItems = new List<Order_Item__c>();
      orderItems = [select id,Is_First_Subscription_Renewal__c,Parent_Commission_Ignore__c,Parent__c,Order__c,LZ_Order_Item_Id__c from Order_Item__c where Order__r.Contact__c in :conIdList];
      OrderItemMatcher theOrderItemmatcher = new OrderItemMatcher();
      theOrderItemmatcher.processOrderItemsForCommission(orderItems );
   }     
   
   global void finish(Database.BatchableContext info)
   {     
        System.debug('Am I done?');
   } 
}