src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Order_ID__c</fullName>
        <description>matching the fkUserOrder field of OrderItem table in lzdata</description>
        <externalId>true</externalId>
        <label>Processing Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Note</fullName>
        <active>true</active>
        <description>Order Note from Notepad</description>
        <label>Note</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateOrderNoteFromOrderItemController.cls
public with sharing class CreateOrderNoteFromOrderItemController
{
    public Task theTask {get; set;}
    public String lastError {get; set;}
    ApexPages.StandardController theController;
    Id orderItemId;
    public String processingNumber{get;set;}
    Id orderId;
    public CreateOrderNoteFromOrderItemController(ApexPages.StandardController controller) 
    {
        theController = controller;
        theTask = new Task();
        orderItemId = theController.getRecord().Id;     
        for(Order_Item__c theItem : [SELECT Id , Order__c ,  User_Order_ID__c FROM Order_Item__c WHERE Id = :orderItemId])
        {
            orderId = theItem.Order__c;
            processingNumber = theItem.User_Order_ID__c;
        }
        lastError = '';

    }
    
     public PageReference createTask()
     {
       try 
       {
            theTask.Status = 'Completed';
            theTask.ActivityDate = Date.today();
            theTask.Subject = 'Order Note';
            theTask.WhatId = orderId;
            theTask.Priority = 'Normal';
            theTask.Type = 'Note';
            theTask.User_Order_ID__c = processingNumber;
            insert theTask;
            
            theTask = new Task();
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Order Note Created.'));
            
        } catch(System.Exception ex){
           lastError = ex.getMessage();
           ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, lastError));
        }
        return null;
     }    
}