src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact_State__c</fullName>
        <label>Contact State</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processing_Status_Date_Time__c</fullName>
        <formula>User_Order_Extension__r.Processing_Status_Date_Time__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Processing Status Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <formula>User_Order_Extension__r.Processing_Status__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Processing Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Order_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Order Extension</label>
        <referenceTo>User_Order_Extension__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Order_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Order Extension</label>
        <referenceTo>User_Order_Extension__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Processing_Status__c.object
<CustomObject>
    <label>Processing Status</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processing Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_Order_Extension__c.object
<CustomObject>
    <fields>
        <fullName>Processing_Status_Date_Time__c</fullName>
        <label>Processing Status Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Processing Status</label>
        <referenceTo>Processing_Status__c</referenceTo>
        <relationshipName>User_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Order Extension</label>
    <nameField>
        <displayFormat>UOE-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Order Extensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MagicTimeCampaignBatchTest.cls
@isTest
public class MagicTimeCampaignBatchTest {
    
    public MagicTimeCampaignBatchTest() {
        
    }

    static List<Account> testAccounts;
    static List<Contact> testContacts;
    static List<Order__c> testOrders;
    static List<Order_Item__c> testOrderItems;
    static User_Order_Extension__c firstUserOrderExtension;
    static User_Order_Extension__c secondUserOrderExtension;
  
    final static String TEST_ACCOUNT = 'Test Account';
    final static String TEST_CONTACT = 'Test Contact';
    final static Integer SIZE = 100; 

    static void setupData()
    {
        testContacts = new List<Contact>();
        testOrderItems = new List<Order_Item__c>();
        testAccounts = TestUtils.createAccounts(SIZE , TEST_ACCOUNT , false);
        insert testAccounts;

        for(Account theAccount : testAccounts)
        {
            Contact theContact = TestUtils.createContacts(1 , TEST_CONTACT , theAccount.Id , false)[0];
            testContacts.add(theContact);
        }

        insert testContacts;

        firstUserOrderExtension = new User_Order_Extension__c();
        firstUserOrderExtension.Processing_Status__c = CampaignRulesSetup.sentToCustomerProcessingStatus.Id;
        firstUserOrderExtension.Processing_Status_Date_Time__c = Date.today().addDays(-16);
        insert firstUserOrderExtension;

        secondUserOrderExtension = new User_Order_Extension__c();
        secondUserOrderExtension.Processing_Status__c = CampaignRulesSetup.sentToCustomerProcessingStatus.Id;
        secondUserOrderExtension.Processing_Status_Date_Time__c = Date.today().addDays(-190);
        insert secondUserOrderExtension;

    }

    static testMethod void testPostPurchaseCampaignBatchWithMagicTime()
    {
        CampaignRulesSetup.setupCampaignWithRules();
        setupData();
        testOrders = new List<Order__c>();
        for(Integer i = 0 ; i<SIZE/2 ; ++i)
        {
            Order__c theOrder = TestUtils.createOrders(1 , CampaignRulesSetup.testProducts[0].Id , false)[0]; // Business Formation Product Line
            theOrder.Contact__c = testContacts[i].Id;
            theOrder.Contact_State__c = 'CA';
            testOrders.add(theOrder);   
        }
        for(Integer i = SIZE/2 ; i<SIZE ; ++i)
        {
            Order__c theOrder = TestUtils.createOrders(1 , CampaignRulesSetup.testProducts[0].Id , false)[0]; // Business Formation Product Line
            theOrder.Contact__c = testContacts[i].Id;
            theOrder.Contact_State__c = 'TX';
            testOrders.add(theOrder);   
        }
        insert testOrders;
               
        Test.startTest();
            MagicTimeCampaignBatch theBatch = new MagicTimeCampaignBatch();
            Database.executeBatch(theBatch , SIZE);
        Test.stopTest();

        List<CampaignMember> campaignMembers = [SELECT Id FROM CampaignMember];
        System.assertEquals(SIZE , campaignMembers.size() , '100 Campaign Members should have been created');

    }

}