src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Process__c</fullName>
        <formula>Base_Product__r.Process__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <formula>Base_Product__r.Product_Line__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <description>matching Process table in LZData</description>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Line</label>
        <referenceTo>Product_Line__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product_Line__c.object
<CustomObject>
    <description>matching ProductLine lookup table in LZData</description>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Relationship_Type__c.object
<CustomObject>
    <description>matching RelationshipType table in LZData</description>
    <label>Relationship Type</label>
    <nameField>
        <label>Relationship Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/OrderExceptionOwnerChangeBatchTest.cls
/*
	Created by: Artyom M.
	Per story: B-28448
*/
@isTest
public class OrderExceptionOwnerChangeBatchTest {
	static Order_Exception__c newExc;
	static Product2 testProduct;
	final static String PRODUCT_LINE = 'Intellectual Property';
	static Id relationshipTypeId;
	static Product_Line__c testProductLine;
	static void setup() {
		Group grp = new Group(Name = 'Order Due 3',  DeveloperName = 'Dev',  Type = 'Queue');
		insert grp;
		QueueSobject mappingObject  = new QueueSobject(QueueId = grp.Id,  SobjectType = 'Order_Exception__c');
		System.runAs(TestUtils.ADMIN_USER) {
			insert mappingObject;
		}
		
		Process__c testProcess = TestUtils.createProcesses(1, 'Test', true)[0];
		
		testProduct = TestUtils.createProducts(1 , 'Test Product', false)[0];
        testProductLine = TestUtils.createProductLines(1 , PRODUCT_LINE , false)[0];
        testProductLine.Name = PRODUCT_LINE;
        insert testProductLine;
        
        relationshipTypeId = TestUtils.createRelationshipTypesTypes(1 , 'Process', true)[0].Id;
        testProduct.Product_Line__c = testProductLine.Id;
        testProduct.Relationship_Type__c = relationshipTypeId;
        testProduct.Process__c = testProcess.Id;
        insert testProduct; 
		
		
		
		Order__c testOrder = TestUtils.createOrders(1 , testProduct.Id , true)[0];
        newExc = new Order_Exception__c();
        newExc.Order_Number__c = testOrder.Id;
        newExc.Due_Date__c = System.now().addDays(3);
        newExc.OwnerId = grp.Id;
        insert newExc;
        
	}
	static testMethod void testBatch() {
		OrderExceptionOwnerChangeBatchSchedule bch = new OrderExceptionOwnerChangeBatchSchedule();
	    String cron = '0 0 9-17 ? * MON-FRI';
	    String jobId = System.schedule('OrderExceptionOwnerChangeBatchSchedule', cron, bch);
	}
	static testMethod void testBatch2() {
		setup();
		OrderExceptionOwnerChangeBatch bch = new OrderExceptionOwnerChangeBatch();
		Id batchId = Database.executeBatch(bch);
	}
	
	static testMethod void orderExceptionQueueAssignmentByIdTest() {
		setup();
		Id id = newExc.Id;
		List<Id> lst = new List<Id>();
		lst.add(id);
		OrderExceptionOwnerChangeBatch.orderExceptionQueueAssignmentById(lst);
	}
	
    
}