src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>ACR_Date_Time__c</fullName>
        <formula>User_Order_Extension__r.ACR_Date_Time__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ACR Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Base_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The base product of the order.  Data integration will populate this field.</description>
        <label>Base Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Status__c</fullName>
        <label>Fulfillment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-Sale</fullName>
                </value>
                <value>
                    <fullName>Not Yet Started</fullName>
                </value>
                <value>
                    <fullName>Entity Name Avail</fullName>
                </value>
                <value>
                    <fullName>Pre-Filing Prob</fullName>
                </value>
                <value>
                    <fullName>Sent for Sig</fullName>
                </value>
                <value>
                    <fullName>Sent to SOS</fullName>
                </value>
                <value>
                    <fullName>Docs Rec’d</fullName>
                </value>
                <value>
                    <fullName>Docs Backends</fullName>
                </value>
                <value>
                    <fullName>Sent to Cust</fullName>
                </value>
                <value>
                    <fullName>TM Search</fullName>
                </value>
                <value>
                    <fullName>TM G&amp;S</fullName>
                </value>
                <value>
                    <fullName>TM L&amp;S</fullName>
                </value>
                <value>
                    <fullName>TM App Prep</fullName>
                </value>
                <value>
                    <fullName>TM App Filed</fullName>
                </value>
                <value>
                    <fullName>Office Action</fullName>
                </value>
                <value>
                    <fullName>TM SOU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_Matter__c</fullName>
        <formula>User_Order_Extension__r.Legal_Matter__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Legal Matter</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Date_Time_Created__c</fullName>
        <description>Store the created date time of the order created in LZ Data</description>
        <label>Order Date/Time Created</label>
        <type>DateTime</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ACRSOrderController.cls
public with sharing class ACRSOrderController {
	 private final Account acct;
	 Set<String> productNames = new Set<String>{'Business Advantage Pro Attorney Consultation','Legal Advantage Plus Attorney Consultation'};
	 public List<Order__c> acrsOrders{get;set;}
	 public ACRSOrderController(ApexPages.StandardController stdController) {
        this.acct = (Account)stdController.getRecord();
     	acrsOrders = [SELECT Id , Base_Product__r.Name , Order_Date_Time_Created__c , ACR_Date_Time__c , Legal_Matter__c ,  Fulfillment_Status__c , Name FROM Order__c WHERE Account__c =:acct.Id AND Base_Product__r.Name IN :productNames];
     }
}