src/objects/Order360__c.object
<CustomObject>
    <fields>
        <fullName>Days_from_Creation__c</fullName>
        <formula>NOW() - CreatedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days from Creation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Matching_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Matching Activity</label>
        <referenceTo>Order_Matching_Activity__c</referenceTo>
        <relationshipName>Order360</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipLabel>Active Revenue (Parent Order Item)</relationshipLabel>
        <relationshipName>Active_Revenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Saved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscription Saved</label>
        <type>Checkbox</type>
    </fields>
    <label>Active Revenue</label>
    <nameField>
        <displayFormat>Ord360-{0000}</displayFormat>
        <label>Order360 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Active Revenue</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Order line item detail from LZ database</description>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Active Won&apos;t Renew</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Not Yet Started</fullName>
                </value>
                <value>
                    <fullName>Payment Due</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order_Matching_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Is_Subscription_Activity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Subscription Activity?</label>
        <type>Checkbox</type>
    </fields>
    <label>Order Matching Activity</label>
    <nameField>
        <displayFormat>Match-{0000}</displayFormat>
        <label>Order Matching Activity  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Matching Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ss_days__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This settings contains the number of days after which should look if the subscription is saved or not</description>
    <label>Subscription save days</label>
</CustomObject>

src/classes/SubSave30DayBatch.cls
global class SubSave30DayBatch implements Database.Batchable<sObject> ,  Database.Stateful{
    
    String query;
    public static String ACTIVE = 'Active';
    public static DECIMAL SUBSCRIPTION_DAYS
    {
        get
        {
            if(SUBSCRIPTION_DAYS == null) 
            {
                for (ss_days__c ssDays : [SELECT Name  FROM ss_days__c LIMIT 1])
                {
                    SUBSCRIPTION_DAYS = Decimal.valueOf(ssDays.Name);
                }
            }
            return SUBSCRIPTION_DAYS;
        } 
        set;
    }
    Date SUBSCRIPTION_CREATED_DATE = system.today().addDays(-Integer.valueOf(SUBSCRIPTION_DAYS));
    Date SUBSCRIPTION_CREATED_DATE2 = system.today().addDays(-Integer.valueOf(SUBSCRIPTION_DAYS) + 1); //to compare created date
    global SubSave30DayBatch()
    {
        system.debug(system.today());
        system.debug('date = '+ SUBSCRIPTION_CREATED_DATE);
        query = 'SELECT Days_from_Creation__c , Order_Matching_Activity__r.Is_Subscription_Activity__c ,Parent_Order_Item__c , Parent_Order_Item__r.Subscription_Status__c , Subscription_Saved__c FROM Order360__c WHERE Order_Matching_Activity__r.Is_Subscription_Activity__c = True AND CreatedDate >=: SUBSCRIPTION_CREATED_DATE and CreatedDate <=: SUBSCRIPTION_CREATED_DATE2';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Order360__c> scope)
    {
        for(Order360__c theActivieRevenue : scope)
        {
            if(theActivieRevenue.Parent_Order_Item__c != null)
            {
                if(theActivieRevenue.Parent_Order_Item__r.Subscription_Status__c == ACTIVE)
                    theActivieRevenue.Subscription_Saved__c = true;
            }
        }
        try
        {
            update scope;
        }
        catch(DmlException exp)
        {
            SendExceptionEmail.sendDMLExceptionEmail(exp, 'Error in processing the SUB SAVE records.');
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
    

}