src/objects/Sales_Adjustment__c.object
<CustomObject>
    <description>Intake form for Sales Adjustment</description>
    <fields>
        <fullName>Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Adjustment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_of_Adjustment__c</fullName>
        <label>Amount of Adjustment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_of_Adjustment__c</fullName>
        <label>Type of Adjustment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contests</fullName>
                </value>
                <value>
                    <fullName>Pilots</fullName>
                </value>
                <value>
                    <fullName>Training Assistance</fullName>
                </value>
                <value>
                    <fullName>Awards</fullName>
                </value>
                <value>
                    <fullName>Training Bonus</fullName>
                </value>
                <value>
                    <fullName>Technical Issue</fullName>
                </value>
                <value>
                    <fullName>Kickers</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Adjustment</label>
    <nameField>
        <displayFormat>Adjustment-{0000}</displayFormat>
        <label>Sales Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Adjustment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SalesAdjustmentServiceTest.cls
@isTest
public with sharing class SalesAdjustmentServiceTest {
    public SalesAdjustmentServiceTest() {
        
    }
  
    static testMethod void testCreateManualSharing()
    {
        User testManager = TestUtils.createUser('TestUser' , TestUtils.salesMgrProfileId  ,true);
        User testSalesUser = TestUtils.createUser('SaleUser' , TestUtils.salesAgentProfileId , true);
        List<Sales_Adjustment__c> salesAdjustmentsToUpdate = new List<Sales_Adjustment__c>();
        System.runAs(testManager)
        {
            Test.startTest();
                for(Integer i = 0 ; i< 50 ; ++i)
                {
                    Sales_Adjustment__c salesAdjustment = new Sales_Adjustment__c();
                    salesAdjustment.Amount_of_Adjustment__c = 100;
                    salesAdjustment.Type_of_Adjustment__c = 'Contests';
                    salesAdjustment.Agent__c = testSalesUser.Id;
                    salesAdjustmentsToUpdate.add(salesAdjustment);
                    
                }

                insert salesAdjustmentsToUpdate;
            Test.stopTest();
        }
        System.assertEquals(50 , [SELECT Id FROM Sales_Adjustment__c].size() , '50 Adjustments');
        List<Sales_Adjustment__Share> adjustmentShares = [SELECT Id , AccessLevel , RowCause , UserOrGroupId  FROM Sales_Adjustment__Share WHERE UserOrGroupId = :testSalesUser.Id];
        System.assertEquals(50 , adjustmentShares.size() , '50 records should have been created');

        for(Sales_Adjustment__Share theShare : adjustmentShares)
        {
            System.assertEquals(theShare.AccessLevel, 'Read');
            System.assertEquals(theShare.RowCause, 'Manual');
            System.assertEquals(theShare.UserOrGroupId, testSalesUser.Id);
              
        }
    }
}