src/objects/StatesMap__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Is_State__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is State</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State_Id__c</fullName>
        <label>State Id</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State_code__c</fullName>
        <label>State code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>StatesMap</label>
</CustomObject>

src/classes/StatePicklistValues_Test.cls
@isTest
private class StatePicklistValues_Test {
    @testSetup
    private static void setupTestData() {
        // Create Admin User
        TestUtils.createUser('adminuser' + DateTime.now().getTime(), [SELECT Id FROM Profile WHERE Name ='SYStem Administrator' LIMIT 1].Id,true);
        
        List<StatesMap__c> stateMapList = new List<StatesMap__c>();
        stateMapList.add(new StatesMap__c (Name='NewYork',Is_State__c=true, State_code__c='ny', State_Id__c=78));
        stateMapList.add(new StatesMap__c (Name='Texas',Is_State__c=true, State_code__c='tx', State_Id__c=10));
        insert stateMapList;
    }
    
    @isTest private static void getStateNames1() {
        User u =[SELECT Id, Name FROM User WHERE profile.Name = 'SYStem Administrator' And IsActive=true LIMIT 1];
        List<StatesMap__c> stateMapL;
        system.runAs(u){
            Test.startTest();  
            	stateMapL = new List<StatesMap__c>();
            	stateMapL = StatePicklistValues.getStateNames();
            Test.stopTest();
            system.assert(stateMapL!=null);
        }
    }
}